// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ypaint/sdf/gen-sdf-code.py

#pragma once

#include <stddef.h>
#include <yetty/ypaint-core/buffer.h>
#include <yetty/ysdf/types.gen.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Parse YAML body and add primitives to canvas.
 * @param canvas Target canvas
 * @param yaml YAML string (null-terminated)
 * @param len Length of YAML string
 * @return 0 on success, -1 on error
 */
int ypaint_sdf_yaml_parse(struct yetty_ypaint_buffer *canvas, const char *yaml,
                          size_t len);

#ifdef __cplusplus
}
#endif
