// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ypaint/sdf/gen-sdf-code.py

#pragma once

#include <yetty/ypaint/sdf/ypaint-sdf-types.gen.h>
#include <yetty/ypaint/core/ypaint-canvas.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Parse YAML body and add primitives to canvas.
 * @param canvas Target canvas
 * @param yaml YAML string (null-terminated)
 * @param len Length of YAML string
 * @return 0 on success, -1 on error
 */
int ypaint_sdf_yaml_parse(struct ypaint_canvas *canvas, const char *yaml, size_t len);

#ifdef __cplusplus
}
#endif