# Minimal configuration for riscv64-softmmu - only virt machine
# Target: virtio-9p + virtio-net + qcow2, no graphics

# Disable all machines except virt
CONFIG_SPIKE=n
CONFIG_SIFIVE_E=n
CONFIG_SIFIVE_U=n
CONFIG_MICROCHIP_PFSOC=n
CONFIG_SHAKTI_C=n
CONFIG_XIANGSHAN_KUNMINGHU=n
CONFIG_MIPS_BOSTON_AIA=n
CONFIG_MICROBLAZE_V=n
CONFIG_OPENTITAN=n

# Disable device categories
CONFIG_PCI_DEVICES=n
CONFIG_TEST_DEVICES=n

# Disable unused virtio devices
CONFIG_VIRTIO_GPU=n
CONFIG_VIRTIO_VGA=n
CONFIG_VIRTIO_BLK=n
CONFIG_VIRTIO_BALLOON=n
CONFIG_VIRTIO_CRYPTO=n
CONFIG_VIRTIO_IOMMU=n
CONFIG_VIRTIO_INPUT=n
CONFIG_VIRTIO_INPUT_HOST=n
CONFIG_VIRTIO_PMEM=n
CONFIG_VIRTIO_RNG=n
CONFIG_VIRTIO_SCSI=n
CONFIG_VHOST_USER=n
CONFIG_VHOST_KERNEL=n
CONFIG_VHOST_USER_BLK=n
CONFIG_VHOST_USER_FS=n
CONFIG_VHOST_USER_GPU=n
CONFIG_VHOST_USER_INPUT=n
CONFIG_VHOST_USER_SCSI=n
CONFIG_VHOST_USER_VSOCK=n

# Disable SCSI
CONFIG_SCSI=n

# Disable USB
CONFIG_USB=n
CONFIG_USB_OHCI=n
CONFIG_USB_EHCI=n
CONFIG_USB_XHCI=n

# Disable sound
CONFIG_HDA=n

# Disable display
CONFIG_VGA=n
CONFIG_QXL=n
CONFIG_BOCHS_DISPLAY=n

# Disable misc
CONFIG_NVME_PCI=n
CONFIG_TPM=n
CONFIG_TPM_TIS_SYSBUS=n

# Disable ACPI/SMBIOS/PCI (patched Kconfig to allow this)
CONFIG_ACPI=n
CONFIG_ACPI_PCI=n
CONFIG_SMBIOS=n
CONFIG_PCI=n
CONFIG_PCI_EXPRESS_GENERIC_BRIDGE=n
CONFIG_PFLASH_CFI01=n
CONFIG_SIFIVE_TEST=n
CONFIG_FW_CFG_DMA=n
CONFIG_RISCV_IOMMU=n

# Disable debug/misc features
CONFIG_IVSHMEM_FLAT_DEVICE=n
CONFIG_SPDM_SOCKET=n
CONFIG_UEFI_VARS=n
CONFIG_VIRTIO_SND=n

# Keep only virt
# CONFIG_RISCV_VIRT=y is default
