// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ypaint/sdf/gen-sdf-code.py

#pragma once

#include "ypaint-sdf-types.gen.h"
#include <yetty/ypaint/core/ypaint-buffer.h>

#ifdef __cplusplus
extern "C" {
#endif

struct yetty_ypaint_id_result ypaint_sdf_add_circle(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_circle *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_box(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_box *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_segment(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_segment *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_triangle(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_triangle *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_ellipse(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_ellipse *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_arc(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_arc *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_rounded_box(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_rounded_box *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_rhombus(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_rhombus *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_pentagon(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_pentagon *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_hexagon(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_hexagon *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_star(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_star *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_pie(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_pie *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_ring(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_ring *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_heart(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_heart *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_cross(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_cross *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_rounded_x(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_rounded_x *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_capsule(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_capsule *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_moon(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_moon *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_egg(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_egg *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_octogon(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_octogon *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_hexagram(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_hexagram *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_pentagram(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_pentagram *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_sphere_3d(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_sphere_3d *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_box_3d(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_box_3d *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_torus_3d(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_torus_3d *geom);

struct yetty_ypaint_id_result ypaint_sdf_add_cylinder_3d(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_cylinder_3d *geom);

#ifdef __cplusplus
}
#endif