// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ypaint/sdf/gen-sdf-code.py

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum YPaintSdfType {
    YPAINT_SDF_CIRCLE = 0,
    YPAINT_SDF_BOX = 1,
    YPAINT_SDF_SEGMENT = 2,
    YPAINT_SDF_TRIANGLE = 3,
    YPAINT_SDF_ELLIPSE = 6,
    YPAINT_SDF_ARC = 7,
    YPAINT_SDF_ROUNDED_BOX = 8,
    YPAINT_SDF_RHOMBUS = 9,
    YPAINT_SDF_PENTAGON = 10,
    YPAINT_SDF_HEXAGON = 11,
    YPAINT_SDF_STAR = 12,
    YPAINT_SDF_PIE = 13,
    YPAINT_SDF_RING = 14,
    YPAINT_SDF_HEART = 15,
    YPAINT_SDF_CROSS = 16,
    YPAINT_SDF_ROUNDED_X = 17,
    YPAINT_SDF_CAPSULE = 18,
    YPAINT_SDF_MOON = 19,
    YPAINT_SDF_EGG = 20,
    YPAINT_SDF_OCTOGON = 28,
    YPAINT_SDF_HEXAGRAM = 29,
    YPAINT_SDF_PENTAGRAM = 30,
    YPAINT_SDF_SPHERE_3D = 100,
    YPAINT_SDF_BOX_3D = 101,
    YPAINT_SDF_TORUS_3D = 103,
    YPAINT_SDF_CYLINDER_3D = 105,
} YPaintSdfType;

typedef struct YPaintSdfCircle {
    float cx;
    float cy;
    float r;
} YPaintSdfCircle;

typedef struct YPaintSdfBox {
    float cx;
    float cy;
    float hw;
    float hh;
    float round;
} YPaintSdfBox;

typedef struct YPaintSdfSegment {
    float x0;
    float y0;
    float x1;
    float y1;
} YPaintSdfSegment;

typedef struct YPaintSdfTriangle {
    float ax;
    float ay;
    float bx;
    float by;
    float cx;
    float cy;
} YPaintSdfTriangle;

typedef struct YPaintSdfEllipse {
    float cx;
    float cy;
    float rx;
    float ry;
} YPaintSdfEllipse;

typedef struct YPaintSdfArc {
    float cx;
    float cy;
    float sc_x;
    float sc_y;
    float ra;
    float rb;
} YPaintSdfArc;

typedef struct YPaintSdfRoundedBox {
    float cx;
    float cy;
    float hw;
    float hh;
    float r0;
    float r1;
    float r2;
    float r3;
} YPaintSdfRoundedBox;

typedef struct YPaintSdfRhombus {
    float cx;
    float cy;
    float bx;
    float by;
} YPaintSdfRhombus;

typedef struct YPaintSdfPentagon {
    float cx;
    float cy;
    float r;
} YPaintSdfPentagon;

typedef struct YPaintSdfHexagon {
    float cx;
    float cy;
    float r;
} YPaintSdfHexagon;

typedef struct YPaintSdfStar {
    float cx;
    float cy;
    float r;
    float n;
    float m;
} YPaintSdfStar;

typedef struct YPaintSdfPie {
    float cx;
    float cy;
    float sc_x;
    float sc_y;
    float r;
} YPaintSdfPie;

typedef struct YPaintSdfRing {
    float cx;
    float cy;
    float nx;
    float ny;
    float r;
    float th;
} YPaintSdfRing;

typedef struct YPaintSdfHeart {
    float cx;
    float cy;
    float scale;
} YPaintSdfHeart;

typedef struct YPaintSdfCross {
    float cx;
    float cy;
    float bx;
    float by;
    float r;
} YPaintSdfCross;

typedef struct YPaintSdfRoundedX {
    float cx;
    float cy;
    float w;
    float r;
} YPaintSdfRoundedX;

typedef struct YPaintSdfCapsule {
    float ax;
    float ay;
    float bx;
    float by;
    float r;
} YPaintSdfCapsule;

typedef struct YPaintSdfMoon {
    float cx;
    float cy;
    float d;
    float ra;
    float rb;
} YPaintSdfMoon;

typedef struct YPaintSdfEgg {
    float cx;
    float cy;
    float ra;
    float rb;
} YPaintSdfEgg;

typedef struct YPaintSdfOctogon {
    float cx;
    float cy;
    float r;
} YPaintSdfOctogon;

typedef struct YPaintSdfHexagram {
    float cx;
    float cy;
    float r;
} YPaintSdfHexagram;

typedef struct YPaintSdfPentagram {
    float cx;
    float cy;
    float r;
} YPaintSdfPentagram;

typedef struct YPaintSdfSphere3D {
    float px;
    float py;
    float pz;
    float r;
} YPaintSdfSphere3D;

typedef struct YPaintSdfBox3D {
    float px;
    float py;
    float pz;
    float bx;
    float by;
    float bz;
} YPaintSdfBox3D;

typedef struct YPaintSdfTorus3D {
    float px;
    float py;
    float pz;
    float majorR;
    float minorR;
} YPaintSdfTorus3D;

typedef struct YPaintSdfCylinder3D {
    float px;
    float py;
    float pz;
    float r;
    float h;
} YPaintSdfCylinder3D;

// Word count per SDF primitive type
static inline uint32_t ypaint_sdf_word_count(YPaintSdfType type) {
    switch (type) {
        case YPAINT_SDF_CIRCLE: return 8u;
        case YPAINT_SDF_BOX: return 10u;
        case YPAINT_SDF_SEGMENT: return 9u;
        case YPAINT_SDF_TRIANGLE: return 11u;
        case YPAINT_SDF_ELLIPSE: return 9u;
        case YPAINT_SDF_ARC: return 11u;
        case YPAINT_SDF_ROUNDED_BOX: return 13u;
        case YPAINT_SDF_RHOMBUS: return 9u;
        case YPAINT_SDF_PENTAGON: return 8u;
        case YPAINT_SDF_HEXAGON: return 8u;
        case YPAINT_SDF_STAR: return 10u;
        case YPAINT_SDF_PIE: return 10u;
        case YPAINT_SDF_RING: return 11u;
        case YPAINT_SDF_HEART: return 8u;
        case YPAINT_SDF_CROSS: return 10u;
        case YPAINT_SDF_ROUNDED_X: return 9u;
        case YPAINT_SDF_CAPSULE: return 10u;
        case YPAINT_SDF_MOON: return 10u;
        case YPAINT_SDF_EGG: return 9u;
        case YPAINT_SDF_OCTOGON: return 8u;
        case YPAINT_SDF_HEXAGRAM: return 8u;
        case YPAINT_SDF_PENTAGRAM: return 8u;
        case YPAINT_SDF_SPHERE_3D: return 9u;
        case YPAINT_SDF_BOX_3D: return 11u;
        case YPAINT_SDF_TORUS_3D: return 10u;
        case YPAINT_SDF_CYLINDER_3D: return 10u;
        default: return 0u;
    }
}

#ifdef __cplusplus
}
#endif