// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ypaint/sdf/gen-sdf-code.py

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum ypaint_sdf_type {
    YPAINT_SDF_CIRCLE = 0,
    YPAINT_SDF_BOX = 1,
    YPAINT_SDF_SEGMENT = 2,
    YPAINT_SDF_TRIANGLE = 3,
    YPAINT_SDF_ELLIPSE = 6,
    YPAINT_SDF_ARC = 7,
    YPAINT_SDF_ROUNDED_BOX = 8,
    YPAINT_SDF_RHOMBUS = 9,
    YPAINT_SDF_PENTAGON = 10,
    YPAINT_SDF_HEXAGON = 11,
    YPAINT_SDF_STAR = 12,
    YPAINT_SDF_PIE = 13,
    YPAINT_SDF_RING = 14,
    YPAINT_SDF_HEART = 15,
    YPAINT_SDF_CROSS = 16,
    YPAINT_SDF_ROUNDED_X = 17,
    YPAINT_SDF_CAPSULE = 18,
    YPAINT_SDF_MOON = 19,
    YPAINT_SDF_EGG = 20,
    YPAINT_SDF_OCTOGON = 28,
    YPAINT_SDF_HEXAGRAM = 29,
    YPAINT_SDF_PENTAGRAM = 30,
    YPAINT_SDF_SPHERE_3D = 100,
    YPAINT_SDF_BOX_3D = 101,
    YPAINT_SDF_TORUS_3D = 103,
    YPAINT_SDF_CYLINDER_3D = 105,
};

struct ypaint_sdf_circle {
    float center_x;
    float center_y;
    float radius;
};

struct ypaint_sdf_box {
    float center_x;
    float center_y;
    float half_width;
    float half_height;
    float corner_radius;
};

struct ypaint_sdf_segment {
    float start_x;
    float start_y;
    float end_x;
    float end_y;
};

struct ypaint_sdf_triangle {
    float vertex_a_x;
    float vertex_a_y;
    float vertex_b_x;
    float vertex_b_y;
    float vertex_c_x;
    float vertex_c_y;
};

struct ypaint_sdf_ellipse {
    float center_x;
    float center_y;
    float radius_x;
    float radius_y;
};

struct ypaint_sdf_arc {
    float center_x;
    float center_y;
    float aperture_x;
    float aperture_y;
    float radius;
    float thickness;
};

struct ypaint_sdf_rounded_box {
    float center_x;
    float center_y;
    float half_width;
    float half_height;
    float radius_top_right;
    float radius_bottom_right;
    float radius_top_left;
    float radius_bottom_left;
};

struct ypaint_sdf_rhombus {
    float center_x;
    float center_y;
    float half_width;
    float half_height;
};

struct ypaint_sdf_pentagon {
    float center_x;
    float center_y;
    float radius;
};

struct ypaint_sdf_hexagon {
    float center_x;
    float center_y;
    float radius;
};

struct ypaint_sdf_star {
    float center_x;
    float center_y;
    float radius;
    float num_points;
    float inner_ratio;
};

struct ypaint_sdf_pie {
    float center_x;
    float center_y;
    float aperture_x;
    float aperture_y;
    float radius;
};

struct ypaint_sdf_ring {
    float center_x;
    float center_y;
    float normal_x;
    float normal_y;
    float radius;
    float thickness;
};

struct ypaint_sdf_heart {
    float center_x;
    float center_y;
    float scale;
};

struct ypaint_sdf_cross {
    float center_x;
    float center_y;
    float half_width;
    float half_height;
    float corner_radius;
};

struct ypaint_sdf_rounded_x {
    float center_x;
    float center_y;
    float width;
    float radius;
};

struct ypaint_sdf_capsule {
    float start_x;
    float start_y;
    float end_x;
    float end_y;
    float radius;
};

struct ypaint_sdf_moon {
    float center_x;
    float center_y;
    float offset;
    float radius_outer;
    float radius_inner;
};

struct ypaint_sdf_egg {
    float center_x;
    float center_y;
    float radius_outer;
    float radius_inner;
};

struct ypaint_sdf_octogon {
    float center_x;
    float center_y;
    float radius;
};

struct ypaint_sdf_hexagram {
    float center_x;
    float center_y;
    float radius;
};

struct ypaint_sdf_pentagram {
    float center_x;
    float center_y;
    float radius;
};

struct ypaint_sdf_sphere_3d {
    float position_x;
    float position_y;
    float position_z;
    float radius;
};

struct ypaint_sdf_box_3d {
    float position_x;
    float position_y;
    float position_z;
    float half_size_x;
    float half_size_y;
    float half_size_z;
};

struct ypaint_sdf_torus_3d {
    float position_x;
    float position_y;
    float position_z;
    float major_radius;
    float minor_radius;
};

struct ypaint_sdf_cylinder_3d {
    float position_x;
    float position_y;
    float position_z;
    float radius;
    float half_height;
};

// Word count per SDF primitive type
static inline uint32_t ypaint_sdf_word_count(enum ypaint_sdf_type type) {
    switch (type) {
        case YPAINT_SDF_CIRCLE: return 8u;
        case YPAINT_SDF_BOX: return 10u;
        case YPAINT_SDF_SEGMENT: return 9u;
        case YPAINT_SDF_TRIANGLE: return 11u;
        case YPAINT_SDF_ELLIPSE: return 9u;
        case YPAINT_SDF_ARC: return 11u;
        case YPAINT_SDF_ROUNDED_BOX: return 13u;
        case YPAINT_SDF_RHOMBUS: return 9u;
        case YPAINT_SDF_PENTAGON: return 8u;
        case YPAINT_SDF_HEXAGON: return 8u;
        case YPAINT_SDF_STAR: return 10u;
        case YPAINT_SDF_PIE: return 10u;
        case YPAINT_SDF_RING: return 11u;
        case YPAINT_SDF_HEART: return 8u;
        case YPAINT_SDF_CROSS: return 10u;
        case YPAINT_SDF_ROUNDED_X: return 9u;
        case YPAINT_SDF_CAPSULE: return 10u;
        case YPAINT_SDF_MOON: return 10u;
        case YPAINT_SDF_EGG: return 9u;
        case YPAINT_SDF_OCTOGON: return 8u;
        case YPAINT_SDF_HEXAGRAM: return 8u;
        case YPAINT_SDF_PENTAGRAM: return 8u;
        case YPAINT_SDF_SPHERE_3D: return 9u;
        case YPAINT_SDF_BOX_3D: return 11u;
        case YPAINT_SDF_TORUS_3D: return 10u;
        case YPAINT_SDF_CYLINDER_3D: return 10u;
        default: return 0u;
    }
}

// Compute AABB for an SDF primitive
// data: full primitive data (type + z_order + style + geometry)
// word_count: number of 32-bit words in data
void ypaint_sdf_compute_aabb(const float *data, uint32_t word_count,
                              float *min_x, float *min_y,
                              float *max_x, float *max_y);

#ifdef __cplusplus
}
#endif