#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""Generate C and WGSL code from sdf-primitives.yaml.

Run:  uv run src/yetty/ypaint-c/gen-sdf-code.py

Reads:    src/yetty/ypaint-c/sdf-primitives.yaml
Generates:
  include/yetty/ypaint-c/ypaint-types.gen.h  - C enums + structs
  include/yetty/ypaint-c/ypaint-prim.gen.h   - C add functions
  src/yetty/ypaint-c/ypaint-sdf.gen.wgsl     - WGSL SDF functions + dispatch
"""

import re
from pathlib import Path
import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent.parent

YAML_PATH = SCRIPT_DIR / "sdf-primitives.yaml"
TYPES_OUT = PROJECT_ROOT / "include" / "yetty" / "ypaint-c" / "ypaint-types.gen.h"
PRIM_OUT = PROJECT_ROOT / "include" / "yetty" / "ypaint-c" / "ypaint-prim.gen.h"
WGSL_OUT = SCRIPT_DIR / "ypaint-sdf.gen.wgsl"

HEADER = """// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ypaint-c/gen-sdf-code.py
"""

# Buffer layout (in 32-bit words):
# [0] type (YPaintType enum value)
# [1] zOrder (YPaintAttrs)
# [2] fillColor (YPaintStyle)
# [3] strokeColor (YPaintStyle)
# [4] strokeWidth (YPaintStyle)
# [5+] geometry args

YPAINT_ATTRS_FIELDS = [
    ("zOrder", "u32"),
]

YPAINT_STYLE_FIELDS = [
    ("fillColor", "u32"),
    ("strokeColor", "u32"),
    ("strokeWidth", "f32"),
]

# Geometry starts after type + attrs + style
GEOMETRY_OFFSET = 1 + len(YPAINT_ATTRS_FIELDS) + len(YPAINT_STYLE_FIELDS)


def camel_to_snake(name: str) -> str:
    """CamelCase -> snake_case"""
    s = re.sub(r"([a-z])([A-Z])", r"\1_\2", name)
    s = re.sub(r"([a-zA-Z])(\d)", r"\1_\2", s)
    return s.lower()


def camel_to_screaming(name: str) -> str:
    """CamelCase -> SCREAMING_SNAKE"""
    return camel_to_snake(name).upper()


def c_type(yaml_type: str) -> str:
    """Convert YAML type to C type"""
    return {"f32": "float", "u32": "uint32_t", "i32": "int32_t"}[yaml_type]


def load_primitives(path: Path) -> list[dict]:
    with open(path) as f:
        return yaml.safe_load(f)


def generate_types_header(prims: list[dict], out: Path) -> None:
    """Generate ypaint-types.gen.h"""
    lines = [HEADER, "#pragma once", "", "#include <stdint.h>", "", "#ifdef __cplusplus", 'extern "C" {', "#endif", ""]

    # Enum for primitive types
    lines.append("typedef enum YPaintType {")
    for p in prims:
        lines.append(f"    YPAINT_{camel_to_screaming(p['name'])} = {p['type']},")
    lines.append("} YPaintType;")
    lines.append("")

    # YPaintAttrs struct
    lines.append("typedef struct YPaintAttrs {")
    for fname, ftype in YPAINT_ATTRS_FIELDS:
        lines.append(f"    {c_type(ftype)} {fname};")
    lines.append("} YPaintAttrs;")
    lines.append("")

    # YPaintStyle struct
    lines.append("typedef struct YPaintStyle {")
    for fname, ftype in YPAINT_STYLE_FIELDS:
        lines.append(f"    {c_type(ftype)} {fname};")
    lines.append("} YPaintStyle;")
    lines.append("")

    # Geometry structs (only SDF-specific args)
    for p in prims:
        name = p["name"]
        args = p.get("args", [])

        lines.append(f"typedef struct YPaint{name} {{")
        for arg in args:
            lines.append(f"    {c_type(arg['type'])} {arg['name']};")
        lines.append(f"}} YPaint{name};")
        lines.append("")

    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def generate_prim_header(prims: list[dict], out: Path) -> None:
    """Generate ypaint-prim.gen.h"""
    lines = [HEADER, "#pragma once", "", "#include \"ypaint-types.gen.h\"", "#include \"ypaint-buffer.h\"", ""]
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")

    for p in prims:
        name = p["name"]
        snake = camel_to_snake(name)
        lines.append(f"YPaintIdResult ypaint_buffer_add_{snake}(YPaintBufferHandle buf, YPaintAttrs attrs, YPaintStyle style, const YPaint{name}* geom);")
        lines.append("")

    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def generate_wgsl(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf.gen.wgsl"""
    lines = [HEADER, ""]

    # Generate individual SDF functions
    for p in prims:
        name = p["name"]
        args = p.get("args", [])
        shader = p.get("shader", {}).get("code", "")
        if not shader.strip():
            continue

        # Function signature with explicit params
        params = ["p: vec2<f32>"] if p["category"] == "sdf2d" else ["p: vec3<f32>"]
        for arg in args:
            wgsl_type = "f32" if arg["type"] == "f32" else "u32"
            params.append(f"{arg['name']}: {wgsl_type}")

        lines.append(f"fn sdf{name}({', '.join(params)}) -> f32 {{")
        for line in shader.strip().split("\n"):
            # Remove {field} substitution - use params directly
            cleaned = re.sub(r"\{(\w+)\}", r"\1", line)
            lines.append(f"    {cleaned}")
        lines.append("}")
        lines.append("")

    # Generate dispatcher for 2D
    sdf2d = [p for p in prims if p["category"] == "sdf2d"]
    if sdf2d:
        lines.append("fn evaluateSDF2D(primOffset: u32, p: vec2<f32>) -> f32 {")
        lines.append("    let primType = bitcast<u32>(buf[primOffset]);")
        lines.append("    switch (primType) {")
        for p in sdf2d:
            name = p["name"]
            args = p.get("args", [])
            arg_accesses = [f"buf[primOffset + {GEOMETRY_OFFSET + i}u]" for i in range(len(args))]
            lines.append(f"        case {p['type']}u: {{ return sdf{name}(p, {', '.join(arg_accesses)}); }}")
        lines.append("        default: { return 1e10; }")
        lines.append("    }")
        lines.append("}")
        lines.append("")

    # Generate dispatcher for 3D
    sdf3d = [p for p in prims if p["category"] == "sdf3d"]
    if sdf3d:
        lines.append("fn evaluateSDF3D(primOffset: u32, p: vec3<f32>) -> f32 {")
        lines.append("    let primType = bitcast<u32>(buf[primOffset]);")
        lines.append("    switch (primType) {")
        for p in sdf3d:
            name = p["name"]
            args = p.get("args", [])
            arg_accesses = [f"buf[primOffset + {GEOMETRY_OFFSET + i}u]" for i in range(len(args))]
            lines.append(f"        case {p['type']}u: {{ return sdf{name}(p, {', '.join(arg_accesses)}); }}")
        lines.append("        default: { return 1e10; }")
        lines.append("    }")
        lines.append("}")
        lines.append("")

    # Style extraction (common for all)
    lines.append("fn getPrimStyle(primOffset: u32) -> vec3<u32> {")
    lines.append("    return vec3<u32>(")
    lines.append("        bitcast<u32>(buf[primOffset + 2u]),  // fillColor")
    lines.append("        bitcast<u32>(buf[primOffset + 3u]),  // strokeColor")
    lines.append("        bitcast<u32>(buf[primOffset + 4u])   // strokeWidth as bits")
    lines.append("    );")
    lines.append("}")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def main():
    prims = load_primitives(YAML_PATH)
    generate_types_header(prims, TYPES_OUT)
    generate_prim_header(prims, PRIM_OUT)
    generate_wgsl(prims, WGSL_OUT)
    print("Done.")


if __name__ == "__main__":
    main()
