#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""Generate C and WGSL code from sdf-primitives.yaml.

Run:  uv run src/yetty/ypaint/sdf/gen-sdf-code.py

Reads:    src/yetty/ypaint/sdf/sdf-primitives.yaml
Generates:
  include/yetty/ypaint/sdf/ypaint-sdf-types.gen.h  - C enums + geometry structs
  include/yetty/ypaint/sdf/ypaint-sdf-prim.gen.h   - C add function declarations
  src/yetty/ypaint/sdf/ypaint-sdf-prim.gen.c       - C add function implementations
  src/yetty/ypaint/sdf/ypaint-sdf-aabb.gen.c       - C AABB computation
  src/yetty/ypaint/sdf/ypaint-sdf.gen.wgsl         - WGSL SDF functions + dispatch
"""

import re
from pathlib import Path
import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent.parent.parent

YAML_PATH = SCRIPT_DIR / "sdf-primitives.yaml"
SDF_TYPES_OUT = PROJECT_ROOT / "include" / "yetty" / "ypaint" / "sdf" / "ypaint-sdf-types.gen.h"
SDF_PRIM_H_OUT = PROJECT_ROOT / "include" / "yetty" / "ypaint" / "sdf" / "ypaint-sdf-prim.gen.h"
SDF_PRIM_C_OUT = SCRIPT_DIR / "ypaint-sdf-prim.gen.c"
SDF_AABB_OUT = SCRIPT_DIR / "ypaint-sdf-aabb.gen.c"
SDF_WGSL_OUT = SCRIPT_DIR / "ypaint-sdf.gen.wgsl"

HEADER_C = """// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ypaint/sdf/gen-sdf-code.py
"""

HEADER_WGSL = """// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ypaint/sdf/gen-sdf-code.py
"""

# Buffer layout (in 32-bit words):
# [0] type (YPaintSdfType enum value)
# [1] zOrder
# [2] fillColor
# [3] strokeColor
# [4] strokeWidth
# [5+] geometry args

GEOMETRY_OFFSET = 5


def camel_to_snake(name: str) -> str:
    """CamelCase -> snake_case"""
    s = re.sub(r"([a-z])([A-Z])", r"\1_\2", name)
    s = re.sub(r"([a-zA-Z])(\d)", r"\1_\2", s)
    return s.lower()


def camel_to_screaming(name: str) -> str:
    """CamelCase -> SCREAMING_SNAKE"""
    return camel_to_snake(name).upper()


def c_type(yaml_type: str) -> str:
    """Convert YAML type to C type"""
    return {"f32": "float", "u32": "uint32_t", "i32": "int32_t"}[yaml_type]


def load_primitives(path: Path) -> list[dict]:
    with open(path) as f:
        return yaml.safe_load(f)


def generate_sdf_types(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf-types.gen.h - enums and geometry structs for SDF primitives"""
    lines = [HEADER_C, "#pragma once", "", "#include <stdint.h>", "", "#ifdef __cplusplus", 'extern "C" {', "#endif", ""]

    # Enum for SDF primitive types
    lines.append("typedef enum YPaintSdfType {")
    for p in prims:
        lines.append(f"    YPAINT_SDF_{camel_to_screaming(p['name'])} = {p['type']},")
    lines.append("} YPaintSdfType;")
    lines.append("")

    # Geometry structs for each SDF primitive
    for p in prims:
        name = p["name"]
        args = p.get("args", [])

        lines.append(f"typedef struct YPaintSdf{name} {{")
        for arg in args:
            lines.append(f"    {c_type(arg['type'])} {arg['name']};")
        lines.append(f"}} YPaintSdf{name};")
        lines.append("")

    # Word count for each SDF primitive type
    lines.append("// Word count per SDF primitive type")
    lines.append("static inline uint32_t ypaint_sdf_word_count(YPaintSdfType type) {")
    lines.append("    switch (type) {")
    for p in prims:
        name = p["name"]
        args = p.get("args", [])
        word_count = GEOMETRY_OFFSET + len(args)
        lines.append(f"        case YPAINT_SDF_{camel_to_screaming(name)}: return {word_count}u;")
    lines.append("        default: return 0u;")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def generate_sdf_prim_header(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf-prim.gen.h - add function declarations for SDF primitives"""
    lines = [HEADER_C, "#pragma once", ""]
    lines.append('#include "ypaint-sdf-types.gen.h"')
    lines.append('#include <yetty/ypaint/core/ypaint-buffer.h>')
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")

    for p in prims:
        name = p["name"]
        snake = camel_to_snake(name)
        lines.append(f"YPaintIdResult ypaint_sdf_add_{snake}(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdf{name}* geom);")
        lines.append("")

    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def generate_sdf_prim_impl(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf-prim.gen.c - add function implementations for SDF primitives"""
    lines = [HEADER_C, ""]
    lines.append('#include <yetty/ypaint/sdf/ypaint-sdf-prim.gen.h>')
    lines.append('#include <string.h>')
    lines.append("")

    for p in prims:
        name = p["name"]
        snake = camel_to_snake(name)
        args = p.get("args", [])
        word_count = GEOMETRY_OFFSET + len(args)

        lines.append(f"YPaintIdResult ypaint_sdf_add_{snake}(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdf{name}* geom) {{")
        lines.append(f"    float data[{word_count}];")
        lines.append("    uint32_t tmp;")
        lines.append("")
        # Type
        lines.append(f"    tmp = YPAINT_SDF_{camel_to_screaming(name)};")
        lines.append("    memcpy(&data[0], &tmp, sizeof(tmp));")
        # zOrder
        lines.append("    tmp = zOrder;")
        lines.append("    memcpy(&data[1], &tmp, sizeof(tmp));")
        # fillColor
        lines.append("    tmp = fillColor;")
        lines.append("    memcpy(&data[2], &tmp, sizeof(tmp));")
        # strokeColor
        lines.append("    tmp = strokeColor;")
        lines.append("    memcpy(&data[3], &tmp, sizeof(tmp));")
        # strokeWidth
        lines.append("    data[4] = strokeWidth;")
        # Geometry args
        for i, arg in enumerate(args):
            offset = GEOMETRY_OFFSET + i
            if arg["type"] == "f32":
                lines.append(f"    data[{offset}] = geom->{arg['name']};")
            else:
                lines.append(f"    tmp = geom->{arg['name']};")
                lines.append(f"    memcpy(&data[{offset}], &tmp, sizeof(tmp));")
        lines.append("")
        lines.append(f"    return ypaint_buffer_add_prim(buf, data, {word_count});")
        lines.append("}")
        lines.append("")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def generate_sdf_aabb(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf-aabb.gen.c - AABB computation for SDF primitives"""
    lines = [HEADER_C, ""]
    lines.append('#include <yetty/ypaint/sdf/ypaint-sdf-types.gen.h>')
    lines.append('#include <math.h>')
    lines.append('#include <string.h>')
    lines.append("")
    lines.append("// Compute AABB for an SDF primitive")
    lines.append("// data: full primitive data (type + zOrder + style + geometry)")
    lines.append("// p: pointer to geometry args (data + 5)")
    lines.append("// expand: strokeWidth * 0.5f")
    lines.append("")
    lines.append("void ypaint_sdf_compute_aabb(const float* data, uint32_t wordCount,")
    lines.append("                              float* minX, float* minY, float* maxX, float* maxY) {")
    lines.append("    uint32_t type;")
    lines.append("    memcpy(&type, &data[0], sizeof(type));")
    lines.append(f"    const float* p = data + {GEOMETRY_OFFSET};  // geometry args")
    lines.append("    float strokeWidth = data[4];")
    lines.append("    float expand = strokeWidth * 0.5f;")
    lines.append("")
    lines.append("    switch ((YPaintSdfType)type) {")

    for p in prims:
        name = p["name"]
        aabb_code = p.get("aabb", {}).get("code", "").strip()
        if not aabb_code:
            aabb_code = "*minX = -1e10f; *minY = -1e10f; *maxX = 1e10f; *maxY = 1e10f;"

        lines.append(f"    case YPAINT_SDF_{camel_to_screaming(name)}: {{")
        for line in aabb_code.split("\n"):
            lines.append(f"        {line}")
        lines.append("        break;")
        lines.append("    }")

    lines.append("    default:")
    lines.append("        *minX = -1e10f; *minY = -1e10f; *maxX = 1e10f; *maxY = 1e10f;")
    lines.append("        break;")
    lines.append("    }")
    lines.append("}")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def generate_sdf_wgsl(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf.gen.wgsl - WGSL SDF functions and dispatcher"""
    lines = [HEADER_WGSL, ""]

    # Generate individual SDF functions
    for p in prims:
        name = p["name"]
        args = p.get("args", [])
        shader = p.get("shader", {}).get("code", "")
        if not shader.strip():
            continue

        # Function signature with explicit params
        params = ["p: vec2<f32>"] if p["category"] == "sdf2d" else ["p: vec3<f32>"]
        for arg in args:
            wgsl_type = "f32" if arg["type"] == "f32" else "u32"
            params.append(f"{arg['name']}: {wgsl_type}")

        lines.append(f"fn sdf{name}({', '.join(params)}) -> f32 {{")
        for line in shader.strip().split("\n"):
            lines.append(f"    {line}")
        lines.append("}")
        lines.append("")

    # Generate dispatcher for 2D
    sdf2d = [p for p in prims if p["category"] == "sdf2d"]
    if sdf2d:
        lines.append("fn evaluateSDF2D(primOffset: u32, p: vec2<f32>) -> f32 {")
        lines.append("    let primType = bitcast<u32>(buf[primOffset]);")
        lines.append("    switch (primType) {")
        for p in sdf2d:
            name = p["name"]
            args = p.get("args", [])
            arg_accesses = [f"buf[primOffset + {GEOMETRY_OFFSET + i}u]" for i in range(len(args))]
            lines.append(f"        case {p['type']}u: {{ return sdf{name}(p, {', '.join(arg_accesses)}); }}")
        lines.append("        default: { return 1e10; }")
        lines.append("    }")
        lines.append("}")
        lines.append("")

    # Generate dispatcher for 3D
    sdf3d = [p for p in prims if p["category"] == "sdf3d"]
    if sdf3d:
        lines.append("fn evaluateSDF3D(primOffset: u32, p: vec3<f32>) -> f32 {")
        lines.append("    let primType = bitcast<u32>(buf[primOffset]);")
        lines.append("    switch (primType) {")
        for p in sdf3d:
            name = p["name"]
            args = p.get("args", [])
            arg_accesses = [f"buf[primOffset + {GEOMETRY_OFFSET + i}u]" for i in range(len(args))]
            lines.append(f"        case {p['type']}u: {{ return sdf{name}(p, {', '.join(arg_accesses)}); }}")
        lines.append("        default: { return 1e10; }")
        lines.append("    }")
        lines.append("}")
        lines.append("")

    # Style extraction
    lines.append("fn getSdfPrimStyle(primOffset: u32) -> vec3<u32> {")
    lines.append("    return vec3<u32>(")
    lines.append("        bitcast<u32>(buf[primOffset + 2u]),  // fillColor")
    lines.append("        bitcast<u32>(buf[primOffset + 3u]),  // strokeColor")
    lines.append("        bitcast<u32>(buf[primOffset + 4u])   // strokeWidth as bits")
    lines.append("    );")
    lines.append("}")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def main():
    prims = load_primitives(YAML_PATH)
    generate_sdf_types(prims, SDF_TYPES_OUT)
    generate_sdf_prim_header(prims, SDF_PRIM_H_OUT)
    generate_sdf_prim_impl(prims, SDF_PRIM_C_OUT)
    generate_sdf_aabb(prims, SDF_AABB_OUT)
    generate_sdf_wgsl(prims, SDF_WGSL_OUT)
    print("Done.")


if __name__ == "__main__":
    main()
