#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""Generate C and WGSL code from sdf-primitives.yaml.

Run:  uv run src/yetty/ypaint/sdf/gen-sdf-code.py

Reads:    src/yetty/ypaint/sdf/sdf-primitives.yaml
Generates:
  include/yetty/ypaint/sdf/ypaint-sdf-types.gen.h  - C enums + geometry structs
  include/yetty/ypaint/sdf/ypaint-sdf-prim.gen.h   - C add function declarations
  src/yetty/ypaint/sdf/ypaint-sdf-prim.gen.c       - C add function implementations
  src/yetty/ypaint/sdf/ypaint-sdf-aabb.gen.c       - C AABB computation
  src/yetty/ypaint/sdf/ypaint-sdf.gen.wgsl         - WGSL SDF functions + dispatch
"""

import re
from pathlib import Path
import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent.parent.parent

YAML_PATH = SCRIPT_DIR / "sdf-primitives.yaml"
SDF_TYPES_OUT = PROJECT_ROOT / "include" / "yetty" / "ypaint" / "sdf" / "ypaint-sdf-types.gen.h"
SDF_PRIM_H_OUT = PROJECT_ROOT / "include" / "yetty" / "ypaint" / "sdf" / "ypaint-sdf-prim.gen.h"
SDF_PRIM_C_OUT = SCRIPT_DIR / "ypaint-sdf-prim.gen.c"
SDF_AABB_OUT = SCRIPT_DIR / "ypaint-sdf-aabb.gen.c"
SDF_WGSL_OUT = SCRIPT_DIR / "ypaint-sdf.gen.wgsl"
SDF_YAML_H_OUT = PROJECT_ROOT / "include" / "yetty" / "ypaint" / "sdf" / "ypaint-sdf-yaml.gen.h"
SDF_YAML_C_OUT = SCRIPT_DIR / "ypaint-sdf-yaml.gen.c"

HEADER_C = """// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ypaint/sdf/gen-sdf-code.py
"""

HEADER_WGSL = """// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ypaint/sdf/gen-sdf-code.py
"""

# Buffer layout (in 32-bit words):
# [0] type (YPaintSdfType enum value)
# [1] zOrder
# [2] fillColor
# [3] strokeColor
# [4] strokeWidth
# [5+] geometry args

GEOMETRY_OFFSET = 5


def camel_to_snake(name: str) -> str:
    """CamelCase -> snake_case"""
    s = re.sub(r"([a-z])([A-Z])", r"\1_\2", name)
    s = re.sub(r"([a-zA-Z])(\d)", r"\1_\2", s)
    return s.lower()


def camel_to_screaming(name: str) -> str:
    """CamelCase -> SCREAMING_SNAKE"""
    return camel_to_snake(name).upper()


def c_type(yaml_type: str) -> str:
    """Convert YAML type to C type"""
    return {"f32": "float", "u32": "uint32_t", "i32": "int32_t"}[yaml_type]


def load_primitives(path: Path) -> list[dict]:
    with open(path) as f:
        return yaml.safe_load(f)


def generate_sdf_types(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf-types.gen.h - enums and geometry structs for SDF primitives"""
    lines = [HEADER_C, "#pragma once", "", "#include <stdint.h>", "", "#ifdef __cplusplus", 'extern "C" {', "#endif", ""]

    # Enum for SDF primitive types
    lines.append("typedef enum YPaintSdfType {")
    for p in prims:
        lines.append(f"    YPAINT_SDF_{camel_to_screaming(p['name'])} = {p['type']},")
    lines.append("} YPaintSdfType;")
    lines.append("")

    # Geometry structs for each SDF primitive
    for p in prims:
        name = p["name"]
        args = p.get("args", [])

        lines.append(f"typedef struct YPaintSdf{name} {{")
        for arg in args:
            lines.append(f"    {c_type(arg['type'])} {arg['name']};")
        lines.append(f"}} YPaintSdf{name};")
        lines.append("")

    # Word count for each SDF primitive type
    lines.append("// Word count per SDF primitive type")
    lines.append("static inline uint32_t ypaint_sdf_word_count(YPaintSdfType type) {")
    lines.append("    switch (type) {")
    for p in prims:
        name = p["name"]
        args = p.get("args", [])
        word_count = GEOMETRY_OFFSET + len(args)
        lines.append(f"        case YPAINT_SDF_{camel_to_screaming(name)}: return {word_count}u;")
    lines.append("        default: return 0u;")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def generate_sdf_prim_header(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf-prim.gen.h - add function declarations for SDF primitives"""
    lines = [HEADER_C, "#pragma once", ""]
    lines.append('#include "ypaint-sdf-types.gen.h"')
    lines.append('#include <yetty/ypaint/core/ypaint-buffer.h>')
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")

    for p in prims:
        name = p["name"]
        snake = camel_to_snake(name)
        lines.append(f"YPaintIdResult ypaint_sdf_add_{snake}(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdf{name}* geom);")
        lines.append("")

    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def generate_sdf_prim_impl(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf-prim.gen.c - add function implementations for SDF primitives"""
    lines = [HEADER_C, ""]
    lines.append('#include <yetty/ypaint/sdf/ypaint-sdf-prim.gen.h>')
    lines.append('#include <string.h>')
    lines.append("")

    for p in prims:
        name = p["name"]
        snake = camel_to_snake(name)
        args = p.get("args", [])
        word_count = GEOMETRY_OFFSET + len(args)

        lines.append(f"YPaintIdResult ypaint_sdf_add_{snake}(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdf{name}* geom) {{")
        lines.append(f"    float data[{word_count}];")
        lines.append("    uint32_t tmp;")
        lines.append("")
        # Type
        lines.append(f"    tmp = YPAINT_SDF_{camel_to_screaming(name)};")
        lines.append("    memcpy(&data[0], &tmp, sizeof(tmp));")
        # zOrder
        lines.append("    tmp = zOrder;")
        lines.append("    memcpy(&data[1], &tmp, sizeof(tmp));")
        # fillColor
        lines.append("    tmp = fillColor;")
        lines.append("    memcpy(&data[2], &tmp, sizeof(tmp));")
        # strokeColor
        lines.append("    tmp = strokeColor;")
        lines.append("    memcpy(&data[3], &tmp, sizeof(tmp));")
        # strokeWidth
        lines.append("    data[4] = strokeWidth;")
        # Geometry args
        for i, arg in enumerate(args):
            offset = GEOMETRY_OFFSET + i
            if arg["type"] == "f32":
                lines.append(f"    data[{offset}] = geom->{arg['name']};")
            else:
                lines.append(f"    tmp = geom->{arg['name']};")
                lines.append(f"    memcpy(&data[{offset}], &tmp, sizeof(tmp));")
        lines.append("")
        lines.append(f"    return ypaint_buffer_add_prim(buf, data, {word_count});")
        lines.append("}")
        lines.append("")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def generate_sdf_aabb(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf-aabb.gen.c - AABB computation for SDF primitives"""
    lines = [HEADER_C, ""]
    lines.append('#include <yetty/ypaint/sdf/ypaint-sdf-types.gen.h>')
    lines.append('#include <math.h>')
    lines.append('#include <string.h>')
    lines.append("")
    lines.append("// Compute AABB for an SDF primitive")
    lines.append("// data: full primitive data (type + zOrder + style + geometry)")
    lines.append("// p: pointer to geometry args (data + 5)")
    lines.append("// expand: strokeWidth * 0.5f")
    lines.append("")
    lines.append("void ypaint_sdf_compute_aabb(const float* data, uint32_t wordCount,")
    lines.append("                              float* minX, float* minY, float* maxX, float* maxY) {")
    lines.append("    uint32_t type;")
    lines.append("    memcpy(&type, &data[0], sizeof(type));")
    lines.append(f"    const float* p = data + {GEOMETRY_OFFSET};  // geometry args")
    lines.append("    float strokeWidth = data[4];")
    lines.append("    float expand = strokeWidth * 0.5f;")
    lines.append("")
    lines.append("    switch ((YPaintSdfType)type) {")

    for p in prims:
        name = p["name"]
        aabb_code = p.get("aabb", {}).get("code", "").strip()
        if not aabb_code:
            aabb_code = "*minX = -1e10f; *minY = -1e10f; *maxX = 1e10f; *maxY = 1e10f;"

        lines.append(f"    case YPAINT_SDF_{camel_to_screaming(name)}: {{")
        for line in aabb_code.split("\n"):
            lines.append(f"        {line}")
        lines.append("        break;")
        lines.append("    }")

    lines.append("    default:")
    lines.append("        *minX = -1e10f; *minY = -1e10f; *maxX = 1e10f; *maxY = 1e10f;")
    lines.append("        break;")
    lines.append("    }")
    lines.append("}")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def generate_sdf_wgsl(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf.gen.wgsl - WGSL SDF functions and dispatcher"""
    lines = [HEADER_WGSL, ""]

    # Generate individual SDF functions
    for p in prims:
        name = p["name"]
        args = p.get("args", [])
        shader = p.get("shader", {}).get("code", "")
        if not shader.strip():
            continue

        # Function signature with explicit params
        params = ["p: vec2<f32>"] if p["category"] == "sdf2d" else ["p: vec3<f32>"]
        for arg in args:
            wgsl_type = "f32" if arg["type"] == "f32" else "u32"
            params.append(f"{arg['name']}: {wgsl_type}")

        lines.append(f"fn sdf{name}({', '.join(params)}) -> f32 {{")
        for line in shader.strip().split("\n"):
            lines.append(f"    {line}")
        lines.append("}")
        lines.append("")

    # Generate dispatcher for 2D
    sdf2d = [p for p in prims if p["category"] == "sdf2d"]
    if sdf2d:
        lines.append("fn evaluateSDF2D(primOffset: u32, p: vec2<f32>) -> f32 {")
        lines.append("    let primType = bitcast<u32>(buf[primOffset]);")
        lines.append("    switch (primType) {")
        for p in sdf2d:
            name = p["name"]
            args = p.get("args", [])
            arg_accesses = [f"buf[primOffset + {GEOMETRY_OFFSET + i}u]" for i in range(len(args))]
            lines.append(f"        case {p['type']}u: {{ return sdf{name}(p, {', '.join(arg_accesses)}); }}")
        lines.append("        default: { return 1e10; }")
        lines.append("    }")
        lines.append("}")
        lines.append("")

    # Generate dispatcher for 3D
    sdf3d = [p for p in prims if p["category"] == "sdf3d"]
    if sdf3d:
        lines.append("fn evaluateSDF3D(primOffset: u32, p: vec3<f32>) -> f32 {")
        lines.append("    let primType = bitcast<u32>(buf[primOffset]);")
        lines.append("    switch (primType) {")
        for p in sdf3d:
            name = p["name"]
            args = p.get("args", [])
            arg_accesses = [f"buf[primOffset + {GEOMETRY_OFFSET + i}u]" for i in range(len(args))]
            lines.append(f"        case {p['type']}u: {{ return sdf{name}(p, {', '.join(arg_accesses)}); }}")
        lines.append("        default: { return 1e10; }")
        lines.append("    }")
        lines.append("}")
        lines.append("")

    # Style extraction
    lines.append("fn getSdfPrimStyle(primOffset: u32) -> vec3<u32> {")
    lines.append("    return vec3<u32>(")
    lines.append("        bitcast<u32>(buf[primOffset + 2u]),  // fillColor")
    lines.append("        bitcast<u32>(buf[primOffset + 3u]),  // strokeColor")
    lines.append("        bitcast<u32>(buf[primOffset + 4u])   // strokeWidth as bits")
    lines.append("    );")
    lines.append("}")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def infer_yaml_props(args: list[dict]) -> list[tuple[str, str, list[str], str]]:
    """Infer YAML property mappings from arg names.
    Returns list of (yaml_key, type, [arg_names], transform)
    type: vec2, scalar, size (divides by 2)
    """
    arg_names = [a["name"] for a in args]
    props = []

    # Position patterns
    if "cx" in arg_names and "cy" in arg_names:
        props.append(("position", "vec2", ["cx", "cy"], ""))
    if "ax" in arg_names and "ay" in arg_names:
        if "bx" in arg_names:  # Triangle or multi-point
            props.append(("p0", "vec2", ["ax", "ay"], ""))
            props.append(("p1", "vec2", ["bx", "by"], ""))
            if "cx" in arg_names:
                props.append(("p2", "vec2", ["cx", "cy"], ""))
        else:  # Capsule-like (ax,ay,bx,by)
            props.append(("from", "vec2", ["ax", "ay"], ""))
            props.append(("to", "vec2", ["bx", "by"], ""))
    if "x0" in arg_names and "y0" in arg_names:
        props.append(("from", "vec2", ["x0", "y0"], ""))
        props.append(("to", "vec2", ["x1", "y1"], ""))

    # Size patterns
    if "hw" in arg_names and "hh" in arg_names:
        props.append(("size", "size", ["hw", "hh"], "/ 2.0f"))

    # Radius patterns
    if "r" in arg_names:
        props.append(("radius", "scalar", ["r"], ""))
    if "rx" in arg_names and "ry" in arg_names:
        props.append(("radii", "vec2", ["rx", "ry"], ""))
    if "ra" in arg_names and "rb" in arg_names:
        props.append(("radius_outer", "scalar", ["ra"], ""))
        props.append(("radius_inner", "scalar", ["rb"], ""))

    # Other scalars
    if "round" in arg_names:
        props.append(("round", "scalar", ["round"], ""))
    if "scale" in arg_names:
        props.append(("scale", "scalar", ["scale"], ""))
    if "n" in arg_names:
        props.append(("points", "scalar", ["n"], ""))
    if "m" in arg_names:
        props.append(("inner", "scalar", ["m"], ""))
    if "th" in arg_names:
        props.append(("thickness", "scalar", ["th"], ""))
    if "d" in arg_names:
        props.append(("distance", "scalar", ["d"], ""))

    # Size for cross/rhombus (bx, by without position)
    if "bx" in arg_names and "by" in arg_names and "cx" not in arg_names and "ax" not in arg_names:
        props.append(("size", "vec2", ["bx", "by"], ""))

    # Width for rounded_x
    if "w" in arg_names:
        props.append(("width", "scalar", ["w"], ""))

    return props


def generate_sdf_yaml_header(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf-yaml.gen.h - YAML parsing declarations"""
    lines = [HEADER_C, "#pragma once", ""]
    lines.append('#include "ypaint-sdf-types.gen.h"')
    lines.append('#include <yetty/ypaint/core/ypaint-canvas.h>')
    lines.append('#include <stddef.h>')
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")
    lines.append("/**")
    lines.append(" * Parse YAML body and add primitives to canvas.")
    lines.append(" * @param canvas Target canvas")
    lines.append(" * @param yaml YAML string (null-terminated)")
    lines.append(" * @param len Length of YAML string")
    lines.append(" * @return 0 on success, -1 on error")
    lines.append(" */")
    lines.append("int ypaint_sdf_yaml_parse(YPaintCanvasHandle canvas, const char *yaml, size_t len);")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def generate_sdf_yaml_impl(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf-yaml.gen.c - YAML parsing implementation"""
    # Only generate for 2D primitives
    prims_2d = [p for p in prims if p["category"] == "sdf2d"]

    lines = [HEADER_C, ""]
    lines.append('#include <yetty/ypaint/sdf/ypaint-sdf-yaml.gen.h>')
    lines.append('#include <yetty/ypaint/sdf/ypaint-sdf-types.gen.h>')
    lines.append('#include <yetty/ytrace.h>')
    lines.append('#include <yaml.h>')
    lines.append('#include <stdlib.h>')
    lines.append('#include <string.h>')
    lines.append('#include <math.h>')
    lines.append("")

    # External AABB function
    lines.append("/* External AABB function */")
    lines.append("extern void ypaint_sdf_compute_aabb(const float *data, uint32_t wordCount,")
    lines.append("                                     float *minX, float *minY, float *maxX, float *maxY);")
    lines.append("")

    # Color parsing helper
    lines.append("/*=============================================================================")
    lines.append(" * Helpers")
    lines.append(" *===========================================================================*/")
    lines.append("")
    lines.append("static uint32_t parse_color(const char *str) {")
    lines.append("    if (!str || !*str) return 0;")
    lines.append("    if (str[0] == '#') str++;")
    lines.append("    size_t len = strlen(str);")
    lines.append("    char buf[9] = {0};")
    lines.append("    if (len == 3) {")
    lines.append('        buf[0] = buf[1] = str[0]; buf[2] = buf[3] = str[1]; buf[4] = buf[5] = str[2]; buf[6] = buf[7] = \'F\';')
    lines.append("    } else if (len == 6) {")
    lines.append('        memcpy(buf, str, 6); buf[6] = buf[7] = \'F\';')
    lines.append("    } else if (len == 8) {")
    lines.append("        memcpy(buf, str, 8);")
    lines.append("    } else return 0;")
    lines.append("    char *end;")
    lines.append("    unsigned long v = strtoul(buf, &end, 16);")
    lines.append("    if (*end) return 0;")
    lines.append("    uint32_t r = (v >> 24) & 0xFF, g = (v >> 16) & 0xFF, b = (v >> 8) & 0xFF, a = v & 0xFF;")
    lines.append("    return (a << 24) | (b << 16) | (g << 8) | r;")
    lines.append("}")
    lines.append("")

    # Parser context structure
    lines.append("/*=============================================================================")
    lines.append(" * Parser context")
    lines.append(" *===========================================================================*/")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    YPaintCanvasHandle canvas;")
    lines.append("    uint32_t z_order;")
    lines.append("    /* Current primitive state */")
    lines.append("    char prim_type[32];")
    lines.append("    char prop_key[32];")
    lines.append("    uint32_t fill_color;")
    lines.append("    uint32_t stroke_color;")
    lines.append("    float stroke_width;")

    # Add geometry fields for all args across all primitives
    all_args = set()
    for p in prims_2d:
        for arg in p.get("args", []):
            all_args.add(arg["name"])
    for arg in sorted(all_args):
        lines.append(f"    float {arg};")

    lines.append("    /* Array parsing state */")
    lines.append("    int in_array;")
    lines.append("    int array_idx;")
    lines.append("    float array_vals[8];")
    lines.append("} ParseCtx;")
    lines.append("")

    # Reset function
    lines.append("static void reset_prim(ParseCtx *ctx) {")
    lines.append('    ctx->prim_type[0] = 0;')
    lines.append('    ctx->prop_key[0] = 0;')
    lines.append("    ctx->fill_color = 0;")
    lines.append("    ctx->stroke_color = 0;")
    lines.append("    ctx->stroke_width = 0;")
    for arg in sorted(all_args):
        lines.append(f"    ctx->{arg} = 0;")
    lines.append("    ctx->in_array = 0;")
    lines.append("    ctx->array_idx = 0;")
    lines.append("}")
    lines.append("")

    # Store array values based on property key
    lines.append("static void store_array(ParseCtx *ctx) {")
    lines.append('    const char *k = ctx->prop_key;')
    lines.append('    ydebug("store_array: key=\'%s\' idx=%d vals=[%f,%f]", k, ctx->array_idx, ctx->array_vals[0], ctx->array_vals[1]);')
    lines.append('    if (strcmp(k, "position") == 0 && ctx->array_idx >= 2) {')
    lines.append("        ctx->cx = ctx->array_vals[0]; ctx->cy = ctx->array_vals[1];")
    lines.append('        ydebug("store_array: set cx=%f cy=%f", ctx->cx, ctx->cy);')
    lines.append("    }")
    lines.append('    else if (strcmp(k, "size") == 0 && ctx->array_idx >= 2) {')
    lines.append("        ctx->hw = ctx->array_vals[0] / 2.0f; ctx->hh = ctx->array_vals[1] / 2.0f;")
    lines.append("        ctx->bx = ctx->array_vals[0]; ctx->by = ctx->array_vals[1];")  # for cross/rhombus
    lines.append("    }")
    lines.append('    else if (strcmp(k, "from") == 0 && ctx->array_idx >= 2) {')
    lines.append("        ctx->x0 = ctx->array_vals[0]; ctx->y0 = ctx->array_vals[1];")
    lines.append("        ctx->ax = ctx->array_vals[0]; ctx->ay = ctx->array_vals[1];")
    lines.append("    }")
    lines.append('    else if (strcmp(k, "to") == 0 && ctx->array_idx >= 2) {')
    lines.append("        ctx->x1 = ctx->array_vals[0]; ctx->y1 = ctx->array_vals[1];")
    lines.append("        ctx->bx = ctx->array_vals[0]; ctx->by = ctx->array_vals[1];")
    lines.append("    }")
    lines.append('    else if (strcmp(k, "p0") == 0 && ctx->array_idx >= 2) {')
    lines.append("        ctx->ax = ctx->array_vals[0]; ctx->ay = ctx->array_vals[1];")
    lines.append("    }")
    lines.append('    else if (strcmp(k, "p1") == 0 && ctx->array_idx >= 2) {')
    lines.append("        ctx->bx = ctx->array_vals[0]; ctx->by = ctx->array_vals[1];")
    lines.append("    }")
    lines.append('    else if (strcmp(k, "p2") == 0 && ctx->array_idx >= 2) {')
    lines.append("        ctx->cx = ctx->array_vals[0]; ctx->cy = ctx->array_vals[1];")
    lines.append("    }")
    lines.append('    else if (strcmp(k, "radii") == 0 && ctx->array_idx >= 2) {')
    lines.append("        ctx->rx = ctx->array_vals[0]; ctx->ry = ctx->array_vals[1];")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # Add primitive function
    lines.append("static void add_prim(ParseCtx *ctx) {")
    lines.append("    float data[16];")
    lines.append("    uint32_t wc = 0, tmp;")
    lines.append("    float minX, minY, maxX, maxY;")
    lines.append("")

    lines.append('    ydebug("add_prim: type=\'%s\' cx=%f cy=%f r=%f fill=0x%08x", ctx->prim_type, ctx->cx, ctx->cy, ctx->r, ctx->fill_color);')
    lines.append("")

    for i, p in enumerate(prims_2d):
        name = p["name"]
        snake = camel_to_snake(name)
        args = p.get("args", [])
        word_count = GEOMETRY_OFFSET + len(args)
        cond = "if" if i == 0 else "else if"

        lines.append(f'    {cond} (strcmp(ctx->prim_type, "{snake}") == 0) {{')
        lines.append(f"        tmp = YPAINT_SDF_{camel_to_screaming(name)}; memcpy(&data[0], &tmp, sizeof(tmp));")
        lines.append(f"        tmp = ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));")
        lines.append(f"        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));")
        lines.append(f"        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));")
        lines.append(f"        data[4] = ctx->stroke_width;")
        for j, arg in enumerate(args):
            lines.append(f"        data[{GEOMETRY_OFFSET + j}] = ctx->{arg['name']};")
        lines.append(f"        wc = {word_count};")
        lines.append("    }")

    lines.append("    else {")
    lines.append('        ydebug("ypaint_yaml: unknown type \'%s\'", ctx->prim_type);')
    lines.append("        ctx->z_order++;")
    lines.append("        return;")
    lines.append("    }")
    lines.append("")
    lines.append("    ypaint_sdf_compute_aabb(data, wc, &minX, &minY, &maxX, &maxY);")
    lines.append("    ypaint_canvas_add_primitive(ctx->canvas, data, wc, minX, minY, maxX, maxY);")
    lines.append("    ctx->z_order++;")
    lines.append("}")
    lines.append("")

    # Main parser using libyaml events
    lines.append("/*=============================================================================")
    lines.append(" * YAML event parser")
    lines.append(" *===========================================================================*/")
    lines.append("")
    lines.append("int ypaint_sdf_yaml_parse(YPaintCanvasHandle canvas, const char *yaml, size_t len) {")
    lines.append("    yaml_parser_t parser;")
    lines.append("    yaml_event_t ev;")
    lines.append("    ParseCtx ctx = {0};")
    lines.append("    int done = 0, err = 0;")
    lines.append("    int depth = 0;       /* mapping depth */")
    lines.append("    int in_body = 0;     /* inside body sequence */")
    lines.append("    int in_prim = 0;     /* inside primitive map */")
    lines.append("    int in_prim_type = 0;/* inside primitive type map */")
    lines.append("    int expect_value = 0;")
    lines.append("")
    lines.append("    if (!canvas || !yaml) return -1;")
    lines.append("    ctx.canvas = canvas;")
    lines.append("")
    lines.append("    if (!yaml_parser_initialize(&parser)) return -1;")
    lines.append("    yaml_parser_set_input_string(&parser, (const unsigned char *)yaml, len);")
    lines.append("")
    lines.append("    while (!done && !err) {")
    lines.append("        if (!yaml_parser_parse(&parser, &ev)) { err = 1; break; }")
    lines.append("        switch (ev.type) {")
    lines.append("        case YAML_STREAM_END_EVENT: done = 1; break;")
    lines.append("        case YAML_MAPPING_START_EVENT:")
    lines.append("            depth++;")
    lines.append("            if (in_body && !in_prim) { in_prim = 1; reset_prim(&ctx); }")
    lines.append("            else if (in_prim && !in_prim_type) { in_prim_type = 1; }")
    lines.append("            break;")
    lines.append("        case YAML_MAPPING_END_EVENT:")
    lines.append("            if (in_prim_type) { add_prim(&ctx); in_prim_type = 0; in_prim = 0; }")
    lines.append("            depth--;")
    lines.append("            break;")
    lines.append("        case YAML_SEQUENCE_START_EVENT:")
    lines.append('            if (depth == 1 && strcmp(ctx.prop_key, "body") == 0) { in_body = 1; }')
    lines.append("            else if (in_prim_type) { ctx.in_array = 1; ctx.array_idx = 0; expect_value = 0; }")
    lines.append("            break;")
    lines.append("        case YAML_SEQUENCE_END_EVENT:")
    lines.append("            if (ctx.in_array) { store_array(&ctx); ctx.in_array = 0; }")
    lines.append("            else if (in_body && !in_prim) { in_body = 0; }")
    lines.append("            break;")
    lines.append("        case YAML_SCALAR_EVENT: {")
    lines.append("            const char *val = (const char *)ev.data.scalar.value;")
    lines.append("            if (ctx.in_array) {")
    lines.append("                if (ctx.array_idx < 8) ctx.array_vals[ctx.array_idx++] = strtof(val, NULL);")
    lines.append("            } else if (in_prim && !in_prim_type) {")
    lines.append("                strncpy(ctx.prim_type, val, sizeof(ctx.prim_type)-1);")
    lines.append("            } else if (in_prim_type) {")
    lines.append("                if (!expect_value) {")
    lines.append("                    strncpy(ctx.prop_key, val, sizeof(ctx.prop_key)-1);")
    lines.append("                    expect_value = 1;")
    lines.append("                } else {")
    lines.append('                    if (strcmp(ctx.prop_key, "fill") == 0) ctx.fill_color = parse_color(val);')
    lines.append('                    else if (strcmp(ctx.prop_key, "stroke") == 0) ctx.stroke_color = parse_color(val);')
    lines.append('                    else if (strcmp(ctx.prop_key, "stroke-width") == 0) ctx.stroke_width = strtof(val, NULL);')
    lines.append('                    else if (strcmp(ctx.prop_key, "radius") == 0) ctx.r = strtof(val, NULL);')
    lines.append('                    else if (strcmp(ctx.prop_key, "round") == 0) ctx.round = strtof(val, NULL);')
    lines.append('                    else if (strcmp(ctx.prop_key, "scale") == 0) ctx.scale = strtof(val, NULL);')
    lines.append('                    else if (strcmp(ctx.prop_key, "points") == 0) ctx.n = strtof(val, NULL);')
    lines.append('                    else if (strcmp(ctx.prop_key, "inner") == 0) ctx.m = strtof(val, NULL);')
    lines.append('                    else if (strcmp(ctx.prop_key, "thickness") == 0) ctx.th = strtof(val, NULL);')
    lines.append('                    else if (strcmp(ctx.prop_key, "distance") == 0) ctx.d = strtof(val, NULL);')
    lines.append('                    else if (strcmp(ctx.prop_key, "width") == 0) ctx.w = strtof(val, NULL);')
    lines.append('                    else if (strcmp(ctx.prop_key, "radius_outer") == 0) ctx.ra = strtof(val, NULL);')
    lines.append('                    else if (strcmp(ctx.prop_key, "radius_inner") == 0) ctx.rb = strtof(val, NULL);')
    lines.append("                    expect_value = 0;")
    lines.append("                }")
    lines.append("            } else if (depth == 1) {")
    lines.append("                strncpy(ctx.prop_key, val, sizeof(ctx.prop_key)-1);")
    lines.append("            }")
    lines.append("            break;")
    lines.append("        }")
    lines.append("        default: break;")
    lines.append("        }")
    lines.append("        yaml_event_delete(&ev);")
    lines.append("    }")
    lines.append("    yaml_parser_delete(&parser);")
    lines.append('    ydebug("ypaint_yaml: parsed %u primitives", ctx.z_order);')
    lines.append("    return err ? -1 : 0;")
    lines.append("}")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def main():
    prims = load_primitives(YAML_PATH)
    generate_sdf_types(prims, SDF_TYPES_OUT)
    generate_sdf_prim_header(prims, SDF_PRIM_H_OUT)
    generate_sdf_prim_impl(prims, SDF_PRIM_C_OUT)
    generate_sdf_aabb(prims, SDF_AABB_OUT)
    generate_sdf_wgsl(prims, SDF_WGSL_OUT)
    generate_sdf_yaml_header(prims, SDF_YAML_H_OUT)
    generate_sdf_yaml_impl(prims, SDF_YAML_C_OUT)
    print("Done.")


if __name__ == "__main__":
    main()
