// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ypaint/sdf/gen-sdf-code.py


#include <yetty/ypaint/sdf/ypaint-sdf-prim.gen.h>
#include <string.h>

struct yetty_ypaint_id_result ypaint_sdf_add_circle(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_circle *geom) {
    float data[8];
    uint32_t tmp;

    tmp = YPAINT_SDF_CIRCLE;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->radius;

    return yetty_ypaint_buffer_add_prim(buf, data, 8);
}

struct yetty_ypaint_id_result ypaint_sdf_add_box(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_box *geom) {
    float data[10];
    uint32_t tmp;

    tmp = YPAINT_SDF_BOX;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->half_width;
    data[8] = geom->half_height;
    data[9] = geom->corner_radius;

    return yetty_ypaint_buffer_add_prim(buf, data, 10);
}

struct yetty_ypaint_id_result ypaint_sdf_add_segment(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_segment *geom) {
    float data[9];
    uint32_t tmp;

    tmp = YPAINT_SDF_SEGMENT;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->start_x;
    data[6] = geom->start_y;
    data[7] = geom->end_x;
    data[8] = geom->end_y;

    return yetty_ypaint_buffer_add_prim(buf, data, 9);
}

struct yetty_ypaint_id_result ypaint_sdf_add_triangle(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_triangle *geom) {
    float data[11];
    uint32_t tmp;

    tmp = YPAINT_SDF_TRIANGLE;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->vertex_a_x;
    data[6] = geom->vertex_a_y;
    data[7] = geom->vertex_b_x;
    data[8] = geom->vertex_b_y;
    data[9] = geom->vertex_c_x;
    data[10] = geom->vertex_c_y;

    return yetty_ypaint_buffer_add_prim(buf, data, 11);
}

struct yetty_ypaint_id_result ypaint_sdf_add_ellipse(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_ellipse *geom) {
    float data[9];
    uint32_t tmp;

    tmp = YPAINT_SDF_ELLIPSE;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->radius_x;
    data[8] = geom->radius_y;

    return yetty_ypaint_buffer_add_prim(buf, data, 9);
}

struct yetty_ypaint_id_result ypaint_sdf_add_arc(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_arc *geom) {
    float data[11];
    uint32_t tmp;

    tmp = YPAINT_SDF_ARC;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->aperture_x;
    data[8] = geom->aperture_y;
    data[9] = geom->radius;
    data[10] = geom->thickness;

    return yetty_ypaint_buffer_add_prim(buf, data, 11);
}

struct yetty_ypaint_id_result ypaint_sdf_add_rounded_box(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_rounded_box *geom) {
    float data[13];
    uint32_t tmp;

    tmp = YPAINT_SDF_ROUNDED_BOX;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->half_width;
    data[8] = geom->half_height;
    data[9] = geom->radius_top_right;
    data[10] = geom->radius_bottom_right;
    data[11] = geom->radius_top_left;
    data[12] = geom->radius_bottom_left;

    return yetty_ypaint_buffer_add_prim(buf, data, 13);
}

struct yetty_ypaint_id_result ypaint_sdf_add_rhombus(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_rhombus *geom) {
    float data[9];
    uint32_t tmp;

    tmp = YPAINT_SDF_RHOMBUS;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->half_width;
    data[8] = geom->half_height;

    return yetty_ypaint_buffer_add_prim(buf, data, 9);
}

struct yetty_ypaint_id_result ypaint_sdf_add_pentagon(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_pentagon *geom) {
    float data[8];
    uint32_t tmp;

    tmp = YPAINT_SDF_PENTAGON;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->radius;

    return yetty_ypaint_buffer_add_prim(buf, data, 8);
}

struct yetty_ypaint_id_result ypaint_sdf_add_hexagon(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_hexagon *geom) {
    float data[8];
    uint32_t tmp;

    tmp = YPAINT_SDF_HEXAGON;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->radius;

    return yetty_ypaint_buffer_add_prim(buf, data, 8);
}

struct yetty_ypaint_id_result ypaint_sdf_add_star(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_star *geom) {
    float data[10];
    uint32_t tmp;

    tmp = YPAINT_SDF_STAR;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->radius;
    data[8] = geom->num_points;
    data[9] = geom->inner_ratio;

    return yetty_ypaint_buffer_add_prim(buf, data, 10);
}

struct yetty_ypaint_id_result ypaint_sdf_add_pie(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_pie *geom) {
    float data[10];
    uint32_t tmp;

    tmp = YPAINT_SDF_PIE;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->aperture_x;
    data[8] = geom->aperture_y;
    data[9] = geom->radius;

    return yetty_ypaint_buffer_add_prim(buf, data, 10);
}

struct yetty_ypaint_id_result ypaint_sdf_add_ring(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_ring *geom) {
    float data[11];
    uint32_t tmp;

    tmp = YPAINT_SDF_RING;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->normal_x;
    data[8] = geom->normal_y;
    data[9] = geom->radius;
    data[10] = geom->thickness;

    return yetty_ypaint_buffer_add_prim(buf, data, 11);
}

struct yetty_ypaint_id_result ypaint_sdf_add_heart(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_heart *geom) {
    float data[8];
    uint32_t tmp;

    tmp = YPAINT_SDF_HEART;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->scale;

    return yetty_ypaint_buffer_add_prim(buf, data, 8);
}

struct yetty_ypaint_id_result ypaint_sdf_add_cross(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_cross *geom) {
    float data[10];
    uint32_t tmp;

    tmp = YPAINT_SDF_CROSS;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->half_width;
    data[8] = geom->half_height;
    data[9] = geom->corner_radius;

    return yetty_ypaint_buffer_add_prim(buf, data, 10);
}

struct yetty_ypaint_id_result ypaint_sdf_add_rounded_x(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_rounded_x *geom) {
    float data[9];
    uint32_t tmp;

    tmp = YPAINT_SDF_ROUNDED_X;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->width;
    data[8] = geom->radius;

    return yetty_ypaint_buffer_add_prim(buf, data, 9);
}

struct yetty_ypaint_id_result ypaint_sdf_add_capsule(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_capsule *geom) {
    float data[10];
    uint32_t tmp;

    tmp = YPAINT_SDF_CAPSULE;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->start_x;
    data[6] = geom->start_y;
    data[7] = geom->end_x;
    data[8] = geom->end_y;
    data[9] = geom->radius;

    return yetty_ypaint_buffer_add_prim(buf, data, 10);
}

struct yetty_ypaint_id_result ypaint_sdf_add_moon(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_moon *geom) {
    float data[10];
    uint32_t tmp;

    tmp = YPAINT_SDF_MOON;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->offset;
    data[8] = geom->radius_outer;
    data[9] = geom->radius_inner;

    return yetty_ypaint_buffer_add_prim(buf, data, 10);
}

struct yetty_ypaint_id_result ypaint_sdf_add_egg(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_egg *geom) {
    float data[9];
    uint32_t tmp;

    tmp = YPAINT_SDF_EGG;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->radius_outer;
    data[8] = geom->radius_inner;

    return yetty_ypaint_buffer_add_prim(buf, data, 9);
}

struct yetty_ypaint_id_result ypaint_sdf_add_octogon(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_octogon *geom) {
    float data[8];
    uint32_t tmp;

    tmp = YPAINT_SDF_OCTOGON;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->radius;

    return yetty_ypaint_buffer_add_prim(buf, data, 8);
}

struct yetty_ypaint_id_result ypaint_sdf_add_hexagram(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_hexagram *geom) {
    float data[8];
    uint32_t tmp;

    tmp = YPAINT_SDF_HEXAGRAM;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->radius;

    return yetty_ypaint_buffer_add_prim(buf, data, 8);
}

struct yetty_ypaint_id_result ypaint_sdf_add_pentagram(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_pentagram *geom) {
    float data[8];
    uint32_t tmp;

    tmp = YPAINT_SDF_PENTAGRAM;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->center_x;
    data[6] = geom->center_y;
    data[7] = geom->radius;

    return yetty_ypaint_buffer_add_prim(buf, data, 8);
}

struct yetty_ypaint_id_result ypaint_sdf_add_sphere_3d(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_sphere_3d *geom) {
    float data[9];
    uint32_t tmp;

    tmp = YPAINT_SDF_SPHERE_3D;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->position_x;
    data[6] = geom->position_y;
    data[7] = geom->position_z;
    data[8] = geom->radius;

    return yetty_ypaint_buffer_add_prim(buf, data, 9);
}

struct yetty_ypaint_id_result ypaint_sdf_add_box_3d(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_box_3d *geom) {
    float data[11];
    uint32_t tmp;

    tmp = YPAINT_SDF_BOX_3D;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->position_x;
    data[6] = geom->position_y;
    data[7] = geom->position_z;
    data[8] = geom->half_size_x;
    data[9] = geom->half_size_y;
    data[10] = geom->half_size_z;

    return yetty_ypaint_buffer_add_prim(buf, data, 11);
}

struct yetty_ypaint_id_result ypaint_sdf_add_torus_3d(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_torus_3d *geom) {
    float data[10];
    uint32_t tmp;

    tmp = YPAINT_SDF_TORUS_3D;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->position_x;
    data[6] = geom->position_y;
    data[7] = geom->position_z;
    data[8] = geom->major_radius;
    data[9] = geom->minor_radius;

    return yetty_ypaint_buffer_add_prim(buf, data, 10);
}

struct yetty_ypaint_id_result ypaint_sdf_add_cylinder_3d(struct yetty_ypaint_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct ypaint_sdf_cylinder_3d *geom) {
    float data[10];
    uint32_t tmp;

    tmp = YPAINT_SDF_CYLINDER_3D;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = z_order;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fill_color;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = stroke_color;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = stroke_width;
    data[5] = geom->position_x;
    data[6] = geom->position_y;
    data[7] = geom->position_z;
    data[8] = geom->radius;
    data[9] = geom->half_height;

    return yetty_ypaint_buffer_add_prim(buf, data, 10);
}
