#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""Generate C and WGSL code from sdf-primitives.yaml.

Run:  uv run src/yetty/ysdf/gen-sdf-code.py

Reads:    src/yetty/ysdf/primitives.yaml
Generates:
  include/yetty/ysdf/types.gen.h  - C enums + geometry structs
  include/yetty/ysdf/prim.gen.h   - C add function declarations
  src/yetty/ysdf/funcs.gen.c       - C add function implementations
  src/yetty/ysdf/aabb.gen.c       - C AABB computation
  src/yetty/ysdf/wgsl.gen.wgsl         - WGSL SDF functions + dispatch
"""

from pathlib import Path
import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent.parent

YAML_PATH = SCRIPT_DIR / "primitives.yaml"
SDF_TYPES_OUT = PROJECT_ROOT / "include" / "yetty" / "ysdf" / "types.gen.h"
SDF_PRIM_H_OUT = PROJECT_ROOT / "include" / "yetty" / "ysdf" / "funcs.gen.h"
SDF_PRIM_C_OUT = SCRIPT_DIR / "funcs.gen.c"
SDF_AABB_OUT = SCRIPT_DIR / "aabb.gen.c"
SDF_WGSL_OUT = SCRIPT_DIR / "wgsl.gen.wgsl"
SDF_YAML_H_OUT = PROJECT_ROOT / "include" / "yetty" / "ysdf" / "yaml.gen.h"
SDF_YAML_C_OUT = PROJECT_ROOT / "src" / "yetty" / "ysdf" / "yaml.gen.c"

HEADER_C = """// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ysdf/gen-sdf-code.py
"""

HEADER_WGSL = """// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ysdf/gen-sdf-code.py
"""

# Buffer layout (in 32-bit words):
# [0] type (enum ysdf_type value)
# [1] z_order
# [2] fill_color
# [3] stroke_color
# [4] stroke_width
# [5+] geometry args

GEOMETRY_OFFSET = 5


def to_upper(name: str) -> str:
    """snake_case -> UPPER_SNAKE_CASE"""
    return name.upper()


def c_type(yaml_type: str) -> str:
    """Convert YAML type to C type"""
    return {"f32": "float", "u32": "uint32_t", "i32": "int32_t"}[yaml_type]


def load_primitives(path: Path) -> list[dict]:
    with open(path) as f:
        return yaml.safe_load(f)


def generate_sdf_types(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf-types.gen.h - enums and geometry structs for SDF primitives"""
    lines = [HEADER_C, "#pragma once", "", "#include <stddef.h>", "#include <stdint.h>", "", "#ifdef __cplusplus", 'extern "C" {', "#endif", ""]

    # Enum for SDF primitive types
    lines.append("enum yetty_ysdf_type {")
    for p in prims:
        lines.append(f"    YETTY_YSDF_{to_upper(p['name'])} = {p['type']},")
    lines.append("};")
    lines.append("")

    # Geometry structs for each SDF primitive
    for p in prims:
        name = p["name"]
        args = p.get("args", [])

        lines.append(f"struct yetty_ysdf_{name} {{")
        for arg in args:
            lines.append(f"    {c_type(arg['type'])} {arg['name']};")
        lines.append("};")
        lines.append("")

    # Word count for each SDF primitive type
    lines.append("// Word count per SDF primitive type")
    lines.append("static inline uint32_t yetty_ysdf_word_count(enum yetty_ysdf_type type) {")
    lines.append("    switch (type) {")
    for p in prims:
        name = p["name"]
        args = p.get("args", [])
        word_count = GEOMETRY_OFFSET + len(args)
        lines.append(f"        case YETTY_YSDF_{to_upper(name)}: return {word_count}u;")
    lines.append("        default: return 0u;")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # Primitive size in bytes (callback compatible)
    lines.append("// Primitive size in bytes - use as yetty_ypaint_core_primitive_size_fn callback")
    lines.append("static inline size_t yetty_ysdf_primitive_size(uint32_t type) {")
    lines.append("    return yetty_ysdf_word_count((enum yetty_ysdf_type)type) * sizeof(float);")
    lines.append("}")
    lines.append("")

    # AABB computation function declaration
    lines.append("// Compute AABB for an SDF primitive")
    lines.append("// data: full primitive data (type + z_order + style + geometry)")
    lines.append("// word_count: number of 32-bit words in data")
    lines.append("#include <yetty/ycore/types.h>")
    lines.append("")
    lines.append("struct rectangle_result yetty_ysdf_compute_aabb(const float *data, uint32_t word_count);")
    lines.append("")

    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def generate_sdf_prim_header(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf-prim.gen.h - add function declarations for SDF primitives"""
    lines = [HEADER_C, "#pragma once", ""]
    lines.append('#include "types.gen.h"')
    lines.append('#include <yetty/ypaint-core/buffer.h>')
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")

    for p in prims:
        name = p["name"]
        lines.append(f"struct yetty_ypaint_id_result yetty_ysdf_add_{name}(struct yetty_ypaint_core_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct yetty_ysdf_{name} *geom);")
        lines.append("")

    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def generate_sdf_prim_impl(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf-prim.gen.c - add function implementations for SDF primitives"""
    lines = [HEADER_C, ""]
    lines.append('#include <yetty/ysdf/funcs.gen.h>')
    lines.append('#include <string.h>')
    lines.append("")

    for p in prims:
        name = p["name"]
        args = p.get("args", [])
        word_count = GEOMETRY_OFFSET + len(args)

        lines.append(f"struct yetty_ypaint_id_result yetty_ysdf_add_{name}(struct yetty_ypaint_core_buffer *buf, uint32_t z_order, uint32_t fill_color, uint32_t stroke_color, float stroke_width, const struct yetty_ysdf_{name} *geom) {{")
        lines.append(f"    float data[{word_count}];")
        lines.append("    uint32_t tmp;")
        lines.append("")
        # Type
        lines.append(f"    tmp = YETTY_YSDF_{to_upper(name)};")
        lines.append("    memcpy(&data[0], &tmp, sizeof(tmp));")
        # z_order
        lines.append("    tmp = z_order;")
        lines.append("    memcpy(&data[1], &tmp, sizeof(tmp));")
        # fill_color
        lines.append("    tmp = fill_color;")
        lines.append("    memcpy(&data[2], &tmp, sizeof(tmp));")
        # stroke_color
        lines.append("    tmp = stroke_color;")
        lines.append("    memcpy(&data[3], &tmp, sizeof(tmp));")
        # stroke_width
        lines.append("    data[4] = stroke_width;")
        # Geometry args
        for i, arg in enumerate(args):
            offset = GEOMETRY_OFFSET + i
            if arg["type"] == "f32":
                lines.append(f"    data[{offset}] = geom->{arg['name']};")
            else:
                lines.append(f"    tmp = geom->{arg['name']};")
                lines.append(f"    memcpy(&data[{offset}], &tmp, sizeof(tmp));")
        lines.append("")
        lines.append(f"    return yetty_ypaint_core_buffer_add_prim(buf, data, {word_count} * sizeof(float));")
        lines.append("}")
        lines.append("")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def generate_sdf_aabb(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf-aabb.gen.c - AABB computation for SDF primitives"""
    lines = [HEADER_C, ""]
    lines.append('#include <yetty/ysdf/types.gen.h>')
    lines.append('#include <math.h>')
    lines.append('#include <string.h>')
    lines.append("")
    lines.append("struct rectangle_result yetty_ysdf_compute_aabb(const float *data, uint32_t word_count) {")
    lines.append("    if (!data)")
    lines.append('        return YETTY_ERR(rectangle, "data is NULL");')
    lines.append("    uint32_t type;")
    lines.append("    memcpy(&type, &data[0], sizeof(type));")
    lines.append(f"    const float *geom = data + {GEOMETRY_OFFSET};  // geometry args")
    lines.append("    float stroke_width = data[4];")
    lines.append("    float expand = stroke_width * 0.5f;")
    lines.append("    struct rectangle rect = {0};")
    lines.append("    (void)word_count;")
    lines.append("")
    lines.append("    switch ((enum yetty_ysdf_type)type) {")

    for p in prims:
        name = p["name"]
        aabb_code = p.get("aabb", {}).get("code", "").strip()
        if not aabb_code:
            aabb_code = "rect.min.x = -1e10f; rect.min.y = -1e10f; rect.max.x = 1e10f; rect.max.y = 1e10f;"
        else:
            # Replace *min_x/*min_y/*max_x/*max_y with rect.min.x etc.
            aabb_code = aabb_code.replace("*min_x", "rect.min.x")
            aabb_code = aabb_code.replace("*min_y", "rect.min.y")
            aabb_code = aabb_code.replace("*max_x", "rect.max.x")
            aabb_code = aabb_code.replace("*max_y", "rect.max.y")

        lines.append(f"    case YETTY_YSDF_{to_upper(name)}: {{")
        for line in aabb_code.split("\n"):
            lines.append(f"        {line}")
        lines.append("        break;")
        lines.append("    }")

    lines.append("    default:")
    lines.append('        return YETTY_ERR(rectangle, "unknown SDF type");')
    lines.append("    }")
    lines.append("    return YETTY_OK(rectangle, rect);")
    lines.append("}")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def generate_sdf_wgsl(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf.gen.wgsl - WGSL SDF functions and dispatcher"""
    lines = [HEADER_WGSL, ""]

    # Generate individual SDF functions
    for p in prims:
        name = p["name"]
        args = p.get("args", [])
        shader = p.get("shader", {}).get("code", "")
        if not shader.strip():
            continue

        # Function signature with explicit params
        params = ["sample_pos: vec2<f32>"] if p["category"] == "sdf2d" else ["sample_pos: vec3<f32>"]
        for arg in args:
            wgsl_type = "f32" if arg["type"] == "f32" else "u32"
            params.append(f"{arg['name']}: {wgsl_type}")

        lines.append(f"fn sdf_{name}({', '.join(params)}) -> f32 {{")
        for line in shader.strip().split("\n"):
            lines.append(f"    {line}")
        lines.append("}")
        lines.append("")

    # Generate dispatcher for 2D
    sdf2d = [p for p in prims if p["category"] == "sdf2d"]
    if sdf2d:
        lines.append("fn evaluate_sdf_2d(prim_offset: u32, sample_pos: vec2<f32>) -> f32 {")
        lines.append("    let prim_type = bitcast<u32>(buf[prim_offset]);")
        lines.append("    switch (prim_type) {")
        for p in sdf2d:
            name = p["name"]
            args = p.get("args", [])
            arg_accesses = [f"buf[prim_offset + {GEOMETRY_OFFSET + i}u]" for i in range(len(args))]
            lines.append(f"        case {p['type']}u: {{ return sdf_{name}(sample_pos, {', '.join(arg_accesses)}); }}")
        lines.append("        default: { return 1e10; }")
        lines.append("    }")
        lines.append("}")
        lines.append("")

    # Generate dispatcher for 3D
    sdf3d = [p for p in prims if p["category"] == "sdf3d"]
    if sdf3d:
        lines.append("fn evaluate_sdf_3d(prim_offset: u32, sample_pos: vec3<f32>) -> f32 {")
        lines.append("    let prim_type = bitcast<u32>(buf[prim_offset]);")
        lines.append("    switch (prim_type) {")
        for p in sdf3d:
            name = p["name"]
            args = p.get("args", [])
            arg_accesses = [f"buf[prim_offset + {GEOMETRY_OFFSET + i}u]" for i in range(len(args))]
            lines.append(f"        case {p['type']}u: {{ return sdf_{name}(sample_pos, {', '.join(arg_accesses)}); }}")
        lines.append("        default: { return 1e10; }")
        lines.append("    }")
        lines.append("}")
        lines.append("")

    # Style extraction
    lines.append("fn get_sdf_prim_style(prim_offset: u32) -> vec3<u32> {")
    lines.append("    return vec3<u32>(")
    lines.append("        bitcast<u32>(buf[prim_offset + 2u]),  // fill_color")
    lines.append("        bitcast<u32>(buf[prim_offset + 3u]),  // stroke_color")
    lines.append("        bitcast<u32>(buf[prim_offset + 4u])   // stroke_width as bits")
    lines.append("    );")
    lines.append("}")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def infer_yaml_props(args: list[dict]) -> list[tuple[str, str, list[str], str]]:
    """Infer YAML property mappings from arg names.
    Returns list of (yaml_key, type, [arg_names], transform)
    type: vec2, scalar, size (divides by 2)
    """
    arg_names = [a["name"] for a in args]
    props = []

    # Position patterns
    if "center_x" in arg_names and "center_y" in arg_names:
        props.append(("position", "vec2", ["center_x", "center_y"], ""))
    if "vertex_a_x" in arg_names and "vertex_a_y" in arg_names:
        props.append(("vertex_a", "vec2", ["vertex_a_x", "vertex_a_y"], ""))
        props.append(("vertex_b", "vec2", ["vertex_b_x", "vertex_b_y"], ""))
        if "vertex_c_x" in arg_names:
            props.append(("vertex_c", "vec2", ["vertex_c_x", "vertex_c_y"], ""))
    if "start_x" in arg_names and "start_y" in arg_names:
        props.append(("start", "vec2", ["start_x", "start_y"], ""))
        props.append(("end", "vec2", ["end_x", "end_y"], ""))

    # Size patterns
    if "half_width" in arg_names and "half_height" in arg_names:
        props.append(("size", "size", ["half_width", "half_height"], "/ 2.0f"))

    # Radius patterns
    if "radius" in arg_names:
        props.append(("radius", "scalar", ["radius"], ""))
    if "radius_x" in arg_names and "radius_y" in arg_names:
        props.append(("radii", "vec2", ["radius_x", "radius_y"], ""))
    if "radius_outer" in arg_names and "radius_inner" in arg_names:
        props.append(("radius_outer", "scalar", ["radius_outer"], ""))
        props.append(("radius_inner", "scalar", ["radius_inner"], ""))

    # Other scalars
    if "corner_radius" in arg_names:
        props.append(("corner_radius", "scalar", ["corner_radius"], ""))
    if "scale" in arg_names:
        props.append(("scale", "scalar", ["scale"], ""))
    if "num_points" in arg_names:
        props.append(("num_points", "scalar", ["num_points"], ""))
    if "inner_ratio" in arg_names:
        props.append(("inner_ratio", "scalar", ["inner_ratio"], ""))
    if "thickness" in arg_names:
        props.append(("thickness", "scalar", ["thickness"], ""))
    if "offset" in arg_names:
        props.append(("offset", "scalar", ["offset"], ""))
    if "width" in arg_names:
        props.append(("width", "scalar", ["width"], ""))

    return props


def generate_sdf_yaml_header(prims: list[dict], out: Path) -> None:
    """Generate ypaint-yaml.gen.h - YAML parsing declarations"""
    lines = [HEADER_C, "#pragma once", ""]
    lines.append('#include <yetty/ysdf/types.gen.h>')
    lines.append('#include <yetty/ypaint-core/buffer.h>')
    lines.append('#include <stddef.h>')
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")
    lines.append("/**")
    lines.append(" * Parse YAML body and add primitives to canvas.")
    lines.append(" * @param canvas Target canvas")
    lines.append(" * @param yaml YAML string (null-terminated)")
    lines.append(" * @param len Length of YAML string")
    lines.append(" * @return 0 on success, -1 on error")
    lines.append(" */")
    lines.append("int yetty_ysdf_yaml_parse(struct yetty_ypaint_core_buffer *canvas, const char *yaml, size_t len);")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def generate_sdf_yaml_impl(prims: list[dict], out: Path) -> None:
    """Generate ypaint-sdf-yaml.gen.c - YAML parsing implementation"""
    # Only generate for 2D primitives
    prims_2d = [p for p in prims if p["category"] == "sdf2d"]

    lines = [HEADER_C, ""]
    lines.append('#include <yetty/ysdf/yaml.gen.h>')
    lines.append('#include <yetty/ysdf/types.gen.h>')
    lines.append('#include <yetty/ypaint-core/buffer.h>')
    lines.append('#include <yetty/ytrace.h>')
    lines.append('#include <yaml.h>')
    lines.append('#include <stdlib.h>')
    lines.append('#include <string.h>')
    lines.append('#include <math.h>')
    lines.append("")

    # Color parsing helper
    lines.append("/*=============================================================================")
    lines.append(" * Helpers")
    lines.append(" *===========================================================================*/")
    lines.append("")
    lines.append("static uint32_t parse_color(const char *str) {")
    lines.append("    if (!str || !*str) return 0;")
    lines.append("    if (str[0] == '#') str++;")
    lines.append("    size_t len = strlen(str);")
    lines.append("    char buf[9] = {0};")
    lines.append("    if (len == 3) {")
    lines.append('        buf[0] = buf[1] = str[0]; buf[2] = buf[3] = str[1]; buf[4] = buf[5] = str[2]; buf[6] = buf[7] = \'F\';')
    lines.append("    } else if (len == 6) {")
    lines.append('        memcpy(buf, str, 6); buf[6] = buf[7] = \'F\';')
    lines.append("    } else if (len == 8) {")
    lines.append("        memcpy(buf, str, 8);")
    lines.append("    } else return 0;")
    lines.append("    char *end;")
    lines.append("    unsigned long v = strtoul(buf, &end, 16);")
    lines.append("    if (*end) return 0;")
    lines.append("    uint32_t r = (v >> 24) & 0xFF, g = (v >> 16) & 0xFF, b = (v >> 8) & 0xFF, a = v & 0xFF;")
    lines.append("    return (a << 24) | (b << 16) | (g << 8) | r;")
    lines.append("}")
    lines.append("")

    # Parser context structure
    lines.append("/*=============================================================================")
    lines.append(" * Parser context")
    lines.append(" *===========================================================================*/")
    lines.append("")
    lines.append("struct ypaint_yaml_parse_ctx {")
    lines.append("    struct yetty_ypaint_core_buffer *buffer;")
    lines.append("    uint32_t z_order;")
    lines.append("    /* Current primitive state */")
    lines.append("    char prim_type[32];")
    lines.append("    char prop_key[32];")
    lines.append("    uint32_t fill_color;")
    lines.append("    uint32_t stroke_color;")
    lines.append("    float stroke_width;")

    # Add geometry fields for all args across all primitives
    all_args = set()
    for p in prims_2d:
        for arg in p.get("args", []):
            all_args.add(arg["name"])
    for arg in sorted(all_args):
        lines.append(f"    float {arg};")

    lines.append("    /* Array parsing state */")
    lines.append("    int in_array;")
    lines.append("    int array_idx;")
    lines.append("    float array_vals[8];")
    lines.append("};")
    lines.append("")

    # Reset function
    lines.append("static void reset_prim(struct ypaint_yaml_parse_ctx *yaml_parse_ctx) {")
    lines.append('    yaml_parse_ctx->prim_type[0] = 0;')
    lines.append('    yaml_parse_ctx->prop_key[0] = 0;')
    lines.append("    yaml_parse_ctx->fill_color = 0;")
    lines.append("    yaml_parse_ctx->stroke_color = 0;")
    lines.append("    yaml_parse_ctx->stroke_width = 0;")
    for arg in sorted(all_args):
        lines.append(f"    yaml_parse_ctx->{arg} = 0;")
    lines.append("    yaml_parse_ctx->in_array = 0;")
    lines.append("    yaml_parse_ctx->array_idx = 0;")
    lines.append("}")
    lines.append("")

    # Store array values based on property key
    lines.append("static void store_array(struct ypaint_yaml_parse_ctx *yaml_parse_ctx) {")
    lines.append('    const char *key = yaml_parse_ctx->prop_key;')
    lines.append('    ydebug("store_array: key=\'%s\' idx=%d vals=[%f,%f]", key, yaml_parse_ctx->array_idx, yaml_parse_ctx->array_vals[0], yaml_parse_ctx->array_vals[1]);')
    lines.append('    if (strcmp(key, "position") == 0 && yaml_parse_ctx->array_idx >= 2) {')
    lines.append("        yaml_parse_ctx->center_x = yaml_parse_ctx->array_vals[0]; yaml_parse_ctx->center_y = yaml_parse_ctx->array_vals[1];")
    lines.append('        ydebug("store_array: set center_x=%f center_y=%f", yaml_parse_ctx->center_x, yaml_parse_ctx->center_y);')
    lines.append("    }")
    lines.append('    else if (strcmp(key, "size") == 0 && yaml_parse_ctx->array_idx >= 2) {')
    lines.append("        yaml_parse_ctx->half_width = yaml_parse_ctx->array_vals[0] / 2.0f; yaml_parse_ctx->half_height = yaml_parse_ctx->array_vals[1] / 2.0f;")
    lines.append("    }")
    lines.append('    else if (strcmp(key, "start") == 0 && yaml_parse_ctx->array_idx >= 2) {')
    lines.append("        yaml_parse_ctx->start_x = yaml_parse_ctx->array_vals[0]; yaml_parse_ctx->start_y = yaml_parse_ctx->array_vals[1];")
    lines.append("    }")
    lines.append('    else if (strcmp(key, "end") == 0 && yaml_parse_ctx->array_idx >= 2) {')
    lines.append("        yaml_parse_ctx->end_x = yaml_parse_ctx->array_vals[0]; yaml_parse_ctx->end_y = yaml_parse_ctx->array_vals[1];")
    lines.append("    }")
    lines.append('    else if (strcmp(key, "vertex_a") == 0 && yaml_parse_ctx->array_idx >= 2) {')
    lines.append("        yaml_parse_ctx->vertex_a_x = yaml_parse_ctx->array_vals[0]; yaml_parse_ctx->vertex_a_y = yaml_parse_ctx->array_vals[1];")
    lines.append("    }")
    lines.append('    else if (strcmp(key, "vertex_b") == 0 && yaml_parse_ctx->array_idx >= 2) {')
    lines.append("        yaml_parse_ctx->vertex_b_x = yaml_parse_ctx->array_vals[0]; yaml_parse_ctx->vertex_b_y = yaml_parse_ctx->array_vals[1];")
    lines.append("    }")
    lines.append('    else if (strcmp(key, "vertex_c") == 0 && yaml_parse_ctx->array_idx >= 2) {')
    lines.append("        yaml_parse_ctx->vertex_c_x = yaml_parse_ctx->array_vals[0]; yaml_parse_ctx->vertex_c_y = yaml_parse_ctx->array_vals[1];")
    lines.append("    }")
    lines.append('    else if (strcmp(key, "radii") == 0 && yaml_parse_ctx->array_idx >= 2) {')
    lines.append("        yaml_parse_ctx->radius_x = yaml_parse_ctx->array_vals[0]; yaml_parse_ctx->radius_y = yaml_parse_ctx->array_vals[1];")
    lines.append("    }")
    lines.append('    else if (strcmp(key, "aperture") == 0 && yaml_parse_ctx->array_idx >= 2) {')
    lines.append("        yaml_parse_ctx->aperture_x = yaml_parse_ctx->array_vals[0]; yaml_parse_ctx->aperture_y = yaml_parse_ctx->array_vals[1];")
    lines.append("    }")
    lines.append('    else if (strcmp(key, "normal") == 0 && yaml_parse_ctx->array_idx >= 2) {')
    lines.append("        yaml_parse_ctx->normal_x = yaml_parse_ctx->array_vals[0]; yaml_parse_ctx->normal_y = yaml_parse_ctx->array_vals[1];")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # Add primitive function
    lines.append("static void add_prim(struct ypaint_yaml_parse_ctx *yaml_parse_ctx) {")
    lines.append("    float data[16];")
    lines.append("    uint32_t word_count = 0, tmp;")
    lines.append("")

    lines.append('    ydebug("add_prim: type=\'%s\' center_x=%f center_y=%f radius=%f fill=0x%08x", yaml_parse_ctx->prim_type, yaml_parse_ctx->center_x, yaml_parse_ctx->center_y, yaml_parse_ctx->radius, yaml_parse_ctx->fill_color);')
    lines.append("")

    for i, p in enumerate(prims_2d):
        name = p["name"]
        args = p.get("args", [])
        prim_word_count = GEOMETRY_OFFSET + len(args)
        cond = "if" if i == 0 else "else if"

        lines.append(f'    {cond} (strcmp(yaml_parse_ctx->prim_type, "{name}") == 0) {{')
        lines.append(f"        tmp = YETTY_YSDF_{to_upper(name)}; memcpy(&data[0], &tmp, sizeof(tmp));")
        lines.append(f"        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));")
        lines.append(f"        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));")
        lines.append(f"        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));")
        lines.append(f"        data[4] = yaml_parse_ctx->stroke_width;")
        for j, arg in enumerate(args):
            lines.append(f"        data[{GEOMETRY_OFFSET + j}] = yaml_parse_ctx->{arg['name']};")
        lines.append(f"        word_count = {prim_word_count};")
        lines.append("    }")

    lines.append("    else {")
    lines.append('        ydebug("ypaint_yaml: unknown type \'%s\'", yaml_parse_ctx->prim_type);')
    lines.append("        yaml_parse_ctx->z_order++;")
    lines.append("        return;")
    lines.append("    }")
    lines.append("")
    lines.append("    /* Add primitive to buffer */")
    lines.append("    yetty_ypaint_core_buffer_add_prim(yaml_parse_ctx->buffer, data, word_count * sizeof(float));")
    lines.append("    yaml_parse_ctx->z_order++;")
    lines.append("}")
    lines.append("")

    # Main parser using libyaml events
    lines.append("/*=============================================================================")
    lines.append(" * YAML event parser")
    lines.append(" *===========================================================================*/")
    lines.append("")
    lines.append("int yetty_ysdf_yaml_parse(struct yetty_ypaint_core_buffer *buffer, const char *yaml_str, size_t yaml_len) {")
    lines.append("    yaml_parser_t parser;")
    lines.append("    yaml_event_t event;")
    lines.append("    struct ypaint_yaml_parse_ctx yaml_parse_ctx = {0};")
    lines.append("    int done = 0, err = 0;")
    lines.append("    int depth = 0;       /* mapping depth */")
    lines.append("    int in_body = 0;     /* inside body sequence */")
    lines.append("    int in_prim = 0;     /* inside primitive map */")
    lines.append("    int in_prim_type = 0;/* inside primitive type map */")
    lines.append("    int expect_value = 0;")
    lines.append("")
    lines.append("    if (!buffer || !yaml_str) return -1;")
    lines.append("    yaml_parse_ctx.buffer = buffer;")
    lines.append("")
    lines.append("    if (!yaml_parser_initialize(&parser)) return -1;")
    lines.append("    yaml_parser_set_input_string(&parser, (const unsigned char *)yaml_str, yaml_len);")
    lines.append("")
    lines.append("    while (!done && !err) {")
    lines.append("        if (!yaml_parser_parse(&parser, &event)) { err = 1; break; }")
    lines.append("        switch (event.type) {")
    lines.append("        case YAML_STREAM_END_EVENT: done = 1; break;")
    lines.append("        case YAML_MAPPING_START_EVENT:")
    lines.append("            depth++;")
    lines.append("            if (in_body && !in_prim) { in_prim = 1; reset_prim(&yaml_parse_ctx); }")
    lines.append("            else if (in_prim && !in_prim_type) { in_prim_type = 1; }")
    lines.append("            break;")
    lines.append("        case YAML_MAPPING_END_EVENT:")
    lines.append("            if (in_prim_type) { add_prim(&yaml_parse_ctx); in_prim_type = 0; in_prim = 0; }")
    lines.append("            depth--;")
    lines.append("            break;")
    lines.append("        case YAML_SEQUENCE_START_EVENT:")
    lines.append('            if (depth == 1 && strcmp(yaml_parse_ctx.prop_key, "body") == 0) { in_body = 1; }')
    lines.append("            else if (in_prim_type) { yaml_parse_ctx.in_array = 1; yaml_parse_ctx.array_idx = 0; expect_value = 0; }")
    lines.append("            break;")
    lines.append("        case YAML_SEQUENCE_END_EVENT:")
    lines.append("            if (yaml_parse_ctx.in_array) { store_array(&yaml_parse_ctx); yaml_parse_ctx.in_array = 0; }")
    lines.append("            else if (in_body && !in_prim) { in_body = 0; }")
    lines.append("            break;")
    lines.append("        case YAML_SCALAR_EVENT: {")
    lines.append("            const char *scalar_value = (const char *)event.data.scalar.value;")
    lines.append("            if (yaml_parse_ctx.in_array) {")
    lines.append("                if (yaml_parse_ctx.array_idx < 8) yaml_parse_ctx.array_vals[yaml_parse_ctx.array_idx++] = strtof(scalar_value, NULL);")
    lines.append("            } else if (in_prim && !in_prim_type) {")
    lines.append("                strncpy(yaml_parse_ctx.prim_type, scalar_value, sizeof(yaml_parse_ctx.prim_type)-1);")
    lines.append("            } else if (in_prim_type) {")
    lines.append("                if (!expect_value) {")
    lines.append("                    strncpy(yaml_parse_ctx.prop_key, scalar_value, sizeof(yaml_parse_ctx.prop_key)-1);")
    lines.append("                    expect_value = 1;")
    lines.append("                } else {")
    lines.append('                    if (strcmp(yaml_parse_ctx.prop_key, "fill") == 0) yaml_parse_ctx.fill_color = parse_color(scalar_value);')
    lines.append('                    else if (strcmp(yaml_parse_ctx.prop_key, "stroke") == 0) yaml_parse_ctx.stroke_color = parse_color(scalar_value);')
    lines.append('                    else if (strcmp(yaml_parse_ctx.prop_key, "stroke_width") == 0) yaml_parse_ctx.stroke_width = strtof(scalar_value, NULL);')
    lines.append('                    else if (strcmp(yaml_parse_ctx.prop_key, "radius") == 0) yaml_parse_ctx.radius = strtof(scalar_value, NULL);')
    lines.append('                    else if (strcmp(yaml_parse_ctx.prop_key, "corner_radius") == 0) yaml_parse_ctx.corner_radius = strtof(scalar_value, NULL);')
    lines.append('                    else if (strcmp(yaml_parse_ctx.prop_key, "scale") == 0) yaml_parse_ctx.scale = strtof(scalar_value, NULL);')
    lines.append('                    else if (strcmp(yaml_parse_ctx.prop_key, "num_points") == 0) yaml_parse_ctx.num_points = strtof(scalar_value, NULL);')
    lines.append('                    else if (strcmp(yaml_parse_ctx.prop_key, "inner_ratio") == 0) yaml_parse_ctx.inner_ratio = strtof(scalar_value, NULL);')
    lines.append('                    else if (strcmp(yaml_parse_ctx.prop_key, "thickness") == 0) yaml_parse_ctx.thickness = strtof(scalar_value, NULL);')
    lines.append('                    else if (strcmp(yaml_parse_ctx.prop_key, "offset") == 0) yaml_parse_ctx.offset = strtof(scalar_value, NULL);')
    lines.append('                    else if (strcmp(yaml_parse_ctx.prop_key, "width") == 0) yaml_parse_ctx.width = strtof(scalar_value, NULL);')
    lines.append('                    else if (strcmp(yaml_parse_ctx.prop_key, "radius_outer") == 0) yaml_parse_ctx.radius_outer = strtof(scalar_value, NULL);')
    lines.append('                    else if (strcmp(yaml_parse_ctx.prop_key, "radius_inner") == 0) yaml_parse_ctx.radius_inner = strtof(scalar_value, NULL);')
    lines.append("                    expect_value = 0;")
    lines.append("                }")
    lines.append("            } else if (depth == 1) {")
    lines.append("                strncpy(yaml_parse_ctx.prop_key, scalar_value, sizeof(yaml_parse_ctx.prop_key)-1);")
    lines.append("            }")
    lines.append("            break;")
    lines.append("        }")
    lines.append("        default: break;")
    lines.append("        }")
    lines.append("        yaml_event_delete(&event);")
    lines.append("    }")
    lines.append("    yaml_parser_delete(&parser);")
    lines.append("")
    lines.append("    /* Buffer is now populated with primitives */")
    lines.append('    ydebug("ypaint_yaml: parsed %u primitives", yaml_parse_ctx.z_order);')
    lines.append("    return err ? -1 : 0;")
    lines.append("}")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def main():
    prims = load_primitives(YAML_PATH)
    generate_sdf_types(prims, SDF_TYPES_OUT)
    generate_sdf_prim_header(prims, SDF_PRIM_H_OUT)
    generate_sdf_prim_impl(prims, SDF_PRIM_C_OUT)
    generate_sdf_aabb(prims, SDF_AABB_OUT)
    generate_sdf_wgsl(prims, SDF_WGSL_OUT)
    generate_sdf_yaml_header(prims, SDF_YAML_H_OUT)
    generate_sdf_yaml_impl(prims, SDF_YAML_C_OUT)
    print("Done.")


if __name__ == "__main__":
    main()
