// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ysdf/gen-sdf-code.py


fn sdf_circle(sample_pos: vec2<f32>, center_x: f32, center_y: f32, radius: f32) -> f32 {
    return length(sample_pos - vec2<f32>(center_x, center_y)) - radius;
}

fn sdf_box(sample_pos: vec2<f32>, center_x: f32, center_y: f32, half_width: f32, half_height: f32, corner_radius: f32) -> f32 {
    let d = abs(sample_pos - vec2<f32>(center_x, center_y)) - vec2<f32>(half_width, half_height) + corner_radius;
    return length(max(d, vec2<f32>(0.0))) + min(max(d.x, d.y), 0.0) - corner_radius;
}

fn sdf_segment(sample_pos: vec2<f32>, start_x: f32, start_y: f32, end_x: f32, end_y: f32) -> f32 {
    let start_point = vec2<f32>(start_x, start_y);
    let end_point = vec2<f32>(end_x, end_y);
    let pos_to_start = sample_pos - start_point;
    let start_to_end = end_point - start_point;
    let t = clamp(dot(pos_to_start, start_to_end) / dot(start_to_end, start_to_end), 0.0, 1.0);
    return length(pos_to_start - start_to_end * t);
}

fn sdf_triangle(sample_pos: vec2<f32>, vertex_a_x: f32, vertex_a_y: f32, vertex_b_x: f32, vertex_b_y: f32, vertex_c_x: f32, vertex_c_y: f32) -> f32 {
    let p0 = vec2<f32>(vertex_a_x, vertex_a_y);
    let p1 = vec2<f32>(vertex_b_x, vertex_b_y);
    let p2 = vec2<f32>(vertex_c_x, vertex_c_y);
    let e0 = p1 - p0; let e1 = p2 - p1; let e2 = p0 - p2;
    let v0 = sample_pos - p0; let v1 = sample_pos - p1; let v2 = sample_pos - p2;
    let pq0 = v0 - e0 * clamp(dot(v0, e0) / dot(e0, e0), 0.0, 1.0);
    let pq1 = v1 - e1 * clamp(dot(v1, e1) / dot(e1, e1), 0.0, 1.0);
    let pq2 = v2 - e2 * clamp(dot(v2, e2) / dot(e2, e2), 0.0, 1.0);
    let s = sign(e0.x * e2.y - e0.y * e2.x);
    let d = min(min(
        vec2<f32>(dot(pq0, pq0), s * (v0.x * e0.y - v0.y * e0.x)),
        vec2<f32>(dot(pq1, pq1), s * (v1.x * e1.y - v1.y * e1.x))),
        vec2<f32>(dot(pq2, pq2), s * (v2.x * e2.y - v2.y * e2.x)));
    return -sqrt(d.x) * sign(d.y);
}

fn sdf_ellipse(sample_pos: vec2<f32>, center_x: f32, center_y: f32, radius_x: f32, radius_y: f32) -> f32 {
    let center = vec2<f32>(center_x, center_y);
    let radii = vec2<f32>(radius_x, radius_y);
    if (abs(radii.x - radii.y) < 0.001) { return length(sample_pos - center) - radii.x; }
    var pos = abs(sample_pos - center);
    var ab = radii;
    if (pos.x > pos.y) { pos = pos.yx; ab = ab.yx; }
    let l = ab.y * ab.y - ab.x * ab.x;
    let m = ab.x * pos.x / l; let m2 = m * m;
    let n = ab.y * pos.y / l; let n2 = n * n;
    let c = (m2 + n2 - 1.0) / 3.0; let c3 = c * c * c;
    let q = c3 + m2 * n2 * 2.0;
    let d = c3 + m2 * n2;
    let g = m + m * n2;
    var co: f32;
    if (d < 0.0) {
        let h = acos(q / c3) / 3.0;
        let s = cos(h); let t = sin(h) * sqrt(3.0);
        let rx = sqrt(-c * (s + t + 2.0) + m2);
        let ry = sqrt(-c * (s - t + 2.0) + m2);
        co = (ry + sign(l) * rx + abs(g) / (rx * ry) - m) / 2.0;
    } else {
        let h = 2.0 * m * n * sqrt(d);
        let s = sign(q + h) * pow(abs(q + h), 1.0 / 3.0);
        let u = sign(q - h) * pow(abs(q - h), 1.0 / 3.0);
        let rx = -s - u - c * 4.0 + 2.0 * m2;
        let ry = (s - u) * sqrt(3.0);
        let rm = sqrt(rx * rx + ry * ry);
        co = (ry / sqrt(rm - rx) + 2.0 * g / rm - m) / 2.0;
    }
    let r = ab * vec2<f32>(co, sqrt(1.0 - co * co));
    return length(r - pos) * sign(pos.y - r.y);
}

fn sdf_arc(sample_pos: vec2<f32>, center_x: f32, center_y: f32, aperture_x: f32, aperture_y: f32, radius: f32, thickness: f32) -> f32 {
    let center = vec2<f32>(center_x, center_y);
    let aperture = vec2<f32>(aperture_x, aperture_y);
    var pos = abs(sample_pos - center);
    if (aperture.y * pos.x > aperture.x * pos.y) { return length(pos - aperture * radius) - thickness; }
    return abs(length(pos) - radius) - thickness;
}

fn sdf_rounded_box(sample_pos: vec2<f32>, center_x: f32, center_y: f32, half_width: f32, half_height: f32, radius_top_right: f32, radius_bottom_right: f32, radius_top_left: f32, radius_bottom_left: f32) -> f32 {
    let center = vec2<f32>(center_x, center_y);
    let half_size = vec2<f32>(half_width, half_height);
    let radii = vec4<f32>(radius_top_right, radius_bottom_right, radius_top_left, radius_bottom_left);
    var pos = sample_pos - center;
    var corner_radii = select(radii.zw, radii.xy, pos.x > 0.0).xyxy;
    corner_radii.x = select(corner_radii.y, corner_radii.x, pos.y > 0.0);
    let q = abs(pos) - half_size + corner_radii.x;
    return min(max(q.x, q.y), 0.0) + length(max(q, vec2<f32>(0.0))) - corner_radii.x;
}

fn sdf_rhombus(sample_pos: vec2<f32>, center_x: f32, center_y: f32, half_width: f32, half_height: f32) -> f32 {
    var pos = abs(sample_pos - vec2<f32>(center_x, center_y));
    var half_diag = vec2<f32>(half_width, -half_height);
    let t = clamp((dot(half_diag, pos) + half_diag.y * half_diag.y) / dot(half_diag, half_diag), 0.0, 1.0);
    pos -= half_diag * vec2<f32>(t, t - 1.0);
    return length(pos) * sign(pos.x);
}

fn sdf_pentagon(sample_pos: vec2<f32>, center_x: f32, center_y: f32, radius: f32) -> f32 {
    let k = vec3<f32>(0.809016994, 0.587785252, 0.726542528);
    var pos = sample_pos - vec2<f32>(center_x, center_y);
    pos.x = abs(pos.x);
    pos -= 2.0 * min(dot(vec2<f32>(-k.x, k.y), pos), 0.0) * vec2<f32>(-k.x, k.y);
    pos -= 2.0 * min(dot(vec2<f32>(k.x, k.y), pos), 0.0) * vec2<f32>(k.x, k.y);
    pos -= vec2<f32>(clamp(pos.x, -radius * k.z, radius * k.z), radius);
    return length(pos) * sign(pos.y);
}

fn sdf_hexagon(sample_pos: vec2<f32>, center_x: f32, center_y: f32, radius: f32) -> f32 {
    let k = vec3<f32>(-0.866025404, 0.5, 0.577350269);
    var pos = abs(sample_pos - vec2<f32>(center_x, center_y));
    pos -= 2.0 * min(dot(k.xy, pos), 0.0) * k.xy;
    pos -= vec2<f32>(clamp(pos.x, -k.z * radius, k.z * radius), radius);
    return length(pos) * sign(pos.y);
}

fn sdf_star(sample_pos: vec2<f32>, center_x: f32, center_y: f32, radius: f32, num_points: f32, inner_ratio: f32) -> f32 {
    let angle_step = 3.141593 / num_points;
    let inner_angle = 3.141593 / inner_ratio;
    let outer_cos_sin = vec2<f32>(cos(angle_step), sin(angle_step));
    let inner_cos_sin = vec2<f32>(cos(inner_angle), sin(inner_angle));
    var pos = sample_pos - vec2<f32>(center_x, center_y);
    let angle = atan2(pos.x, pos.y);
    let normalized_angle = ((angle % (2.0 * angle_step)) + 2.0 * angle_step) % (2.0 * angle_step) - angle_step;
    pos = length(pos) * vec2<f32>(cos(normalized_angle), abs(sin(normalized_angle)));
    pos -= radius * outer_cos_sin;
    pos += inner_cos_sin * clamp(-dot(pos, inner_cos_sin), 0.0, radius * outer_cos_sin.y / inner_cos_sin.y);
    return length(pos) * sign(pos.x);
}

fn sdf_pie(sample_pos: vec2<f32>, center_x: f32, center_y: f32, aperture_x: f32, aperture_y: f32, radius: f32) -> f32 {
    let aperture = vec2<f32>(aperture_x, aperture_y);
    var pos = sample_pos - vec2<f32>(center_x, center_y);
    pos.x = abs(pos.x);
    let l = length(pos) - radius;
    let m = length(pos - aperture * clamp(dot(pos, aperture), 0.0, radius));
    return max(l, m * sign(aperture.y * pos.x - aperture.x * pos.y));
}

fn sdf_ring(sample_pos: vec2<f32>, center_x: f32, center_y: f32, normal_x: f32, normal_y: f32, radius: f32, thickness: f32) -> f32 {
    let normal = vec2<f32>(normal_x, normal_y);
    var pos = sample_pos - vec2<f32>(center_x, center_y);
    pos.x = abs(pos.x);
    pos = mat2x2<f32>(normal.x, normal.y, -normal.y, normal.x) * pos;
    return max(abs(length(pos) - radius) - thickness * 0.5,
               length(vec2<f32>(pos.x, max(0.0, abs(radius - pos.y) - thickness * 0.5))) * sign(pos.x));
}

fn sdf_heart(sample_pos: vec2<f32>, center_x: f32, center_y: f32, scale: f32) -> f32 {
    var pos = (sample_pos - vec2<f32>(center_x, center_y)) / scale;
    pos.x = abs(pos.x);
    if (pos.y + pos.x > 1.0) {
        return (length(pos - vec2<f32>(0.25, 0.75)) - sqrt(2.0) / 4.0) * scale;
    }
    return (sqrt(min(dot(pos - vec2<f32>(0.0, 1.0), pos - vec2<f32>(0.0, 1.0)),
                     dot(pos - 0.5 * max(pos.x + pos.y, 0.0), pos - 0.5 * max(pos.x + pos.y, 0.0)))) *
            sign(pos.x - pos.y)) * scale;
}

fn sdf_cross(sample_pos: vec2<f32>, center_x: f32, center_y: f32, half_width: f32, half_height: f32, corner_radius: f32) -> f32 {
    let half_size = vec2<f32>(half_width, half_height);
    var pos = abs(sample_pos - vec2<f32>(center_x, center_y));
    pos = select(pos, pos.yx, pos.y > pos.x);
    let q = pos - half_size;
    let k = max(q.y, q.x);
    let w = select(vec2<f32>(half_size.y - pos.x, -k), q, k > 0.0);
    return sign(k) * length(max(w, vec2<f32>(0.0))) + corner_radius;
}

fn sdf_rounded_x(sample_pos: vec2<f32>, center_x: f32, center_y: f32, width: f32, radius: f32) -> f32 {
    let pos = abs(sample_pos - vec2<f32>(center_x, center_y));
    return length(pos - min(pos.x + pos.y, width) * 0.5) - radius;
}

fn sdf_capsule(sample_pos: vec2<f32>, start_x: f32, start_y: f32, end_x: f32, end_y: f32, radius: f32) -> f32 {
    let start_point = vec2<f32>(start_x, start_y);
    let end_point = vec2<f32>(end_x, end_y);
    let pos_to_start = sample_pos - start_point;
    let start_to_end = end_point - start_point;
    let t = clamp(dot(pos_to_start, start_to_end) / dot(start_to_end, start_to_end), 0.0, 1.0);
    return length(pos_to_start - start_to_end * t) - radius;
}

fn sdf_moon(sample_pos: vec2<f32>, center_x: f32, center_y: f32, offset: f32, radius_outer: f32, radius_inner: f32) -> f32 {
    var pos = sample_pos - vec2<f32>(center_x, center_y);
    pos.y = abs(pos.y);
    let a = (radius_outer * radius_outer - radius_inner * radius_inner + offset * offset) / (2.0 * offset);
    let b = sqrt(max(radius_outer * radius_outer - a * a, 0.0));
    if (offset * (pos.x * b - pos.y * a) > offset * offset * max(b - pos.y, 0.0)) {
        return length(pos - vec2<f32>(a, b));
    }
    return max(length(pos) - radius_outer, -(length(pos - vec2<f32>(offset, 0.0)) - radius_inner));
}

fn sdf_egg(sample_pos: vec2<f32>, center_x: f32, center_y: f32, radius_outer: f32, radius_inner: f32) -> f32 {
    var pos = sample_pos - vec2<f32>(center_x, center_y);
    pos.x = abs(pos.x);
    let r = radius_outer - radius_inner;
    let k = select((radius_inner * pos.y - radius_outer * pos.x) / (radius_outer * radius_inner), length(pos) / r, pos.y < 0.0);
    if (k < 0.0) { return length(pos) - radius_outer; }
    if (k > radius_outer) { return length(pos - vec2<f32>(0.0, radius_outer)) - radius_inner; }
    return length(pos - vec2<f32>(-r, 0.0)) - (radius_outer + radius_inner - r);
}

fn sdf_octogon(sample_pos: vec2<f32>, center_x: f32, center_y: f32, radius: f32) -> f32 {
    let k = vec3<f32>(-0.9238795325, 0.3826834323, 0.4142135623);
    var pos = abs(sample_pos - vec2<f32>(center_x, center_y));
    pos = pos - 2.0 * min(dot(vec2<f32>(k.x, k.y), pos), 0.0) * vec2<f32>(k.x, k.y);
    pos = pos - 2.0 * min(dot(vec2<f32>(-k.x, k.y), pos), 0.0) * vec2<f32>(-k.x, k.y);
    pos = pos - vec2<f32>(clamp(pos.x, -k.z * radius, k.z * radius), radius);
    return length(pos) * sign(pos.y);
}

fn sdf_hexagram(sample_pos: vec2<f32>, center_x: f32, center_y: f32, radius: f32) -> f32 {
    let k = vec4<f32>(-0.5, 0.8660254038, 0.5773502692, 1.7320508076);
    var pos = abs(sample_pos - vec2<f32>(center_x, center_y));
    pos = pos - 2.0 * min(dot(k.xy, pos), 0.0) * k.xy;
    pos = pos - 2.0 * min(dot(k.yx, pos), 0.0) * k.yx;
    pos = pos - vec2<f32>(clamp(pos.x, radius * k.z, radius * k.w), radius);
    return length(pos) * sign(pos.y);
}

fn sdf_pentagram(sample_pos: vec2<f32>, center_x: f32, center_y: f32, radius: f32) -> f32 {
    let v1 = vec2<f32>(0.809016994, -0.587785252);
    let v2 = vec2<f32>(-0.809016994, -0.587785252);
    let v3 = vec2<f32>(0.309016994, -0.951056516);
    let k1z = 0.726542528;
    var pos = sample_pos - vec2<f32>(center_x, center_y);
    pos.x = abs(pos.x);
    pos = pos - 2.0 * max(dot(v1, pos), 0.0) * v1;
    pos = pos - 2.0 * max(dot(v2, pos), 0.0) * v2;
    pos.x = abs(pos.x);
    pos.y = pos.y - radius;
    return length(pos - v3 * clamp(dot(pos, v3), 0.0, k1z * radius)) * sign(pos.y * v3.x - pos.x * v3.y);
}

fn sdf_sphere_3d(sample_pos: vec3<f32>, position_x: f32, position_y: f32, position_z: f32, radius: f32) -> f32 {
    return length(sample_pos - vec3<f32>(position_x, position_y, position_z)) - radius;
}

fn sdf_box_3d(sample_pos: vec3<f32>, position_x: f32, position_y: f32, position_z: f32, half_size_x: f32, half_size_y: f32, half_size_z: f32) -> f32 {
    let q = abs(sample_pos - vec3<f32>(position_x, position_y, position_z)) - vec3<f32>(half_size_x, half_size_y, half_size_z);
    return length(max(q, vec3<f32>(0.0))) + min(max(q.x, max(q.y, q.z)), 0.0);
}

fn sdf_torus_3d(sample_pos: vec3<f32>, position_x: f32, position_y: f32, position_z: f32, major_radius: f32, minor_radius: f32) -> f32 {
    let pos = sample_pos - vec3<f32>(position_x, position_y, position_z);
    let q = vec2<f32>(length(pos.xz) - major_radius, pos.y);
    return length(q) - minor_radius;
}

fn sdf_cylinder_3d(sample_pos: vec3<f32>, position_x: f32, position_y: f32, position_z: f32, radius: f32, half_height: f32) -> f32 {
    let pos = sample_pos - vec3<f32>(position_x, position_y, position_z);
    let d = abs(vec2<f32>(length(pos.xz), pos.y)) - vec2<f32>(radius, half_height);
    return min(max(d.x, d.y), 0.0) + length(max(d, vec2<f32>(0.0)));
}

fn evaluate_sdf_2d(prim_offset: u32, sample_pos: vec2<f32>) -> f32 {
    let prim_type = bitcast<u32>(buf[prim_offset]);
    switch (prim_type) {
        case 0u: { return sdf_circle(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u]); }
        case 1u: { return sdf_box(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u], buf[prim_offset + 9u]); }
        case 2u: { return sdf_segment(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u]); }
        case 3u: { return sdf_triangle(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u], buf[prim_offset + 9u], buf[prim_offset + 10u]); }
        case 6u: { return sdf_ellipse(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u]); }
        case 7u: { return sdf_arc(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u], buf[prim_offset + 9u], buf[prim_offset + 10u]); }
        case 8u: { return sdf_rounded_box(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u], buf[prim_offset + 9u], buf[prim_offset + 10u], buf[prim_offset + 11u], buf[prim_offset + 12u]); }
        case 9u: { return sdf_rhombus(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u]); }
        case 10u: { return sdf_pentagon(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u]); }
        case 11u: { return sdf_hexagon(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u]); }
        case 12u: { return sdf_star(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u], buf[prim_offset + 9u]); }
        case 13u: { return sdf_pie(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u], buf[prim_offset + 9u]); }
        case 14u: { return sdf_ring(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u], buf[prim_offset + 9u], buf[prim_offset + 10u]); }
        case 15u: { return sdf_heart(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u]); }
        case 16u: { return sdf_cross(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u], buf[prim_offset + 9u]); }
        case 17u: { return sdf_rounded_x(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u]); }
        case 18u: { return sdf_capsule(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u], buf[prim_offset + 9u]); }
        case 19u: { return sdf_moon(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u], buf[prim_offset + 9u]); }
        case 20u: { return sdf_egg(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u]); }
        case 28u: { return sdf_octogon(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u]); }
        case 29u: { return sdf_hexagram(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u]); }
        case 30u: { return sdf_pentagram(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u]); }
        default: { return 1e10; }
    }
}

fn evaluate_sdf_3d(prim_offset: u32, sample_pos: vec3<f32>) -> f32 {
    let prim_type = bitcast<u32>(buf[prim_offset]);
    switch (prim_type) {
        case 100u: { return sdf_sphere_3d(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u]); }
        case 101u: { return sdf_box_3d(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u], buf[prim_offset + 9u], buf[prim_offset + 10u]); }
        case 103u: { return sdf_torus_3d(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u], buf[prim_offset + 9u]); }
        case 105u: { return sdf_cylinder_3d(sample_pos, buf[prim_offset + 5u], buf[prim_offset + 6u], buf[prim_offset + 7u], buf[prim_offset + 8u], buf[prim_offset + 9u]); }
        default: { return 1e10; }
    }
}

fn get_sdf_prim_style(prim_offset: u32) -> vec3<u32> {
    return vec3<u32>(
        bitcast<u32>(buf[prim_offset + 2u]),  // fill_color
        bitcast<u32>(buf[prim_offset + 3u]),  // stroke_color
        bitcast<u32>(buf[prim_offset + 4u])   // stroke_width as bits
    );
}