// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ypaint/sdf/gen-sdf-code.py


#include <yetty/ypaint/yaml/ypaint-yaml.gen.h>
#include <yetty/ysdf/types.gen.h>
#include <yetty/ypaint/core/ypaint-buffer.h>
#include <yetty/ytrace.h>
#include <yaml.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/*=============================================================================
 * Helpers
 *===========================================================================*/

static uint32_t parse_color(const char *str) {
    if (!str || !*str) return 0;
    if (str[0] == '#') str++;
    size_t len = strlen(str);
    char buf[9] = {0};
    if (len == 3) {
        buf[0] = buf[1] = str[0]; buf[2] = buf[3] = str[1]; buf[4] = buf[5] = str[2]; buf[6] = buf[7] = 'F';
    } else if (len == 6) {
        memcpy(buf, str, 6); buf[6] = buf[7] = 'F';
    } else if (len == 8) {
        memcpy(buf, str, 8);
    } else return 0;
    char *end;
    unsigned long v = strtoul(buf, &end, 16);
    if (*end) return 0;
    uint32_t r = (v >> 24) & 0xFF, g = (v >> 16) & 0xFF, b = (v >> 8) & 0xFF, a = v & 0xFF;
    return (a << 24) | (b << 16) | (g << 8) | r;
}

/*=============================================================================
 * Parser context
 *===========================================================================*/

struct ypaint_yaml_parse_ctx {
    struct ypaint_canvas *canvas;
    struct yetty_ypaint_buffer *buffer;
    uint32_t z_order;
    /* Current primitive state */
    char prim_type[32];
    char prop_key[32];
    uint32_t fill_color;
    uint32_t stroke_color;
    float stroke_width;
    float aperture_x;
    float aperture_y;
    float center_x;
    float center_y;
    float corner_radius;
    float end_x;
    float end_y;
    float half_height;
    float half_width;
    float inner_ratio;
    float normal_x;
    float normal_y;
    float num_points;
    float offset;
    float radius;
    float radius_bottom_left;
    float radius_bottom_right;
    float radius_inner;
    float radius_outer;
    float radius_top_left;
    float radius_top_right;
    float radius_x;
    float radius_y;
    float scale;
    float start_x;
    float start_y;
    float thickness;
    float vertex_a_x;
    float vertex_a_y;
    float vertex_b_x;
    float vertex_b_y;
    float vertex_c_x;
    float vertex_c_y;
    float width;
    /* Array parsing state */
    int in_array;
    int array_idx;
    float array_vals[8];
};

static void reset_prim(struct ypaint_yaml_parse_ctx *yaml_parse_ctx) {
    yaml_parse_ctx->prim_type[0] = 0;
    yaml_parse_ctx->prop_key[0] = 0;
    yaml_parse_ctx->fill_color = 0;
    yaml_parse_ctx->stroke_color = 0;
    yaml_parse_ctx->stroke_width = 0;
    yaml_parse_ctx->aperture_x = 0;
    yaml_parse_ctx->aperture_y = 0;
    yaml_parse_ctx->center_x = 0;
    yaml_parse_ctx->center_y = 0;
    yaml_parse_ctx->corner_radius = 0;
    yaml_parse_ctx->end_x = 0;
    yaml_parse_ctx->end_y = 0;
    yaml_parse_ctx->half_height = 0;
    yaml_parse_ctx->half_width = 0;
    yaml_parse_ctx->inner_ratio = 0;
    yaml_parse_ctx->normal_x = 0;
    yaml_parse_ctx->normal_y = 0;
    yaml_parse_ctx->num_points = 0;
    yaml_parse_ctx->offset = 0;
    yaml_parse_ctx->radius = 0;
    yaml_parse_ctx->radius_bottom_left = 0;
    yaml_parse_ctx->radius_bottom_right = 0;
    yaml_parse_ctx->radius_inner = 0;
    yaml_parse_ctx->radius_outer = 0;
    yaml_parse_ctx->radius_top_left = 0;
    yaml_parse_ctx->radius_top_right = 0;
    yaml_parse_ctx->radius_x = 0;
    yaml_parse_ctx->radius_y = 0;
    yaml_parse_ctx->scale = 0;
    yaml_parse_ctx->start_x = 0;
    yaml_parse_ctx->start_y = 0;
    yaml_parse_ctx->thickness = 0;
    yaml_parse_ctx->vertex_a_x = 0;
    yaml_parse_ctx->vertex_a_y = 0;
    yaml_parse_ctx->vertex_b_x = 0;
    yaml_parse_ctx->vertex_b_y = 0;
    yaml_parse_ctx->vertex_c_x = 0;
    yaml_parse_ctx->vertex_c_y = 0;
    yaml_parse_ctx->width = 0;
    yaml_parse_ctx->in_array = 0;
    yaml_parse_ctx->array_idx = 0;
}

static void store_array(struct ypaint_yaml_parse_ctx *yaml_parse_ctx) {
    const char *key = yaml_parse_ctx->prop_key;
    ydebug("store_array: key='%s' idx=%d vals=[%f,%f]", key, yaml_parse_ctx->array_idx, yaml_parse_ctx->array_vals[0], yaml_parse_ctx->array_vals[1]);
    if (strcmp(key, "position") == 0 && yaml_parse_ctx->array_idx >= 2) {
        yaml_parse_ctx->center_x = yaml_parse_ctx->array_vals[0]; yaml_parse_ctx->center_y = yaml_parse_ctx->array_vals[1];
        ydebug("store_array: set center_x=%f center_y=%f", yaml_parse_ctx->center_x, yaml_parse_ctx->center_y);
    }
    else if (strcmp(key, "size") == 0 && yaml_parse_ctx->array_idx >= 2) {
        yaml_parse_ctx->half_width = yaml_parse_ctx->array_vals[0] / 2.0f; yaml_parse_ctx->half_height = yaml_parse_ctx->array_vals[1] / 2.0f;
    }
    else if (strcmp(key, "start") == 0 && yaml_parse_ctx->array_idx >= 2) {
        yaml_parse_ctx->start_x = yaml_parse_ctx->array_vals[0]; yaml_parse_ctx->start_y = yaml_parse_ctx->array_vals[1];
    }
    else if (strcmp(key, "end") == 0 && yaml_parse_ctx->array_idx >= 2) {
        yaml_parse_ctx->end_x = yaml_parse_ctx->array_vals[0]; yaml_parse_ctx->end_y = yaml_parse_ctx->array_vals[1];
    }
    else if (strcmp(key, "vertex_a") == 0 && yaml_parse_ctx->array_idx >= 2) {
        yaml_parse_ctx->vertex_a_x = yaml_parse_ctx->array_vals[0]; yaml_parse_ctx->vertex_a_y = yaml_parse_ctx->array_vals[1];
    }
    else if (strcmp(key, "vertex_b") == 0 && yaml_parse_ctx->array_idx >= 2) {
        yaml_parse_ctx->vertex_b_x = yaml_parse_ctx->array_vals[0]; yaml_parse_ctx->vertex_b_y = yaml_parse_ctx->array_vals[1];
    }
    else if (strcmp(key, "vertex_c") == 0 && yaml_parse_ctx->array_idx >= 2) {
        yaml_parse_ctx->vertex_c_x = yaml_parse_ctx->array_vals[0]; yaml_parse_ctx->vertex_c_y = yaml_parse_ctx->array_vals[1];
    }
    else if (strcmp(key, "radii") == 0 && yaml_parse_ctx->array_idx >= 2) {
        yaml_parse_ctx->radius_x = yaml_parse_ctx->array_vals[0]; yaml_parse_ctx->radius_y = yaml_parse_ctx->array_vals[1];
    }
    else if (strcmp(key, "aperture") == 0 && yaml_parse_ctx->array_idx >= 2) {
        yaml_parse_ctx->aperture_x = yaml_parse_ctx->array_vals[0]; yaml_parse_ctx->aperture_y = yaml_parse_ctx->array_vals[1];
    }
    else if (strcmp(key, "normal") == 0 && yaml_parse_ctx->array_idx >= 2) {
        yaml_parse_ctx->normal_x = yaml_parse_ctx->array_vals[0]; yaml_parse_ctx->normal_y = yaml_parse_ctx->array_vals[1];
    }
}

static void add_prim(struct ypaint_yaml_parse_ctx *yaml_parse_ctx) {
    float data[16];
    uint32_t word_count = 0, tmp;

    ydebug("add_prim: type='%s' center_x=%f center_y=%f radius=%f fill=0x%08x", yaml_parse_ctx->prim_type, yaml_parse_ctx->center_x, yaml_parse_ctx->center_y, yaml_parse_ctx->radius, yaml_parse_ctx->fill_color);

    if (strcmp(yaml_parse_ctx->prim_type, "circle") == 0) {
        tmp = YPAINT_SDF_CIRCLE; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->radius;
        word_count = 8;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "box") == 0) {
        tmp = YPAINT_SDF_BOX; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->half_width;
        data[8] = yaml_parse_ctx->half_height;
        data[9] = yaml_parse_ctx->corner_radius;
        word_count = 10;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "segment") == 0) {
        tmp = YPAINT_SDF_SEGMENT; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->start_x;
        data[6] = yaml_parse_ctx->start_y;
        data[7] = yaml_parse_ctx->end_x;
        data[8] = yaml_parse_ctx->end_y;
        word_count = 9;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "triangle") == 0) {
        tmp = YPAINT_SDF_TRIANGLE; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->vertex_a_x;
        data[6] = yaml_parse_ctx->vertex_a_y;
        data[7] = yaml_parse_ctx->vertex_b_x;
        data[8] = yaml_parse_ctx->vertex_b_y;
        data[9] = yaml_parse_ctx->vertex_c_x;
        data[10] = yaml_parse_ctx->vertex_c_y;
        word_count = 11;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "ellipse") == 0) {
        tmp = YPAINT_SDF_ELLIPSE; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->radius_x;
        data[8] = yaml_parse_ctx->radius_y;
        word_count = 9;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "arc") == 0) {
        tmp = YPAINT_SDF_ARC; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->aperture_x;
        data[8] = yaml_parse_ctx->aperture_y;
        data[9] = yaml_parse_ctx->radius;
        data[10] = yaml_parse_ctx->thickness;
        word_count = 11;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "rounded_box") == 0) {
        tmp = YPAINT_SDF_ROUNDED_BOX; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->half_width;
        data[8] = yaml_parse_ctx->half_height;
        data[9] = yaml_parse_ctx->radius_top_right;
        data[10] = yaml_parse_ctx->radius_bottom_right;
        data[11] = yaml_parse_ctx->radius_top_left;
        data[12] = yaml_parse_ctx->radius_bottom_left;
        word_count = 13;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "rhombus") == 0) {
        tmp = YPAINT_SDF_RHOMBUS; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->half_width;
        data[8] = yaml_parse_ctx->half_height;
        word_count = 9;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "pentagon") == 0) {
        tmp = YPAINT_SDF_PENTAGON; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->radius;
        word_count = 8;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "hexagon") == 0) {
        tmp = YPAINT_SDF_HEXAGON; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->radius;
        word_count = 8;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "star") == 0) {
        tmp = YPAINT_SDF_STAR; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->radius;
        data[8] = yaml_parse_ctx->num_points;
        data[9] = yaml_parse_ctx->inner_ratio;
        word_count = 10;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "pie") == 0) {
        tmp = YPAINT_SDF_PIE; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->aperture_x;
        data[8] = yaml_parse_ctx->aperture_y;
        data[9] = yaml_parse_ctx->radius;
        word_count = 10;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "ring") == 0) {
        tmp = YPAINT_SDF_RING; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->normal_x;
        data[8] = yaml_parse_ctx->normal_y;
        data[9] = yaml_parse_ctx->radius;
        data[10] = yaml_parse_ctx->thickness;
        word_count = 11;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "heart") == 0) {
        tmp = YPAINT_SDF_HEART; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->scale;
        word_count = 8;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "cross") == 0) {
        tmp = YPAINT_SDF_CROSS; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->half_width;
        data[8] = yaml_parse_ctx->half_height;
        data[9] = yaml_parse_ctx->corner_radius;
        word_count = 10;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "rounded_x") == 0) {
        tmp = YPAINT_SDF_ROUNDED_X; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->width;
        data[8] = yaml_parse_ctx->radius;
        word_count = 9;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "capsule") == 0) {
        tmp = YPAINT_SDF_CAPSULE; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->start_x;
        data[6] = yaml_parse_ctx->start_y;
        data[7] = yaml_parse_ctx->end_x;
        data[8] = yaml_parse_ctx->end_y;
        data[9] = yaml_parse_ctx->radius;
        word_count = 10;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "moon") == 0) {
        tmp = YPAINT_SDF_MOON; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->offset;
        data[8] = yaml_parse_ctx->radius_outer;
        data[9] = yaml_parse_ctx->radius_inner;
        word_count = 10;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "egg") == 0) {
        tmp = YPAINT_SDF_EGG; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->radius_outer;
        data[8] = yaml_parse_ctx->radius_inner;
        word_count = 9;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "octogon") == 0) {
        tmp = YPAINT_SDF_OCTOGON; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->radius;
        word_count = 8;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "hexagram") == 0) {
        tmp = YPAINT_SDF_HEXAGRAM; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->radius;
        word_count = 8;
    }
    else if (strcmp(yaml_parse_ctx->prim_type, "pentagram") == 0) {
        tmp = YPAINT_SDF_PENTAGRAM; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->z_order; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = yaml_parse_ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = yaml_parse_ctx->stroke_width;
        data[5] = yaml_parse_ctx->center_x;
        data[6] = yaml_parse_ctx->center_y;
        data[7] = yaml_parse_ctx->radius;
        word_count = 8;
    }
    else {
        ydebug("ypaint_yaml: unknown type '%s'", yaml_parse_ctx->prim_type);
        yaml_parse_ctx->z_order++;
        return;
    }

    /* Add primitive to buffer */
    yetty_ypaint_buffer_add_prim(yaml_parse_ctx->buffer, data, word_count);
    yaml_parse_ctx->z_order++;
}

/*=============================================================================
 * YAML event parser
 *===========================================================================*/

int ypaint_sdf_yaml_parse(struct ypaint_canvas *canvas, const char *yaml_str, size_t yaml_len) {
    yaml_parser_t parser;
    yaml_event_t event;
    struct ypaint_yaml_parse_ctx yaml_parse_ctx = {0};
    int done = 0, err = 0;
    int depth = 0;       /* mapping depth */
    int in_body = 0;     /* inside body sequence */
    int in_prim = 0;     /* inside primitive map */
    int in_prim_type = 0;/* inside primitive type map */
    int expect_value = 0;

    if (!canvas || !yaml_str) return -1;

    /* Create buffer for primitives */
    yaml_parse_ctx.buffer = yetty_ypaint_buffer_create();
    if (!yaml_parse_ctx.buffer) return -1;
    yaml_parse_ctx.canvas = canvas;

    if (!yaml_parser_initialize(&parser)) return -1;
    yaml_parser_set_input_string(&parser, (const unsigned char *)yaml_str, yaml_len);

    while (!done && !err) {
        if (!yaml_parser_parse(&parser, &event)) { err = 1; break; }
        switch (event.type) {
        case YAML_STREAM_END_EVENT: done = 1; break;
        case YAML_MAPPING_START_EVENT:
            depth++;
            if (in_body && !in_prim) { in_prim = 1; reset_prim(&yaml_parse_ctx); }
            else if (in_prim && !in_prim_type) { in_prim_type = 1; }
            break;
        case YAML_MAPPING_END_EVENT:
            if (in_prim_type) { add_prim(&yaml_parse_ctx); in_prim_type = 0; in_prim = 0; }
            depth--;
            break;
        case YAML_SEQUENCE_START_EVENT:
            if (depth == 1 && strcmp(yaml_parse_ctx.prop_key, "body") == 0) { in_body = 1; }
            else if (in_prim_type) { yaml_parse_ctx.in_array = 1; yaml_parse_ctx.array_idx = 0; expect_value = 0; }
            break;
        case YAML_SEQUENCE_END_EVENT:
            if (yaml_parse_ctx.in_array) { store_array(&yaml_parse_ctx); yaml_parse_ctx.in_array = 0; }
            else if (in_body && !in_prim) { in_body = 0; }
            break;
        case YAML_SCALAR_EVENT: {
            const char *scalar_value = (const char *)event.data.scalar.value;
            if (yaml_parse_ctx.in_array) {
                if (yaml_parse_ctx.array_idx < 8) yaml_parse_ctx.array_vals[yaml_parse_ctx.array_idx++] = strtof(scalar_value, NULL);
            } else if (in_prim && !in_prim_type) {
                strncpy(yaml_parse_ctx.prim_type, scalar_value, sizeof(yaml_parse_ctx.prim_type)-1);
            } else if (in_prim_type) {
                if (!expect_value) {
                    strncpy(yaml_parse_ctx.prop_key, scalar_value, sizeof(yaml_parse_ctx.prop_key)-1);
                    expect_value = 1;
                } else {
                    if (strcmp(yaml_parse_ctx.prop_key, "fill") == 0) yaml_parse_ctx.fill_color = parse_color(scalar_value);
                    else if (strcmp(yaml_parse_ctx.prop_key, "stroke") == 0) yaml_parse_ctx.stroke_color = parse_color(scalar_value);
                    else if (strcmp(yaml_parse_ctx.prop_key, "stroke_width") == 0) yaml_parse_ctx.stroke_width = strtof(scalar_value, NULL);
                    else if (strcmp(yaml_parse_ctx.prop_key, "radius") == 0) yaml_parse_ctx.radius = strtof(scalar_value, NULL);
                    else if (strcmp(yaml_parse_ctx.prop_key, "corner_radius") == 0) yaml_parse_ctx.corner_radius = strtof(scalar_value, NULL);
                    else if (strcmp(yaml_parse_ctx.prop_key, "scale") == 0) yaml_parse_ctx.scale = strtof(scalar_value, NULL);
                    else if (strcmp(yaml_parse_ctx.prop_key, "num_points") == 0) yaml_parse_ctx.num_points = strtof(scalar_value, NULL);
                    else if (strcmp(yaml_parse_ctx.prop_key, "inner_ratio") == 0) yaml_parse_ctx.inner_ratio = strtof(scalar_value, NULL);
                    else if (strcmp(yaml_parse_ctx.prop_key, "thickness") == 0) yaml_parse_ctx.thickness = strtof(scalar_value, NULL);
                    else if (strcmp(yaml_parse_ctx.prop_key, "offset") == 0) yaml_parse_ctx.offset = strtof(scalar_value, NULL);
                    else if (strcmp(yaml_parse_ctx.prop_key, "width") == 0) yaml_parse_ctx.width = strtof(scalar_value, NULL);
                    else if (strcmp(yaml_parse_ctx.prop_key, "radius_outer") == 0) yaml_parse_ctx.radius_outer = strtof(scalar_value, NULL);
                    else if (strcmp(yaml_parse_ctx.prop_key, "radius_inner") == 0) yaml_parse_ctx.radius_inner = strtof(scalar_value, NULL);
                    expect_value = 0;
                }
            } else if (depth == 1) {
                strncpy(yaml_parse_ctx.prop_key, scalar_value, sizeof(yaml_parse_ctx.prop_key)-1);
            }
            break;
        }
        default: break;
        }
        yaml_event_delete(&event);
    }
    yaml_parser_delete(&parser);

    /* Add buffer to canvas (handles scrolling) */
    if (!err && yaml_parse_ctx.buffer->prims.buf.size > 0) {
        ypaint_canvas_add_buffer(yaml_parse_ctx.canvas, yaml_parse_ctx.buffer);
    }

    yetty_ypaint_buffer_destroy(yaml_parse_ctx.buffer);
    ydebug("ypaint_yaml: parsed %u primitives", yaml_parse_ctx.z_order);
    return err ? -1 : 0;
}