// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ysdf/gen-sdf-code.py


#include <yetty/ysdf/yaml-factory.gen.h>
#include <yetty/ysdf/types.gen.h>
#include <yetty/ypaint-core/buffer.h>
#include <yetty/ypaint-yaml/ypaint-yaml.h>
#include <yetty/ytrace.h>
#include <yaml.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/*=============================================================================
 * Helpers
 *===========================================================================*/

static uint32_t parse_color(const char *str) {
    if (!str || !*str) return 0;
    if (str[0] == '#') str++;
    size_t len = strlen(str);
    char buf[9] = {0};
    if (len == 3) {
        buf[0] = buf[1] = str[0]; buf[2] = buf[3] = str[1]; buf[4] = buf[5] = str[2]; buf[6] = buf[7] = 'F';
    } else if (len == 6) {
        memcpy(buf, str, 6); buf[6] = buf[7] = 'F';
    } else if (len == 8) {
        memcpy(buf, str, 8);
    } else return 0;
    char *end;
    unsigned long v = strtoul(buf, &end, 16);
    if (*end) return 0;
    uint32_t r = (v >> 24) & 0xFF, g = (v >> 16) & 0xFF, b = (v >> 8) & 0xFF, a = v & 0xFF;
    return (a << 24) | (b << 16) | (g << 8) | r;
}

/*=============================================================================
 * Parse context
 *===========================================================================*/

struct ysdf_parse_ctx {
    char prop_key[32];
    uint32_t fill_color;
    uint32_t stroke_color;
    float stroke_width;
    float aperture_x;
    float aperture_y;
    float center_x;
    float center_y;
    float corner_radius;
    float end_x;
    float end_y;
    float half_height;
    float half_width;
    float inner_ratio;
    float normal_x;
    float normal_y;
    float num_points;
    float offset;
    float radius;
    float radius_bottom_left;
    float radius_bottom_right;
    float radius_inner;
    float radius_outer;
    float radius_top_left;
    float radius_top_right;
    float radius_x;
    float radius_y;
    float scale;
    float start_x;
    float start_y;
    float thickness;
    float vertex_a_x;
    float vertex_a_y;
    float vertex_b_x;
    float vertex_b_y;
    float vertex_c_x;
    float vertex_c_y;
    float width;
    int in_array;
    int array_idx;
    float array_vals[8];
};

static void store_array(struct ysdf_parse_ctx *ctx) {
    const char *key = ctx->prop_key;
    if (strcmp(key, "position") == 0 && ctx->array_idx >= 2) {
        ctx->center_x = ctx->array_vals[0]; ctx->center_y = ctx->array_vals[1];
    }
    else if (strcmp(key, "size") == 0 && ctx->array_idx >= 2) {
        ctx->half_width = ctx->array_vals[0] / 2.0f; ctx->half_height = ctx->array_vals[1] / 2.0f;
    }
    else if (strcmp(key, "start") == 0 && ctx->array_idx >= 2) {
        ctx->start_x = ctx->array_vals[0]; ctx->start_y = ctx->array_vals[1];
    }
    else if (strcmp(key, "end") == 0 && ctx->array_idx >= 2) {
        ctx->end_x = ctx->array_vals[0]; ctx->end_y = ctx->array_vals[1];
    }
    else if (strcmp(key, "vertex_a") == 0 && ctx->array_idx >= 2) {
        ctx->vertex_a_x = ctx->array_vals[0]; ctx->vertex_a_y = ctx->array_vals[1];
    }
    else if (strcmp(key, "vertex_b") == 0 && ctx->array_idx >= 2) {
        ctx->vertex_b_x = ctx->array_vals[0]; ctx->vertex_b_y = ctx->array_vals[1];
    }
    else if (strcmp(key, "vertex_c") == 0 && ctx->array_idx >= 2) {
        ctx->vertex_c_x = ctx->array_vals[0]; ctx->vertex_c_y = ctx->array_vals[1];
    }
    else if (strcmp(key, "radii") == 0 && ctx->array_idx >= 2) {
        ctx->radius_x = ctx->array_vals[0]; ctx->radius_y = ctx->array_vals[1];
    }
    else if (strcmp(key, "aperture") == 0 && ctx->array_idx >= 2) {
        ctx->aperture_x = ctx->array_vals[0]; ctx->aperture_y = ctx->array_vals[1];
    }
    else if (strcmp(key, "normal") == 0 && ctx->array_idx >= 2) {
        ctx->normal_x = ctx->array_vals[0]; ctx->normal_y = ctx->array_vals[1];
    }
}

static void build_prim(struct yetty_ypaint_core_buffer *buffer,
                       const char *primitive_type_name,
                       struct ysdf_parse_ctx *ctx) {
    float data[16];
    uint32_t word_count = 0, tmp;
    static uint32_t z_order = 0;

    if (strcmp(primitive_type_name, "circle") == 0) {
        tmp = YETTY_YSDF_CIRCLE; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->radius;
        word_count = 8;
    }
    else if (strcmp(primitive_type_name, "box") == 0) {
        tmp = YETTY_YSDF_BOX; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->half_width;
        data[8] = ctx->half_height;
        data[9] = ctx->corner_radius;
        word_count = 10;
    }
    else if (strcmp(primitive_type_name, "segment") == 0) {
        tmp = YETTY_YSDF_SEGMENT; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->start_x;
        data[6] = ctx->start_y;
        data[7] = ctx->end_x;
        data[8] = ctx->end_y;
        word_count = 9;
    }
    else if (strcmp(primitive_type_name, "triangle") == 0) {
        tmp = YETTY_YSDF_TRIANGLE; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->vertex_a_x;
        data[6] = ctx->vertex_a_y;
        data[7] = ctx->vertex_b_x;
        data[8] = ctx->vertex_b_y;
        data[9] = ctx->vertex_c_x;
        data[10] = ctx->vertex_c_y;
        word_count = 11;
    }
    else if (strcmp(primitive_type_name, "ellipse") == 0) {
        tmp = YETTY_YSDF_ELLIPSE; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->radius_x;
        data[8] = ctx->radius_y;
        word_count = 9;
    }
    else if (strcmp(primitive_type_name, "arc") == 0) {
        tmp = YETTY_YSDF_ARC; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->aperture_x;
        data[8] = ctx->aperture_y;
        data[9] = ctx->radius;
        data[10] = ctx->thickness;
        word_count = 11;
    }
    else if (strcmp(primitive_type_name, "rounded_box") == 0) {
        tmp = YETTY_YSDF_ROUNDED_BOX; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->half_width;
        data[8] = ctx->half_height;
        data[9] = ctx->radius_top_right;
        data[10] = ctx->radius_bottom_right;
        data[11] = ctx->radius_top_left;
        data[12] = ctx->radius_bottom_left;
        word_count = 13;
    }
    else if (strcmp(primitive_type_name, "rhombus") == 0) {
        tmp = YETTY_YSDF_RHOMBUS; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->half_width;
        data[8] = ctx->half_height;
        word_count = 9;
    }
    else if (strcmp(primitive_type_name, "pentagon") == 0) {
        tmp = YETTY_YSDF_PENTAGON; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->radius;
        word_count = 8;
    }
    else if (strcmp(primitive_type_name, "hexagon") == 0) {
        tmp = YETTY_YSDF_HEXAGON; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->radius;
        word_count = 8;
    }
    else if (strcmp(primitive_type_name, "star") == 0) {
        tmp = YETTY_YSDF_STAR; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->radius;
        data[8] = ctx->num_points;
        data[9] = ctx->inner_ratio;
        word_count = 10;
    }
    else if (strcmp(primitive_type_name, "pie") == 0) {
        tmp = YETTY_YSDF_PIE; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->aperture_x;
        data[8] = ctx->aperture_y;
        data[9] = ctx->radius;
        word_count = 10;
    }
    else if (strcmp(primitive_type_name, "ring") == 0) {
        tmp = YETTY_YSDF_RING; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->normal_x;
        data[8] = ctx->normal_y;
        data[9] = ctx->radius;
        data[10] = ctx->thickness;
        word_count = 11;
    }
    else if (strcmp(primitive_type_name, "heart") == 0) {
        tmp = YETTY_YSDF_HEART; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->scale;
        word_count = 8;
    }
    else if (strcmp(primitive_type_name, "cross") == 0) {
        tmp = YETTY_YSDF_CROSS; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->half_width;
        data[8] = ctx->half_height;
        data[9] = ctx->corner_radius;
        word_count = 10;
    }
    else if (strcmp(primitive_type_name, "rounded_x") == 0) {
        tmp = YETTY_YSDF_ROUNDED_X; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->width;
        data[8] = ctx->radius;
        word_count = 9;
    }
    else if (strcmp(primitive_type_name, "capsule") == 0) {
        tmp = YETTY_YSDF_CAPSULE; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->start_x;
        data[6] = ctx->start_y;
        data[7] = ctx->end_x;
        data[8] = ctx->end_y;
        data[9] = ctx->radius;
        word_count = 10;
    }
    else if (strcmp(primitive_type_name, "moon") == 0) {
        tmp = YETTY_YSDF_MOON; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->offset;
        data[8] = ctx->radius_outer;
        data[9] = ctx->radius_inner;
        word_count = 10;
    }
    else if (strcmp(primitive_type_name, "egg") == 0) {
        tmp = YETTY_YSDF_EGG; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->radius_outer;
        data[8] = ctx->radius_inner;
        word_count = 9;
    }
    else if (strcmp(primitive_type_name, "octogon") == 0) {
        tmp = YETTY_YSDF_OCTOGON; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->radius;
        word_count = 8;
    }
    else if (strcmp(primitive_type_name, "hexagram") == 0) {
        tmp = YETTY_YSDF_HEXAGRAM; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->radius;
        word_count = 8;
    }
    else if (strcmp(primitive_type_name, "pentagram") == 0) {
        tmp = YETTY_YSDF_PENTAGRAM; memcpy(&data[0], &tmp, sizeof(tmp));
        tmp = z_order++; memcpy(&data[1], &tmp, sizeof(tmp));
        tmp = ctx->fill_color; memcpy(&data[2], &tmp, sizeof(tmp));
        tmp = ctx->stroke_color; memcpy(&data[3], &tmp, sizeof(tmp));
        data[4] = ctx->stroke_width;
        data[5] = ctx->center_x;
        data[6] = ctx->center_y;
        data[7] = ctx->radius;
        word_count = 8;
    }
    else {
        return;
    }

    if (word_count > 0)
        yetty_ypaint_core_buffer_add_prim(buffer, data, word_count * sizeof(float));
}

/*=============================================================================
 * Factory
 *===========================================================================*/

struct yetty_core_void_result
yetty_ysdf_yaml_factory(struct yetty_ypaint_core_buffer *buffer,
                        yaml_parser_t *yaml_parser,
                        const char *primitive_type_name) {
    struct ysdf_parse_ctx ctx = {0};
    yaml_event_t event;
    int depth = 0;
    int expect_value = 0;
    int done = 0;

    while (!done) {
        if (!yaml_parser_parse(yaml_parser, &event))
            return YETTY_ERR(yetty_core_void, "yaml parse error");

        switch (event.type) {
        case YAML_MAPPING_START_EVENT:
            depth++;
            break;
        case YAML_MAPPING_END_EVENT:
            depth--;
            if (depth == 0) done = 1;
            break;
        case YAML_SEQUENCE_START_EVENT:
            ctx.in_array = 1;
            ctx.array_idx = 0;
            break;
        case YAML_SEQUENCE_END_EVENT:
            store_array(&ctx);
            ctx.in_array = 0;
            expect_value = 0;
            break;
        case YAML_SCALAR_EVENT: {
            const char *val = (const char *)event.data.scalar.value;
            if (ctx.in_array) {
                if (ctx.array_idx < 8)
                    ctx.array_vals[ctx.array_idx++] = strtof(val, NULL);
            } else if (!expect_value) {
                strncpy(ctx.prop_key, val, sizeof(ctx.prop_key) - 1);
                expect_value = 1;
            } else {
                if (strcmp(ctx.prop_key, "fill") == 0)
                    ctx.fill_color = parse_color(val);
                else if (strcmp(ctx.prop_key, "stroke") == 0)
                    ctx.stroke_color = parse_color(val);
                else if (strcmp(ctx.prop_key, "stroke_width") == 0)
                    ctx.stroke_width = strtof(val, NULL);
                else if (strcmp(ctx.prop_key, "radius") == 0)
                    ctx.radius = strtof(val, NULL);
                else if (strcmp(ctx.prop_key, "corner_radius") == 0)
                    ctx.corner_radius = strtof(val, NULL);
                else if (strcmp(ctx.prop_key, "scale") == 0)
                    ctx.scale = strtof(val, NULL);
                else if (strcmp(ctx.prop_key, "num_points") == 0)
                    ctx.num_points = strtof(val, NULL);
                else if (strcmp(ctx.prop_key, "inner_ratio") == 0)
                    ctx.inner_ratio = strtof(val, NULL);
                else if (strcmp(ctx.prop_key, "thickness") == 0)
                    ctx.thickness = strtof(val, NULL);
                else if (strcmp(ctx.prop_key, "offset") == 0)
                    ctx.offset = strtof(val, NULL);
                else if (strcmp(ctx.prop_key, "width") == 0)
                    ctx.width = strtof(val, NULL);
                else if (strcmp(ctx.prop_key, "radius_outer") == 0)
                    ctx.radius_outer = strtof(val, NULL);
                else if (strcmp(ctx.prop_key, "radius_inner") == 0)
                    ctx.radius_inner = strtof(val, NULL);
                expect_value = 0;
            }
            break;
        }
        default:
            break;
        }
        yaml_event_delete(&event);
    }

    build_prim(buffer, primitive_type_name, &ctx);
    return YETTY_OK_VOID();
}

/*=============================================================================
 * Registration
 *===========================================================================*/

struct yetty_core_void_result
yetty_ysdf_register_yaml_factories(struct yetty_ypaint_yaml_parser *parser) {
    struct yetty_core_void_result res;

    res = yetty_ypaint_yaml_parser_register(parser, "circle", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "box", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "segment", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "triangle", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "ellipse", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "arc", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "rounded_box", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "rhombus", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "pentagon", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "hexagon", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "star", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "pie", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "ring", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "heart", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "cross", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "rounded_x", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "capsule", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "moon", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "egg", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "octogon", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "hexagram", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    res = yetty_ypaint_yaml_parser_register(parser, "pentagram", yetty_ysdf_yaml_factory);
    if (!res.ok) return res;

    return YETTY_OK_VOID();
}