// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ypaint/sdf/gen-sdf-code.py

#pragma once

#include "ypaint-sdf-types.gen.h"
#include <yetty/ypaint/core/ypaint-buffer.h>

#ifdef __cplusplus
extern "C" {
#endif

YPaintIdResult ypaint_sdf_add_circle(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfCircle* geom);

YPaintIdResult ypaint_sdf_add_box(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfBox* geom);

YPaintIdResult ypaint_sdf_add_segment(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfSegment* geom);

YPaintIdResult ypaint_sdf_add_triangle(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfTriangle* geom);

YPaintIdResult ypaint_sdf_add_ellipse(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfEllipse* geom);

YPaintIdResult ypaint_sdf_add_arc(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfArc* geom);

YPaintIdResult ypaint_sdf_add_rounded_box(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfRoundedBox* geom);

YPaintIdResult ypaint_sdf_add_rhombus(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfRhombus* geom);

YPaintIdResult ypaint_sdf_add_pentagon(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfPentagon* geom);

YPaintIdResult ypaint_sdf_add_hexagon(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfHexagon* geom);

YPaintIdResult ypaint_sdf_add_star(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfStar* geom);

YPaintIdResult ypaint_sdf_add_pie(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfPie* geom);

YPaintIdResult ypaint_sdf_add_ring(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfRing* geom);

YPaintIdResult ypaint_sdf_add_heart(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfHeart* geom);

YPaintIdResult ypaint_sdf_add_cross(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfCross* geom);

YPaintIdResult ypaint_sdf_add_rounded_x(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfRoundedX* geom);

YPaintIdResult ypaint_sdf_add_capsule(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfCapsule* geom);

YPaintIdResult ypaint_sdf_add_moon(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfMoon* geom);

YPaintIdResult ypaint_sdf_add_egg(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfEgg* geom);

YPaintIdResult ypaint_sdf_add_octogon(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfOctogon* geom);

YPaintIdResult ypaint_sdf_add_hexagram(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfHexagram* geom);

YPaintIdResult ypaint_sdf_add_pentagram(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfPentagram* geom);

YPaintIdResult ypaint_sdf_add_sphere_3d(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfSphere3D* geom);

YPaintIdResult ypaint_sdf_add_box_3d(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfBox3D* geom);

YPaintIdResult ypaint_sdf_add_torus_3d(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfTorus3D* geom);

YPaintIdResult ypaint_sdf_add_cylinder_3d(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfCylinder3D* geom);

#ifdef __cplusplus
}
#endif