#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""Generate C and WGSL code from yfsvm-opcodes.yaml.

Run:  uv run src/yetty/ypaint/yfsvm/gen-yfsvm-code.py

Reads:    src/yetty/ypaint/yfsvm/yfsvm-opcodes.yaml
Generates:
  include/yetty/ypaint/yfsvm/yfsvm.gen.h   - C enum + encode/decode macros
  src/yetty/ypaint/yfsvm/yfsvm.gen.wgsl    - WGSL VM execution
"""

from pathlib import Path
import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent.parent.parent

YAML_PATH = SCRIPT_DIR / "yfsvm-opcodes.yaml"
HEADER_OUT = PROJECT_ROOT / "include" / "yetty" / "ypaint" / "yfsvm" / "yfsvm.gen.h"
WGSL_OUT = SCRIPT_DIR / "yfsvm.gen.wgsl"

HEADER = """// Auto-generated from yfsvm-opcodes.yaml - DO NOT EDIT
// Generated by: src/yetty/ypaint/yfsvm/gen-yfsvm-code.py
"""


def load_config(path: Path) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def generate_c_header(config: dict, out: Path) -> None:
    """Generate yfsvm.gen.h"""
    lines = [HEADER, "#pragma once", "", "#include <stdint.h>", ""]
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")

    # Constants
    lines.append("// Constants")
    lines.append(f"#define YFSVM_MAGIC 0x{config['magic']:08X}u")
    lines.append(f"#define YFSVM_VERSION {config['version']}u")
    lines.append(f"#define YFSVM_MAX_REGISTERS {config['max_registers']}u")
    lines.append(f"#define YFSVM_MAX_FUNCTIONS {config['max_functions']}u")
    lines.append(f"#define YFSVM_MAX_CONSTANTS {config['max_constants']}u")
    lines.append(f"#define YFSVM_MAX_INSTRUCTIONS {config['max_instructions']}u")
    lines.append(f"#define YFSVM_MAX_EXECUTION_STEPS {config['max_execution_steps']}u")
    lines.append("")

    # Opcode enum
    lines.append("// Opcodes")
    lines.append("typedef enum YfsvmOpcode {")
    for op in config['opcodes']:
        lines.append(f"    YFSVM_OP_{op['name']} = 0x{op['value']:02X},")
    lines.append("} YfsvmOpcode;")
    lines.append("")

    # Instruction encoding/decoding
    lines.append("// Instruction format (32-bit):")
    lines.append("//   [31:24] opcode (8 bits)")
    lines.append("//   [23:20] dst    (4 bits)")
    lines.append("//   [19:16] src1   (4 bits)")
    lines.append("//   [15:12] src2   (4 bits)")
    lines.append("//   [11:0]  imm12  (12 bits)")
    lines.append("")
    lines.append("// Encode instruction")
    lines.append("static inline uint32_t yfsvm_encode(YfsvmOpcode op, uint8_t dst, uint8_t src1, uint8_t src2, uint16_t imm12) {")
    lines.append("    return ((uint32_t)op << 24) | ((dst & 0xF) << 20) | ((src1 & 0xF) << 16) | ((src2 & 0xF) << 12) | (imm12 & 0xFFF);")
    lines.append("}")
    lines.append("")
    lines.append("// Decode instruction")
    lines.append("static inline YfsvmOpcode yfsvm_decode_opcode(uint32_t instr) { return (YfsvmOpcode)((instr >> 24) & 0xFF); }")
    lines.append("static inline uint8_t yfsvm_decode_dst(uint32_t instr) { return (instr >> 20) & 0xF; }")
    lines.append("static inline uint8_t yfsvm_decode_src1(uint32_t instr) { return (instr >> 16) & 0xF; }")
    lines.append("static inline uint8_t yfsvm_decode_src2(uint32_t instr) { return (instr >> 12) & 0xF; }")
    lines.append("static inline uint16_t yfsvm_decode_imm12(uint32_t instr) { return instr & 0xFFF; }")
    lines.append("")

    # Opcode name for debugging
    lines.append("// Get opcode name for debugging")
    lines.append("static inline const char* yfsvm_opcode_name(YfsvmOpcode op) {")
    lines.append("    switch (op) {")
    for op in config['opcodes']:
        lines.append(f'        case YFSVM_OP_{op["name"]}: return "{op["name"]}";')
    lines.append('        default: return "UNKNOWN";')
    lines.append("    }")
    lines.append("}")
    lines.append("")

    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def generate_wgsl(config: dict, out: Path) -> None:
    """Generate yfsvm.gen.wgsl"""
    lines = [HEADER, ""]

    # Constants
    lines.append("// Constants")
    lines.append(f"const YFSVM_MAGIC: u32 = 0x{config['magic']:08X}u;")
    lines.append(f"const YFSVM_VERSION: u32 = {config['version']}u;")
    lines.append(f"const YFSVM_MAX_REGISTERS: u32 = {config['max_registers']}u;")
    lines.append(f"const YFSVM_MAX_FUNCTIONS: u32 = {config['max_functions']}u;")
    lines.append(f"const YFSVM_MAX_EXECUTION_STEPS: u32 = {config['max_execution_steps']}u;")
    lines.append("")

    # Opcode constants
    lines.append("// Opcodes")
    for op in config['opcodes']:
        lines.append(f"const YFSVM_OP_{op['name']}: u32 = 0x{op['value']:02X}u;")
    lines.append("")

    # Instruction decode helpers
    lines.append("// Instruction decoding")
    lines.append("fn yfsvm_decode_opcode(instr: u32) -> u32 { return (instr >> 24u) & 0xFFu; }")
    lines.append("fn yfsvm_decode_dst(instr: u32) -> u32 { return (instr >> 20u) & 0xFu; }")
    lines.append("fn yfsvm_decode_src1(instr: u32) -> u32 { return (instr >> 16u) & 0xFu; }")
    lines.append("fn yfsvm_decode_src2(instr: u32) -> u32 { return (instr >> 12u) & 0xFu; }")
    lines.append("fn yfsvm_decode_imm12(instr: u32) -> u32 { return instr & 0xFFFu; }")
    lines.append("")

    # Register read/write (WGSL doesn't support dynamic array indexing well)
    lines.append("// Register access")
    lines.append("fn yfsvm_read_reg(regs: ptr<function, array<f32, 16>>, idx: u32) -> f32 {")
    lines.append("    switch idx {")
    for i in range(16):
        lines.append(f"        case {i}u: {{ return (*regs)[{i}]; }}")
    lines.append("        default: { return 0.0; }")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("fn yfsvm_write_reg(regs: ptr<function, array<f32, 16>>, idx: u32, val: f32) {")
    lines.append("    switch idx {")
    for i in range(16):
        lines.append(f"        case {i}u: {{ (*regs)[{i}] = val; }}")
    lines.append("        default: {}")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # Main execute function
    lines.append("// Execute yfsvm bytecode")
    lines.append("// bytecodeOffset: index into buf where program starts")
    lines.append("// funcIndex: which function to execute (0-based)")
    lines.append("// x: domain value, t: time, samplers: s0-s7")
    lines.append("fn yfsvm_execute(bytecodeOffset: u32, funcIndex: u32, x: f32, t: f32, samplers: array<f32, 8>) -> f32 {")
    lines.append("    // Read header")
    lines.append("    let magic = bitcast<u32>(buf[bytecodeOffset]);")
    lines.append("    if (magic != YFSVM_MAGIC) { return 0.0; }")
    lines.append("")
    lines.append("    let funcCount = bitcast<u32>(buf[bytecodeOffset + 2u]);")
    lines.append("    let constCount = bitcast<u32>(buf[bytecodeOffset + 3u]);")
    lines.append("    if (funcIndex >= funcCount) { return 0.0; }")
    lines.append("")
    lines.append("    // Function table at offset 4, packed u32 per function (offset:16, length:16)")
    lines.append("    let funcTableOffset = bytecodeOffset + 4u;")
    lines.append("    let packedFunc = bitcast<u32>(buf[funcTableOffset + funcIndex]);")
    lines.append("    let funcOffset = packedFunc & 0xFFFFu;")
    lines.append("    let funcLength = packedFunc >> 16u;")
    lines.append("")
    lines.append("    // Constants after function table (padded to MAX_FUNCTIONS)")
    lines.append("    let constOffset = funcTableOffset + YFSVM_MAX_FUNCTIONS;")
    lines.append("    // Code after constants")
    lines.append("    let codeOffset = constOffset + constCount;")
    lines.append("")
    lines.append("    // Initialize registers")
    lines.append("    var regs: array<f32, 16>;")
    lines.append("    for (var i = 0u; i < 16u; i++) { regs[i] = 0.0; }")
    lines.append("")
    lines.append("    // Execute")
    lines.append("    var pc = funcOffset;")
    lines.append("    let endPc = funcOffset + funcLength;")
    lines.append("")
    lines.append(f"    for (var iter = 0u; iter < YFSVM_MAX_EXECUTION_STEPS; iter++) {{")
    lines.append("        if (pc >= endPc) { break; }")
    lines.append("")
    lines.append("        let instr = bitcast<u32>(buf[codeOffset + pc]);")
    lines.append("        pc++;")
    lines.append("")
    lines.append("        let op = yfsvm_decode_opcode(instr);")
    lines.append("        let dst = yfsvm_decode_dst(instr);")
    lines.append("        let src1 = yfsvm_decode_src1(instr);")
    lines.append("        let src2 = yfsvm_decode_src2(instr);")
    lines.append("        let imm = yfsvm_decode_imm12(instr);")
    lines.append("")
    lines.append("        let v1 = yfsvm_read_reg(&regs, src1);")
    lines.append("        let v2 = yfsvm_read_reg(&regs, src2);")
    lines.append("")

    # Generate switch for opcodes
    lines.append("        switch op {")
    for op in config['opcodes']:
        wgsl = op['wgsl'].strip()
        if wgsl:
            lines.append(f"            case YFSVM_OP_{op['name']}: {{ {wgsl} }}")
        else:
            lines.append(f"            case YFSVM_OP_{op['name']}: {{}}")
    lines.append("            default: {}")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    return regs[0];")
    lines.append("}")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    print(f"Generated: {out}")


def main():
    config = load_config(YAML_PATH)
    generate_c_header(config, HEADER_OUT)
    generate_wgsl(config, WGSL_OUT)
    print("Done.")


if __name__ == "__main__":
    main()
