// =============================================================================
// Terminal Screen Shader - Raster Font Only (Simplified)
// =============================================================================

// Grid uniforms - MINIMAL for raster font rendering
struct GridUniforms {
    projection: mat4x4<f32>,
    screenSize: vec2<f32>,
    cellSize: vec2<f32>,
    gridSize: vec2<f32>,
    cursorPos: vec2<f32>,
    cursorVisible: f32,
    cursorShape: f32,
    cursorBlink: f32,
    scale: f32,
    defaultFg: u32,
    defaultBg: u32,
};

// Raster glyph UV (8 bytes per glyph)
struct RasterGlyphUV {
    uv: vec2<f32>,
};

// Cell structure - matches C++ TextCell struct (12 bytes)
struct Cell {
    glyph: u32,
    fg: u32,
    bg: u32,
};

// Render layer bindings (group 0 - generated by GpuResourceBinder)
// RENDER_LAYER_BINDINGS_PLACEHOLDER

// Vertex input/output
struct VertexInput {
    @location(0) position: vec2<f32>,
};

struct VertexOutput {
    @builtin(position) position: vec4<f32>,
};

@vertex
fn vs_main(input: VertexInput) -> VertexOutput {
    var output: VertexOutput;
    output.position = vec4<f32>(input.position, 0.0, 1.0);
    return output;
}

@fragment
fn fs_main(input: VertexOutput) -> @location(0) vec4<f32> {
    let pixelPos = input.position.xy;

    // Calculate grid dimensions in pixels
    let gridPixelWidth = grid.gridSize.x * grid.cellSize.x;
    let gridPixelHeight = grid.gridSize.y * grid.cellSize.y;

    // Outside grid area - dark background
    if (pixelPos.x < 0.0 || pixelPos.y < 0.0 || pixelPos.x >= gridPixelWidth || pixelPos.y >= gridPixelHeight) {
        return vec4<f32>(0.1, 0.1, 0.1, 1.0);
    }

    // Calculate which cell we're in
    let cellCol = floor(pixelPos.x / grid.cellSize.x);
    let cellRow = floor(pixelPos.y / grid.cellSize.y);
    let cellCoord = vec2<i32>(i32(cellCol), i32(cellRow));

    // Position within the cell
    let localPx = vec2<f32>(
        pixelPos.x - cellCol * grid.cellSize.x,
        pixelPos.y - cellRow * grid.cellSize.y
    );

    // Get cell data
    let cellIndex = u32(cellCoord.y) * u32(grid.gridSize.x) + u32(cellCoord.x);
    let cell = cellBuffer[cellIndex];

    // Unpack colors
    let fgColor = vec3<f32>(
        f32(cell.fg & 0xFFu) / 255.0,
        f32((cell.fg >> 8u) & 0xFFu) / 255.0,
        f32((cell.fg >> 16u) & 0xFFu) / 255.0
    );
    let bgColor = vec3<f32>(
        f32(cell.bg & 0xFFu) / 255.0,
        f32((cell.bg >> 8u) & 0xFFu) / 255.0,
        f32((cell.bg >> 16u) & 0xFFu) / 255.0
    );

    // Start with background
    var finalColor = bgColor;

    // Render glyph if not empty
    let glyphIndex = cell.glyph;
    if (glyphIndex > 32u) {
        let glyphUV = rasterFontBuffer[glyphIndex].uv;
        if (glyphUV.x >= 0.0) {
            let glyphSizeUV = vec2<f32>(grid.cellSize.x / 1024.0, grid.cellSize.y / 1024.0);
            let localUV = localPx / grid.cellSize;
            let sampleUV = glyphUV + localUV * glyphSizeUV;
            let alpha = textureSampleLevel(rasterFontTexture, rasterFontSampler, sampleUV, 0.0).r;
            finalColor = mix(bgColor, fgColor, alpha);
        }
    }

    // Cursor rendering
    let isCursor = grid.cursorVisible > 0.5 &&
                   cellCoord.x == i32(grid.cursorPos.x) &&
                   cellCoord.y == i32(grid.cursorPos.y);
    if (isCursor) {
        var cursorOn = true;
        // TODO: Add time uniform for cursor blink
        // if (grid.cursorBlink > 0.5) {
        //     cursorOn = fract(time) < 0.5;
        // }
        if (cursorOn) {
            let localUV = localPx / grid.cellSize;
            let shape = i32(grid.cursorShape);
            var drawCursor = false;
            if (shape == 2) {
                drawCursor = localUV.y > 0.85;
            } else if (shape == 3) {
                drawCursor = localUV.x < 0.1;
            } else {
                drawCursor = true;
            }
            if (drawCursor) {
                finalColor = vec3<f32>(1.0, 1.0, 1.0) - finalColor;
            }
        }
    }

    return vec4<f32>(finalColor, 1.0);
}
