// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ysdf/gen-sdf-code.py

#pragma once

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum yetty_ysdf_type {
    YETTY_YSDF_CIRCLE = 0,
    YETTY_YSDF_BOX = 1,
    YETTY_YSDF_SEGMENT = 2,
    YETTY_YSDF_TRIANGLE = 3,
    YETTY_YSDF_ELLIPSE = 6,
    YETTY_YSDF_ARC = 7,
    YETTY_YSDF_ROUNDED_BOX = 8,
    YETTY_YSDF_RHOMBUS = 9,
    YETTY_YSDF_PENTAGON = 10,
    YETTY_YSDF_HEXAGON = 11,
    YETTY_YSDF_STAR = 12,
    YETTY_YSDF_PIE = 13,
    YETTY_YSDF_RING = 14,
    YETTY_YSDF_HEART = 15,
    YETTY_YSDF_CROSS = 16,
    YETTY_YSDF_ROUNDED_X = 17,
    YETTY_YSDF_CAPSULE = 18,
    YETTY_YSDF_MOON = 19,
    YETTY_YSDF_EGG = 20,
    YETTY_YSDF_OCTOGON = 28,
    YETTY_YSDF_HEXAGRAM = 29,
    YETTY_YSDF_PENTAGRAM = 30,
    YETTY_YSDF_SPHERE_3D = 100,
    YETTY_YSDF_BOX_3D = 101,
    YETTY_YSDF_TORUS_3D = 103,
    YETTY_YSDF_CYLINDER_3D = 105,
};

struct yetty_ysdf_circle {
    float center_x;
    float center_y;
    float radius;
};

struct yetty_ysdf_box {
    float center_x;
    float center_y;
    float half_width;
    float half_height;
    float corner_radius;
};

struct yetty_ysdf_segment {
    float start_x;
    float start_y;
    float end_x;
    float end_y;
};

struct yetty_ysdf_triangle {
    float vertex_a_x;
    float vertex_a_y;
    float vertex_b_x;
    float vertex_b_y;
    float vertex_c_x;
    float vertex_c_y;
};

struct yetty_ysdf_ellipse {
    float center_x;
    float center_y;
    float radius_x;
    float radius_y;
};

struct yetty_ysdf_arc {
    float center_x;
    float center_y;
    float aperture_x;
    float aperture_y;
    float radius;
    float thickness;
};

struct yetty_ysdf_rounded_box {
    float center_x;
    float center_y;
    float half_width;
    float half_height;
    float radius_top_right;
    float radius_bottom_right;
    float radius_top_left;
    float radius_bottom_left;
};

struct yetty_ysdf_rhombus {
    float center_x;
    float center_y;
    float half_width;
    float half_height;
};

struct yetty_ysdf_pentagon {
    float center_x;
    float center_y;
    float radius;
};

struct yetty_ysdf_hexagon {
    float center_x;
    float center_y;
    float radius;
};

struct yetty_ysdf_star {
    float center_x;
    float center_y;
    float radius;
    float num_points;
    float inner_ratio;
};

struct yetty_ysdf_pie {
    float center_x;
    float center_y;
    float aperture_x;
    float aperture_y;
    float radius;
};

struct yetty_ysdf_ring {
    float center_x;
    float center_y;
    float normal_x;
    float normal_y;
    float radius;
    float thickness;
};

struct yetty_ysdf_heart {
    float center_x;
    float center_y;
    float scale;
};

struct yetty_ysdf_cross {
    float center_x;
    float center_y;
    float half_width;
    float half_height;
    float corner_radius;
};

struct yetty_ysdf_rounded_x {
    float center_x;
    float center_y;
    float width;
    float radius;
};

struct yetty_ysdf_capsule {
    float start_x;
    float start_y;
    float end_x;
    float end_y;
    float radius;
};

struct yetty_ysdf_moon {
    float center_x;
    float center_y;
    float offset;
    float radius_outer;
    float radius_inner;
};

struct yetty_ysdf_egg {
    float center_x;
    float center_y;
    float radius_outer;
    float radius_inner;
};

struct yetty_ysdf_octogon {
    float center_x;
    float center_y;
    float radius;
};

struct yetty_ysdf_hexagram {
    float center_x;
    float center_y;
    float radius;
};

struct yetty_ysdf_pentagram {
    float center_x;
    float center_y;
    float radius;
};

struct yetty_ysdf_sphere_3d {
    float position_x;
    float position_y;
    float position_z;
    float radius;
};

struct yetty_ysdf_box_3d {
    float position_x;
    float position_y;
    float position_z;
    float half_size_x;
    float half_size_y;
    float half_size_z;
};

struct yetty_ysdf_torus_3d {
    float position_x;
    float position_y;
    float position_z;
    float major_radius;
    float minor_radius;
};

struct yetty_ysdf_cylinder_3d {
    float position_x;
    float position_y;
    float position_z;
    float radius;
    float half_height;
};

// Word count per SDF primitive type
static inline uint32_t yetty_ysdf_word_count(enum yetty_ysdf_type type) {
    switch (type) {
        case YETTY_YSDF_CIRCLE: return 8u;
        case YETTY_YSDF_BOX: return 10u;
        case YETTY_YSDF_SEGMENT: return 9u;
        case YETTY_YSDF_TRIANGLE: return 11u;
        case YETTY_YSDF_ELLIPSE: return 9u;
        case YETTY_YSDF_ARC: return 11u;
        case YETTY_YSDF_ROUNDED_BOX: return 13u;
        case YETTY_YSDF_RHOMBUS: return 9u;
        case YETTY_YSDF_PENTAGON: return 8u;
        case YETTY_YSDF_HEXAGON: return 8u;
        case YETTY_YSDF_STAR: return 10u;
        case YETTY_YSDF_PIE: return 10u;
        case YETTY_YSDF_RING: return 11u;
        case YETTY_YSDF_HEART: return 8u;
        case YETTY_YSDF_CROSS: return 10u;
        case YETTY_YSDF_ROUNDED_X: return 9u;
        case YETTY_YSDF_CAPSULE: return 10u;
        case YETTY_YSDF_MOON: return 10u;
        case YETTY_YSDF_EGG: return 9u;
        case YETTY_YSDF_OCTOGON: return 8u;
        case YETTY_YSDF_HEXAGRAM: return 8u;
        case YETTY_YSDF_PENTAGRAM: return 8u;
        case YETTY_YSDF_SPHERE_3D: return 9u;
        case YETTY_YSDF_BOX_3D: return 11u;
        case YETTY_YSDF_TORUS_3D: return 10u;
        case YETTY_YSDF_CYLINDER_3D: return 10u;
        default: return 0u;
    }
}

// Primitive size in bytes - use as yetty_ypaint_core_primitive_size_fn callback
static inline size_t yetty_ysdf_primitive_size(uint32_t type) {
    return yetty_ysdf_word_count((enum yetty_ysdf_type)type) * sizeof(float);
}

// Compute AABB for an SDF primitive
// data: full primitive data (type + z_order + style + geometry)
// word_count: number of 32-bit words in data
#include <yetty/ycore/types.h>

struct rectangle_result yetty_ysdf_compute_aabb(const float *data, uint32_t word_count);

#ifdef __cplusplus
}
#endif