// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ysdf/gen-sdf-code.py

#pragma once

#include <yetty/ypaint-core/yaml-factory.h>

#ifdef __cplusplus
extern "C" {
#endif

// SDF factory - handles all SDF primitive types
struct yetty_core_void_result
yetty_ysdf_yaml_factory(struct yetty_ypaint_core_buffer *buffer,
                        yaml_parser_t *yaml_parser,
                        const char *primitive_type_name);

// Register all SDF primitive types with the parser
// Supported types: circle, box, segment, triangle, ellipse, arc, rounded_box, rhombus, pentagon, hexagon, star, pie, ring, heart, cross, rounded_x, capsule, moon, egg, octogon, hexagram, pentagram
struct yetty_ypaint_yaml_parser;
struct yetty_core_void_result
yetty_ysdf_register_yaml_factories(struct yetty_ypaint_yaml_parser *parser);

#ifdef __cplusplus
}
#endif