// Auto-generated from yfsvm-opcodes.yaml - DO NOT EDIT
// Generated by: src/yetty/ypaint/yfsvm/gen-yfsvm-code.py


// Constants
const YFSVM_MAGIC: u32 = 0x5946534Du;
const YFSVM_VERSION: u32 = 1u;
const YFSVM_MAX_REGISTERS: u32 = 16u;
const YFSVM_MAX_FUNCTIONS: u32 = 16u;
const YFSVM_MAX_EXECUTION_STEPS: u32 = 1024u;

// Opcodes
const YFSVM_OP_NOP: u32 = 0x00u;
const YFSVM_OP_RET: u32 = 0x01u;
const YFSVM_OP_LOAD_C: u32 = 0x02u;
const YFSVM_OP_LOAD_X: u32 = 0x03u;
const YFSVM_OP_LOAD_T: u32 = 0x04u;
const YFSVM_OP_LOAD_S: u32 = 0x05u;
const YFSVM_OP_MOV: u32 = 0x06u;
const YFSVM_OP_ADD: u32 = 0x10u;
const YFSVM_OP_SUB: u32 = 0x11u;
const YFSVM_OP_MUL: u32 = 0x12u;
const YFSVM_OP_DIV: u32 = 0x13u;
const YFSVM_OP_NEG: u32 = 0x14u;
const YFSVM_OP_MOD: u32 = 0x15u;
const YFSVM_OP_SIN: u32 = 0x20u;
const YFSVM_OP_COS: u32 = 0x21u;
const YFSVM_OP_TAN: u32 = 0x22u;
const YFSVM_OP_ASIN: u32 = 0x23u;
const YFSVM_OP_ACOS: u32 = 0x24u;
const YFSVM_OP_ATAN: u32 = 0x25u;
const YFSVM_OP_ATAN2: u32 = 0x26u;
const YFSVM_OP_SINH: u32 = 0x27u;
const YFSVM_OP_COSH: u32 = 0x28u;
const YFSVM_OP_TANH: u32 = 0x29u;
const YFSVM_OP_EXP: u32 = 0x30u;
const YFSVM_OP_EXP2: u32 = 0x31u;
const YFSVM_OP_LOG: u32 = 0x32u;
const YFSVM_OP_LOG2: u32 = 0x33u;
const YFSVM_OP_POW: u32 = 0x34u;
const YFSVM_OP_SQRT: u32 = 0x35u;
const YFSVM_OP_RSQRT: u32 = 0x36u;
const YFSVM_OP_ABS: u32 = 0x40u;
const YFSVM_OP_MIN: u32 = 0x41u;
const YFSVM_OP_MAX: u32 = 0x42u;
const YFSVM_OP_FLOOR: u32 = 0x43u;
const YFSVM_OP_CEIL: u32 = 0x44u;
const YFSVM_OP_ROUND: u32 = 0x45u;
const YFSVM_OP_FRACT: u32 = 0x46u;
const YFSVM_OP_SIGN: u32 = 0x47u;
const YFSVM_OP_CLAMP01: u32 = 0x48u;
const YFSVM_OP_STEP: u32 = 0x49u;
const YFSVM_OP_MIX: u32 = 0x4Au;

// Instruction decoding
fn yfsvm_decode_opcode(instr: u32) -> u32 { return (instr >> 24u) & 0xFFu; }
fn yfsvm_decode_dst(instr: u32) -> u32 { return (instr >> 20u) & 0xFu; }
fn yfsvm_decode_src1(instr: u32) -> u32 { return (instr >> 16u) & 0xFu; }
fn yfsvm_decode_src2(instr: u32) -> u32 { return (instr >> 12u) & 0xFu; }
fn yfsvm_decode_imm12(instr: u32) -> u32 { return instr & 0xFFFu; }

// Register access
fn yfsvm_read_reg(regs: ptr<function, array<f32, 16>>, idx: u32) -> f32 {
    switch idx {
        case 0u: { return (*regs)[0]; }
        case 1u: { return (*regs)[1]; }
        case 2u: { return (*regs)[2]; }
        case 3u: { return (*regs)[3]; }
        case 4u: { return (*regs)[4]; }
        case 5u: { return (*regs)[5]; }
        case 6u: { return (*regs)[6]; }
        case 7u: { return (*regs)[7]; }
        case 8u: { return (*regs)[8]; }
        case 9u: { return (*regs)[9]; }
        case 10u: { return (*regs)[10]; }
        case 11u: { return (*regs)[11]; }
        case 12u: { return (*regs)[12]; }
        case 13u: { return (*regs)[13]; }
        case 14u: { return (*regs)[14]; }
        case 15u: { return (*regs)[15]; }
        default: { return 0.0; }
    }
}

fn yfsvm_write_reg(regs: ptr<function, array<f32, 16>>, idx: u32, val: f32) {
    switch idx {
        case 0u: { (*regs)[0] = val; }
        case 1u: { (*regs)[1] = val; }
        case 2u: { (*regs)[2] = val; }
        case 3u: { (*regs)[3] = val; }
        case 4u: { (*regs)[4] = val; }
        case 5u: { (*regs)[5] = val; }
        case 6u: { (*regs)[6] = val; }
        case 7u: { (*regs)[7] = val; }
        case 8u: { (*regs)[8] = val; }
        case 9u: { (*regs)[9] = val; }
        case 10u: { (*regs)[10] = val; }
        case 11u: { (*regs)[11] = val; }
        case 12u: { (*regs)[12] = val; }
        case 13u: { (*regs)[13] = val; }
        case 14u: { (*regs)[14] = val; }
        case 15u: { (*regs)[15] = val; }
        default: {}
    }
}

// Execute yfsvm bytecode
// bytecodeOffset: index into buf where program starts
// funcIndex: which function to execute (0-based)
// x: domain value, t: time, samplers: s0-s7
fn yfsvm_execute(bytecodeOffset: u32, funcIndex: u32, x: f32, t: f32, samplers: array<f32, 8>) -> f32 {
    // Read header
    let magic = bitcast<u32>(buf[bytecodeOffset]);
    if (magic != YFSVM_MAGIC) { return 0.0; }

    let funcCount = bitcast<u32>(buf[bytecodeOffset + 2u]);
    let constCount = bitcast<u32>(buf[bytecodeOffset + 3u]);
    if (funcIndex >= funcCount) { return 0.0; }

    // Function table at offset 4, packed u32 per function (offset:16, length:16)
    let funcTableOffset = bytecodeOffset + 4u;
    let packedFunc = bitcast<u32>(buf[funcTableOffset + funcIndex]);
    let funcOffset = packedFunc & 0xFFFFu;
    let funcLength = packedFunc >> 16u;

    // Constants after function table (padded to MAX_FUNCTIONS)
    let constOffset = funcTableOffset + YFSVM_MAX_FUNCTIONS;
    // Code after constants
    let codeOffset = constOffset + constCount;

    // Initialize registers
    var regs: array<f32, 16>;
    for (var i = 0u; i < 16u; i++) { regs[i] = 0.0; }

    // Execute
    var pc = funcOffset;
    let endPc = funcOffset + funcLength;

    for (var iter = 0u; iter < YFSVM_MAX_EXECUTION_STEPS; iter++) {
        if (pc >= endPc) { break; }

        let instr = bitcast<u32>(buf[codeOffset + pc]);
        pc++;

        let op = yfsvm_decode_opcode(instr);
        let dst = yfsvm_decode_dst(instr);
        let src1 = yfsvm_decode_src1(instr);
        let src2 = yfsvm_decode_src2(instr);
        let imm = yfsvm_decode_imm12(instr);

        let v1 = yfsvm_read_reg(&regs, src1);
        let v2 = yfsvm_read_reg(&regs, src2);

        switch op {
            case YFSVM_OP_NOP: { // nop }
            case YFSVM_OP_RET: { return regs[0]; }
            case YFSVM_OP_LOAD_C: { regs[dst] = bitcast<f32>(buf[constOffset + imm]); }
            case YFSVM_OP_LOAD_X: { regs[dst] = x; }
            case YFSVM_OP_LOAD_T: { regs[dst] = t; }
            case YFSVM_OP_LOAD_S: { regs[dst] = samplers[imm & 7u]; }
            case YFSVM_OP_MOV: { regs[dst] = v1; }
            case YFSVM_OP_ADD: { regs[dst] = v1 + v2; }
            case YFSVM_OP_SUB: { regs[dst] = v1 - v2; }
            case YFSVM_OP_MUL: { regs[dst] = v1 * v2; }
            case YFSVM_OP_DIV: { regs[dst] = v1 / v2; }
            case YFSVM_OP_NEG: { regs[dst] = -v1; }
            case YFSVM_OP_MOD: { regs[dst] = v1 - v2 * floor(v1 / v2); }
            case YFSVM_OP_SIN: { regs[dst] = sin(v1); }
            case YFSVM_OP_COS: { regs[dst] = cos(v1); }
            case YFSVM_OP_TAN: { regs[dst] = tan(v1); }
            case YFSVM_OP_ASIN: { regs[dst] = asin(v1); }
            case YFSVM_OP_ACOS: { regs[dst] = acos(v1); }
            case YFSVM_OP_ATAN: { regs[dst] = atan(v1); }
            case YFSVM_OP_ATAN2: { regs[dst] = atan2(v1, v2); }
            case YFSVM_OP_SINH: { regs[dst] = sinh(v1); }
            case YFSVM_OP_COSH: { regs[dst] = cosh(v1); }
            case YFSVM_OP_TANH: { regs[dst] = tanh(v1); }
            case YFSVM_OP_EXP: { regs[dst] = exp(v1); }
            case YFSVM_OP_EXP2: { regs[dst] = exp2(v1); }
            case YFSVM_OP_LOG: { regs[dst] = log(v1); }
            case YFSVM_OP_LOG2: { regs[dst] = log2(v1); }
            case YFSVM_OP_POW: { regs[dst] = pow(v1, v2); }
            case YFSVM_OP_SQRT: { regs[dst] = sqrt(v1); }
            case YFSVM_OP_RSQRT: { regs[dst] = inverseSqrt(v1); }
            case YFSVM_OP_ABS: { regs[dst] = abs(v1); }
            case YFSVM_OP_MIN: { regs[dst] = min(v1, v2); }
            case YFSVM_OP_MAX: { regs[dst] = max(v1, v2); }
            case YFSVM_OP_FLOOR: { regs[dst] = floor(v1); }
            case YFSVM_OP_CEIL: { regs[dst] = ceil(v1); }
            case YFSVM_OP_ROUND: { regs[dst] = round(v1); }
            case YFSVM_OP_FRACT: { regs[dst] = fract(v1); }
            case YFSVM_OP_SIGN: { regs[dst] = sign(v1); }
            case YFSVM_OP_CLAMP01: { regs[dst] = clamp(v1, 0.0, 1.0); }
            case YFSVM_OP_STEP: { regs[dst] = step(v1, v2); }
            case YFSVM_OP_MIX: { regs[dst] = mix(v1, v2, regs[imm & 0xFu]); }
            default: {}
        }
    }

    return regs[0];
}