/* incbin-assets.c - Embedded asset management */

#include <yetty/ytrace.h>
#include <brotli/decode.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <errno.h>

#ifndef YETTY_BUILD_VERSION
#define YETTY_BUILD_VERSION "dev"
#endif

#define MAX_ASSETS 1024
#define MAX_PATH_LEN 512

/* Embedded resource declarations (generated by incbin) */
extern const unsigned char gLogoData[];
extern const unsigned int gLogoSize;
extern const unsigned char gDefaultConfigData[];
extern const unsigned int gDefaultConfigSize;

/* Asset entry */
struct asset_entry {
    const char *name;
    const uint8_t *data;
    size_t size;
    int compressed;
};

/* Assets container */
struct yetty_incbin_assets {
    struct asset_entry entries[MAX_ASSETS];
    size_t count;
};

/* Forward declarations for manifest registration functions */
#ifdef HAS_SHADERS_MANIFEST
#include "yetty_shaders_manifest.h"
#endif

#ifdef HAS_FONTS_MANIFEST
#include "yetty_fonts_manifest.h"
#endif

#ifdef HAS_MSDF_FONTS_MANIFEST
#include "yetty_msdf-fonts_manifest.h"
#endif

/* Helper to add asset entry */
static void add_asset(struct yetty_incbin_assets *assets, const char *name,
                      const uint8_t *data, size_t size, int compressed)
{
    if (assets->count >= MAX_ASSETS)
        return;

    assets->entries[assets->count].name = name;
    assets->entries[assets->count].data = data;
    assets->entries[assets->count].size = size;
    assets->entries[assets->count].compressed = compressed;
    assets->count++;
}

/* C callback for manifest registration */
static struct yetty_incbin_assets *g_current_assets = NULL;

static void register_asset_callback(const char *name, const uint8_t *data,
                                    size_t size, int compressed)
{
    if (g_current_assets)
        add_asset(g_current_assets, name, data, size, compressed);
}

/* Create assets container */
struct yetty_incbin_assets *yetty_incbin_assets_create(void)
{
    struct yetty_incbin_assets *assets;

    assets = calloc(1, sizeof(struct yetty_incbin_assets));
    if (!assets)
        return NULL;

    /* Register built-in assets */
    add_asset(assets, "logo.jpeg", gLogoData, gLogoSize, 0);
    add_asset(assets, "default-config.yaml", gDefaultConfigData, gDefaultConfigSize, 0);

    /* Register assets from manifests */
    g_current_assets = assets;

#ifdef HAS_SHADERS_MANIFEST
    register_shaders_assets_c(register_asset_callback);
    ydebug("Registered shader assets from manifest");
#endif

#ifdef HAS_FONTS_MANIFEST
    register_fonts_assets_c(register_asset_callback);
    ydebug("Registered font assets from manifest");
#endif

#ifdef HAS_MSDF_FONTS_MANIFEST
    register_msdf_fonts_assets_c(register_asset_callback);
    ydebug("Registered MSDF font assets from manifest");
#endif

    g_current_assets = NULL;

    ydebug("IncbinAssets: %zu embedded assets available", assets->count);
    return assets;
}

/* Destroy assets container */
void yetty_incbin_assets_destroy(struct yetty_incbin_assets *assets)
{
    free(assets);
}

/* Get marker path */
static void get_marker_path(const char *cache_dir, char *out, size_t out_size)
{
    snprintf(out, out_size, "%s/.yetty-assets/version", cache_dir);
}

/* Create directory recursively */
static int mkdir_p(const char *path)
{
    char tmp[MAX_PATH_LEN];
    char *p = NULL;
    size_t len;

    snprintf(tmp, sizeof(tmp), "%s", path);
    len = strlen(tmp);
    if (tmp[len - 1] == '/')
        tmp[len - 1] = 0;

    for (p = tmp + 1; *p; p++) {
        if (*p == '/') {
            *p = 0;
            if (mkdir(tmp, 0755) != 0 && errno != EEXIST)
                return -1;
            *p = '/';
        }
    }

    if (mkdir(tmp, 0755) != 0 && errno != EEXIST)
        return -1;

    return 0;
}

/* Check if extraction is needed */
int yetty_incbin_assets_needs_extraction(struct yetty_incbin_assets *assets,
                                          const char *cache_dir)
{
    char marker_path[MAX_PATH_LEN];
    char version[64];
    FILE *f;

    (void)assets;

    get_marker_path(cache_dir, marker_path, sizeof(marker_path));
    ydebug("needsExtraction: marker path = %s", marker_path);

    f = fopen(marker_path, "r");
    if (!f) {
        ydebug("needsExtraction: returning 1 (marker not found)");
        return 1;
    }

    if (!fgets(version, sizeof(version), f)) {
        fclose(f);
        return 1;
    }
    fclose(f);

    /* Strip newline */
    version[strcspn(version, "\n")] = 0;

    ydebug("needsExtraction: marker version = '%s', build version = '%s'",
           version, YETTY_BUILD_VERSION);

    if (strcmp(version, YETTY_BUILD_VERSION) != 0) {
        ydebug("needsExtraction: returning 1 (version mismatch)");
        return 1;
    }

    ydebug("needsExtraction: returning 0");
    return 0;
}

/* Decompress brotli data */
static uint8_t *decompress_brotli(const uint8_t *data, size_t size,
                                   size_t *out_size)
{
    size_t decoded_size;
    uint8_t *output;
    size_t capacity;
    BrotliDecoderResult result;

    capacity = size * 10;
    output = malloc(capacity);
    if (!output)
        return NULL;

    do {
        decoded_size = capacity;
        result = BrotliDecoderDecompress(size, data, &decoded_size, output);
        if (result == BROTLI_DECODER_RESULT_NEEDS_MORE_OUTPUT) {
            capacity *= 2;
            uint8_t *new_output = realloc(output, capacity);
            if (!new_output) {
                free(output);
                return NULL;
            }
            output = new_output;
        }
    } while (result == BROTLI_DECODER_RESULT_NEEDS_MORE_OUTPUT);

    if (result != BROTLI_DECODER_RESULT_SUCCESS) {
        free(output);
        return NULL;
    }

    *out_size = decoded_size;
    return output;
}

/* Extract all assets to directory */
int yetty_incbin_assets_extract_to(struct yetty_incbin_assets *assets,
                                    const char *cache_dir)
{
    char path[MAX_PATH_LEN];
    char marker_path[MAX_PATH_LEN];
    char marker_dir[MAX_PATH_LEN];
    size_t i;
    FILE *f;

    ydebug("extractTo: starting extraction to %s", cache_dir);

    for (i = 0; i < assets->count; i++) {
        const struct asset_entry *entry = &assets->entries[i];
        const uint8_t *write_data;
        size_t write_size;
        uint8_t *decompressed = NULL;
        char *last_slash;

        snprintf(path, sizeof(path), "%s/%s", cache_dir, entry->name);
        ydebug("extractTo: extracting '%s' -> '%s'", entry->name, path);

        /* Create parent directories */
        last_slash = strrchr(path, '/');
        if (last_slash) {
            *last_slash = 0;
            if (mkdir_p(path) != 0) {
                ydebug("Failed to create directory: %s", path);
                return 0;
            }
            *last_slash = '/';
        }

        /* Decompress if needed */
        if (entry->compressed) {
            decompressed = decompress_brotli(entry->data, entry->size, &write_size);
            if (!decompressed) {
                ydebug("Failed to decompress: %s", entry->name);
                return 0;
            }
            write_data = decompressed;
            ydebug("Decompressed: %s (%zu -> %zu bytes)", entry->name,
                   entry->size, write_size);
        } else {
            write_data = entry->data;
            write_size = entry->size;
        }

        /* Write file */
        f = fopen(path, "wb");
        if (!f) {
            free(decompressed);
            ydebug("Failed to open file: %s", path);
            return 0;
        }

        if (fwrite(write_data, 1, write_size, f) != write_size) {
            fclose(f);
            free(decompressed);
            ydebug("Failed to write file: %s", path);
            return 0;
        }

        fclose(f);
        free(decompressed);

        if (!entry->compressed) {
            ydebug("Extracted: %s (%zu bytes)", entry->name, write_size);
        }
    }

    /* Write extraction marker */
    get_marker_path(cache_dir, marker_path, sizeof(marker_path));
    strncpy(marker_dir, marker_path, sizeof(marker_dir) - 1);
    marker_dir[sizeof(marker_dir) - 1] = 0;
    char *slash = strrchr(marker_dir, '/');
    if (slash) {
        *slash = 0;
        mkdir_p(marker_dir);
    }

    f = fopen(marker_path, "w");
    if (f) {
        fprintf(f, "%s", YETTY_BUILD_VERSION);
        fclose(f);
    }

    ydebug("Asset extraction complete");
    return 1;
}
