#include <yetty/incbin-assets.hpp>
#include <ytrace/ytrace.hpp>

#include <cstring>
#include <fstream>
#include <unordered_map>
#include <vector>

#ifndef YETTY_BUILD_VERSION
#define YETTY_BUILD_VERSION "dev"
#endif

// Embedded resource declarations (generated by incbin)
// Format: INCBIN(Name, "path") generates gNameData[], gNameSize, gNameEnd
extern "C" {
    extern const unsigned char gLogoData[];
    extern const unsigned int gLogoSize;

    extern const unsigned char gDefaultConfigData[];
    extern const unsigned int gDefaultConfigSize;
}

// Include generated asset manifests
#ifdef HAS_SHADERS_MANIFEST
#include "yetty_shaders_manifest.h"
#endif

#ifdef HAS_FONTS_MANIFEST
#include "yetty_fonts_manifest.h"
#endif

namespace yetty {

struct AssetEntry {
    const uint8_t* data;
    size_t size;
};

#ifndef YETTY_BUILD_VERSION
#define YETTY_BUILD_VERSION_STR "dev"
#else
#define YETTY_BUILD_VERSION_STR YETTY_BUILD_VERSION
#endif

static std::filesystem::path getExtractionMarker(const std::filesystem::path& cacheDir) {
    return cacheDir / ".yetty-assets" / "version";
}

class IncbinAssetsImpl : public IncbinAssets {
public:
    const char* typeName() const override { return "IncbinAssets"; }

    Result<void> init() {
        registerAsset("logo.jpeg", gLogoData, gLogoSize);
        registerAsset("default-config.yaml", gDefaultConfigData, gDefaultConfigSize);

#ifdef HAS_SHADERS_MANIFEST
        register_shaders_assets([this](const char* name, const uint8_t* data, size_t size, bool) {
            registerAsset(name, data, size);
        });
#endif

#ifdef HAS_FONTS_MANIFEST
        register_fonts_assets([this](const char* name, const uint8_t* data, size_t size, bool) {
            registerAsset(name, data, size);
        });
#endif

        ydebug("IncbinAssets: {} embedded assets registered", _assets.size());
        return Ok();
    }

    std::span<const uint8_t> get(std::string_view name) const override {
        auto it = _assets.find(std::string(name));
        if (it == _assets.end()) {
            return {};
        }
        return {it->second.data, it->second.size};
    }

    std::string_view getString(std::string_view name) const override {
        auto data = get(name);
        if (data.empty()) {
            return {};
        }
        return {reinterpret_cast<const char*>(data.data()), data.size()};
    }

    bool has(std::string_view name) const override {
        return _assets.contains(std::string(name));
    }

    std::vector<std::string> list() const override {
        std::vector<std::string> names;
        names.reserve(_assets.size());
        for (const auto& [name, _] : _assets) {
            names.push_back(name);
        }
        return names;
    }

    Result<void> extractTo(const std::filesystem::path& dir) const override {
        namespace fs = std::filesystem;

        for (const auto& [name, entry] : _assets) {
            auto path = dir / name;

            auto parentDir = path.parent_path();
            if (!parentDir.empty() && !fs::exists(parentDir)) {
                std::error_code ec;
                fs::create_directories(parentDir, ec);
                if (ec) {
                    return Err<void>("Failed to create directory: " + parentDir.string());
                }
            }

            std::ofstream file(path, std::ios::binary);
            if (!file) {
                return Err<void>("Failed to open file for writing: " + path.string());
            }
            file.write(reinterpret_cast<const char*>(entry.data), entry.size);
            if (!file) {
                return Err<void>("Failed to write file: " + path.string());
            }
            ydebug("Extracted: {} ({} bytes)", name, entry.size);
        }

        // Write extraction marker
        auto marker = getExtractionMarker(dir);
        fs::create_directories(marker.parent_path());
        std::ofstream markerFile(marker);
        if (markerFile) {
            markerFile << YETTY_BUILD_VERSION;
        }

        return Ok();
    }

    Result<void> extractAsset(std::string_view name,
                               const std::filesystem::path& path) const override {
        auto data = get(name);
        if (data.empty()) {
            return Err<void>("Asset not found: " + std::string(name));
        }

        auto parentDir = path.parent_path();
        if (!parentDir.empty() && !std::filesystem::exists(parentDir)) {
            std::error_code ec;
            std::filesystem::create_directories(parentDir, ec);
            if (ec) {
                return Err<void>("Failed to create directory: " + parentDir.string());
            }
        }

        std::ofstream file(path, std::ios::binary);
        if (!file) {
            return Err<void>("Failed to open file: " + path.string());
        }
        file.write(reinterpret_cast<const char*>(data.data()), data.size());
        return Ok();
    }

private:
    void registerAsset(const std::string& name, const uint8_t* data, size_t size) {
        _assets[name] = {data, size};
    }

    std::unordered_map<std::string, AssetEntry> _assets;
};

bool IncbinAssets::needsExtraction(const std::filesystem::path& cacheDir) {
    auto marker = getExtractionMarker(cacheDir);
    if (!std::filesystem::exists(marker)) {
        return true;
    }
    std::ifstream file(marker);
    std::string version;
    std::getline(file, version);
    return version != YETTY_BUILD_VERSION;
}

// Factory
Result<IncbinAssets*> IncbinAssets::createImpl() {
    auto* impl = new IncbinAssetsImpl();
    if (auto res = impl->init(); !res) {
        delete impl;
        return Err<IncbinAssets*>("Failed to init IncbinAssets", res);
    }
    return Ok(static_cast<IncbinAssets*>(impl));
}

} // namespace yetty
