// Auto-generated from sdf-primitives.yaml - DO NOT EDIT
// Generated by: src/yetty/ypaint/sdf/gen-sdf-code.py


#include <yetty/ypaint/sdf/ypaint-sdf-prim.gen.h>
#include <string.h>

YPaintIdResult ypaint_sdf_add_circle(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfCircle* geom) {
    float data[8];
    uint32_t tmp;

    tmp = YPAINT_SDF_CIRCLE;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->r;

    return ypaint_buffer_add_prim(buf, data, 8);
}

YPaintIdResult ypaint_sdf_add_box(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfBox* geom) {
    float data[10];
    uint32_t tmp;

    tmp = YPAINT_SDF_BOX;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->hw;
    data[8] = geom->hh;
    data[9] = geom->round;

    return ypaint_buffer_add_prim(buf, data, 10);
}

YPaintIdResult ypaint_sdf_add_segment(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfSegment* geom) {
    float data[9];
    uint32_t tmp;

    tmp = YPAINT_SDF_SEGMENT;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->x0;
    data[6] = geom->y0;
    data[7] = geom->x1;
    data[8] = geom->y1;

    return ypaint_buffer_add_prim(buf, data, 9);
}

YPaintIdResult ypaint_sdf_add_triangle(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfTriangle* geom) {
    float data[11];
    uint32_t tmp;

    tmp = YPAINT_SDF_TRIANGLE;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->ax;
    data[6] = geom->ay;
    data[7] = geom->bx;
    data[8] = geom->by;
    data[9] = geom->cx;
    data[10] = geom->cy;

    return ypaint_buffer_add_prim(buf, data, 11);
}

YPaintIdResult ypaint_sdf_add_ellipse(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfEllipse* geom) {
    float data[9];
    uint32_t tmp;

    tmp = YPAINT_SDF_ELLIPSE;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->rx;
    data[8] = geom->ry;

    return ypaint_buffer_add_prim(buf, data, 9);
}

YPaintIdResult ypaint_sdf_add_arc(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfArc* geom) {
    float data[11];
    uint32_t tmp;

    tmp = YPAINT_SDF_ARC;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->sc_x;
    data[8] = geom->sc_y;
    data[9] = geom->ra;
    data[10] = geom->rb;

    return ypaint_buffer_add_prim(buf, data, 11);
}

YPaintIdResult ypaint_sdf_add_rounded_box(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfRoundedBox* geom) {
    float data[13];
    uint32_t tmp;

    tmp = YPAINT_SDF_ROUNDED_BOX;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->hw;
    data[8] = geom->hh;
    data[9] = geom->r0;
    data[10] = geom->r1;
    data[11] = geom->r2;
    data[12] = geom->r3;

    return ypaint_buffer_add_prim(buf, data, 13);
}

YPaintIdResult ypaint_sdf_add_rhombus(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfRhombus* geom) {
    float data[9];
    uint32_t tmp;

    tmp = YPAINT_SDF_RHOMBUS;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->bx;
    data[8] = geom->by;

    return ypaint_buffer_add_prim(buf, data, 9);
}

YPaintIdResult ypaint_sdf_add_pentagon(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfPentagon* geom) {
    float data[8];
    uint32_t tmp;

    tmp = YPAINT_SDF_PENTAGON;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->r;

    return ypaint_buffer_add_prim(buf, data, 8);
}

YPaintIdResult ypaint_sdf_add_hexagon(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfHexagon* geom) {
    float data[8];
    uint32_t tmp;

    tmp = YPAINT_SDF_HEXAGON;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->r;

    return ypaint_buffer_add_prim(buf, data, 8);
}

YPaintIdResult ypaint_sdf_add_star(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfStar* geom) {
    float data[10];
    uint32_t tmp;

    tmp = YPAINT_SDF_STAR;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->r;
    data[8] = geom->n;
    data[9] = geom->m;

    return ypaint_buffer_add_prim(buf, data, 10);
}

YPaintIdResult ypaint_sdf_add_pie(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfPie* geom) {
    float data[10];
    uint32_t tmp;

    tmp = YPAINT_SDF_PIE;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->sc_x;
    data[8] = geom->sc_y;
    data[9] = geom->r;

    return ypaint_buffer_add_prim(buf, data, 10);
}

YPaintIdResult ypaint_sdf_add_ring(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfRing* geom) {
    float data[11];
    uint32_t tmp;

    tmp = YPAINT_SDF_RING;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->nx;
    data[8] = geom->ny;
    data[9] = geom->r;
    data[10] = geom->th;

    return ypaint_buffer_add_prim(buf, data, 11);
}

YPaintIdResult ypaint_sdf_add_heart(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfHeart* geom) {
    float data[8];
    uint32_t tmp;

    tmp = YPAINT_SDF_HEART;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->scale;

    return ypaint_buffer_add_prim(buf, data, 8);
}

YPaintIdResult ypaint_sdf_add_cross(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfCross* geom) {
    float data[10];
    uint32_t tmp;

    tmp = YPAINT_SDF_CROSS;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->bx;
    data[8] = geom->by;
    data[9] = geom->r;

    return ypaint_buffer_add_prim(buf, data, 10);
}

YPaintIdResult ypaint_sdf_add_rounded_x(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfRoundedX* geom) {
    float data[9];
    uint32_t tmp;

    tmp = YPAINT_SDF_ROUNDED_X;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->w;
    data[8] = geom->r;

    return ypaint_buffer_add_prim(buf, data, 9);
}

YPaintIdResult ypaint_sdf_add_capsule(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfCapsule* geom) {
    float data[10];
    uint32_t tmp;

    tmp = YPAINT_SDF_CAPSULE;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->ax;
    data[6] = geom->ay;
    data[7] = geom->bx;
    data[8] = geom->by;
    data[9] = geom->r;

    return ypaint_buffer_add_prim(buf, data, 10);
}

YPaintIdResult ypaint_sdf_add_moon(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfMoon* geom) {
    float data[10];
    uint32_t tmp;

    tmp = YPAINT_SDF_MOON;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->d;
    data[8] = geom->ra;
    data[9] = geom->rb;

    return ypaint_buffer_add_prim(buf, data, 10);
}

YPaintIdResult ypaint_sdf_add_egg(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfEgg* geom) {
    float data[9];
    uint32_t tmp;

    tmp = YPAINT_SDF_EGG;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->ra;
    data[8] = geom->rb;

    return ypaint_buffer_add_prim(buf, data, 9);
}

YPaintIdResult ypaint_sdf_add_octogon(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfOctogon* geom) {
    float data[8];
    uint32_t tmp;

    tmp = YPAINT_SDF_OCTOGON;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->r;

    return ypaint_buffer_add_prim(buf, data, 8);
}

YPaintIdResult ypaint_sdf_add_hexagram(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfHexagram* geom) {
    float data[8];
    uint32_t tmp;

    tmp = YPAINT_SDF_HEXAGRAM;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->r;

    return ypaint_buffer_add_prim(buf, data, 8);
}

YPaintIdResult ypaint_sdf_add_pentagram(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfPentagram* geom) {
    float data[8];
    uint32_t tmp;

    tmp = YPAINT_SDF_PENTAGRAM;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->cx;
    data[6] = geom->cy;
    data[7] = geom->r;

    return ypaint_buffer_add_prim(buf, data, 8);
}

YPaintIdResult ypaint_sdf_add_sphere_3d(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfSphere3D* geom) {
    float data[9];
    uint32_t tmp;

    tmp = YPAINT_SDF_SPHERE_3D;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->px;
    data[6] = geom->py;
    data[7] = geom->pz;
    data[8] = geom->r;

    return ypaint_buffer_add_prim(buf, data, 9);
}

YPaintIdResult ypaint_sdf_add_box_3d(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfBox3D* geom) {
    float data[11];
    uint32_t tmp;

    tmp = YPAINT_SDF_BOX_3D;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->px;
    data[6] = geom->py;
    data[7] = geom->pz;
    data[8] = geom->bx;
    data[9] = geom->by;
    data[10] = geom->bz;

    return ypaint_buffer_add_prim(buf, data, 11);
}

YPaintIdResult ypaint_sdf_add_torus_3d(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfTorus3D* geom) {
    float data[10];
    uint32_t tmp;

    tmp = YPAINT_SDF_TORUS_3D;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->px;
    data[6] = geom->py;
    data[7] = geom->pz;
    data[8] = geom->majorR;
    data[9] = geom->minorR;

    return ypaint_buffer_add_prim(buf, data, 10);
}

YPaintIdResult ypaint_sdf_add_cylinder_3d(YPaintBufferHandle buf, uint32_t zOrder, uint32_t fillColor, uint32_t strokeColor, float strokeWidth, const YPaintSdfCylinder3D* geom) {
    float data[10];
    uint32_t tmp;

    tmp = YPAINT_SDF_CYLINDER_3D;
    memcpy(&data[0], &tmp, sizeof(tmp));
    tmp = zOrder;
    memcpy(&data[1], &tmp, sizeof(tmp));
    tmp = fillColor;
    memcpy(&data[2], &tmp, sizeof(tmp));
    tmp = strokeColor;
    memcpy(&data[3], &tmp, sizeof(tmp));
    data[4] = strokeWidth;
    data[5] = geom->px;
    data[6] = geom->py;
    data[7] = geom->pz;
    data[8] = geom->r;
    data[9] = geom->h;

    return ypaint_buffer_add_prim(buf, data, 10);
}
